import {archiveRequest} from './archive-request.mjs?v=5061f3da916d';
const CACHE='tiangong-v3-pending';
export const readLocal=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
export class ArchiveStore{
 constructor(onStatus=()=>{}){this.onStatus=onStatus;this.records=new Map();this.pending={};this.scope=null;this.online=false;this.chain=Promise.resolve();this.initialized=false}
 async init(){try{const r=await archiveRequest({cache:'no-store'});if(!r.ok)throw Error('读取未成功');const data=await r.json();const previous=readLocal(CACHE);if(previous?.scope&&previous.scope!==data.scope&&Object.keys(previous.pending||{}).length){this.initialized=false;this.online=false;this.scope=previous.scope;this.pending=previous.pending;this.onStatus('身份已改变，原草稿保留在设备；请先导出备份');return false}this.scope=data.scope;this.records=new Map(data.records.map(r=>[r.key,r]));const cache=readLocal(CACHE);if(cache&&(cache.scope===this.scope||cache.scope===null))this.pending=cache.pending||{};for(const [key,p]of Object.entries(this.pending)){if(p.revision===null&&!this.records.has(key))p.revision=0}this.online=true;this.initialized=true;this.report();return true}catch{const cache=readLocal(CACHE);this.scope=cache?.scope||null;this.pending=cache?.pending||{};this.online=false;this.report();return false}}
 report(){const count=Object.keys(this.pending).length;this.onStatus(count?`有 ${count} 份修改待同步`:this.online?'已与云端档案同步':'尚未连接云端档案 · 可先制作')}
 cache(){try{localStorage.setItem(CACHE,JSON.stringify({scope:this.scope,pending:this.pending}))}catch{this.onStatus('设备草稿空间不足，请导出备份')}this.report()}
 get(key){return this.pending[key]?.value||this.records.get(key)?.value||null}
 all(){const map=new Map([...this.records].map(([k,r])=>[k,r.value]));Object.entries(this.pending).forEach(([k,r])=>map.set(k,r.value));return [...map].map(([key,value])=>({key,value}))}
 save(key,value){const snapshot=structuredClone(value),base=Object.hasOwn(this.pending,key)?this.pending[key].revision:(this.records.get(key)?.revision??(this.initialized?0:null));this.pending[key]={value:snapshot,revision:base};this.cache();const attempt=async()=>{if(!this.initialized||!this.online)return false;const current=this.pending[key];if(!current)return true;const sent=structuredClone(current);if(sent.revision===null){this.onStatus('设备草稿需要与云端档案核对，请到设置导出备份');return false}try{const r=await archiveRequest({method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,...sent})});if(!r.ok){if(r.status===409){this.onStatus('发现另一份修改，草稿已保留；请到设置处理同步');return false}throw Error('未同步')}const meta=await r.json();this.records.set(key,{key,value:sent.value,...meta});if(JSON.stringify(this.pending[key]?.value)===JSON.stringify(sent.value))delete this.pending[key];else this.pending[key].revision=meta.revision;this.cache();return true}catch{this.online=false;this.report();return false}};const result=this.chain.then(attempt,attempt);this.chain=result.catch(()=>{});return result}
 async retry(){await this.chain;const saved=structuredClone(this.pending),oldScope=this.scope;if(!await this.init())return false;if(oldScope&&this.scope!==oldScope){this.onStatus('当前云端不同，原设备草稿已保留，请先导出');this.pending=saved;return false}this.pending=saved;for(const [key,p]of Object.entries(saved)){const server=this.records.get(key);if(p.revision===null&&server){this.onStatus('云端中已有记录，设备草稿需先导出核对');return false}if(p.revision!==null&&(server?.revision||0)!==p.revision){this.onStatus('云端中已有更新，设备草稿已保留，请先导出核对');return false}p.revision=server?.revision||0;if(!await this.save(key,p.value))return false}this.report();return true}
 async remove(key){await this.chain;if(!this.online||this.pending[key])return false;const r=await archiveRequest({method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,revision:this.records.get(key)?.revision})});if(!r.ok)return false;this.records.delete(key);this.report();return true}
 async useCloud(){await this.chain;try{const r=await archiveRequest({cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();this.scope=data.scope;this.records=new Map(data.records.map(r=>[r.key,r]));this.pending={};this.online=true;this.initialized=true;this.cache();return true}catch{this.onStatus('未能读取云端版本，设备草稿仍然保留');return false}}
}
