import {WorkStage} from './work-stage.mjs?v=8e433e6a8218';
import {PARTS,RECIPES,recipe,partInfo,uid,snapPart,connect} from './atelier-data.mjs?v=8e433e6a8218';
const $=id=>document.getElementById(id);
export class Atelier{
 constructor(work,onChange,onSave,onExplain){this.onChange=onChange;this.onSave=onSave;this.onExplain=onExplain;this.history=[];this.work=structuredClone(work||recipe(0));this.stage=new WorkStage($('atelier-canvas'));this.selected=null;this.previous=null;this.abort=new AbortController();this.render();this.bind();this.stage.setWork(this.work);this.onChange(this.work)}
 setWork(work){this.remember();this.work=structuredClone(work);this.selected=null;this.previous=null;this.refresh();this.onChange(this.work)}
 remember(){this.history.push(structuredClone(this.work));if(this.history.length>35)this.history.shift()}
 change(fn){this.remember();fn();this.work.updated=Date.now();this.refresh();this.onChange(this.work)}
 select(id){if(this.selected!==id)this.previous=this.selected;this.selected=id;this.stage.select(id);const n=this.work.nodes.find(n=>n.id===id);$('toy-selected').textContent=n?`${partInfo(n.type).name} · 高 ${n.y.toFixed(1)} 格 · 已连接 ${this.work.links.filter(l=>l.includes(id)).length} 处`:'点选部件，拖动位置；拖动空白处旋转视角。';$('toy-part-select').value=id||''}
 refresh(){this.stage.setWork(this.work);this.render();this.select(this.selected);$('toy-run').textContent='试运行 ▷';this.stage.running=false}
 render(){ $('toy-name').textContent=this.work.name;$('toy-help').textContent=RECIPES[this.work.recipe]?.text||'连接、转动、叠搭，试出自己的小机关。';$('toy-recipes').innerHTML=RECIPES.map((r,i)=>`<button data-recipe="${i}" class="${i===this.work.recipe?'active':''}">${r.name}</button>`).join('');$('toy-parts').innerHTML='<span>添一件</span>'+PARTS.map(p=>`<button data-part="${p.id}">${p.name}</button>`).join('');if(!$('toy-part-select')){const label=document.createElement('label');label.innerHTML='桌上部件 <select id="toy-part-select" aria-label="选择桌上部件"></select>';$('toy-tools').insertBefore(label,$('toy-selected'));const row=document.createElement('div');row.className='tool-row';row.innerHTML='<button data-move="-1,0">向左</button><button data-move="1,0">向右</button><button data-move="0,-1">向后</button><button data-move="0,1">向前</button><button id="toy-view-reset">视角归正</button>';$('toy-tools').insertBefore(row,$('toy-selected'))}$('toy-part-select').innerHTML='<option value="">点选一件</option>'+this.work.nodes.map((n,i)=>`<option value="${n.id}">${i+1} · ${partInfo(n.type).name}</option>`).join('');$('toy-undo').disabled=!this.history.length}
 bind(){const signal=this.abort.signal,listen=(id,fn)=>$(id).addEventListener('click',fn,{signal});listen('toy-recipes',e=>{const b=e.target.closest('[data-recipe]');if(b){const w=recipe(Number(b.dataset.recipe));w.era=this.work.era;this.setWork(w);this.onNew?.()}});listen('toy-parts',e=>{const b=e.target.closest('[data-part]');if(!b)return;if(this.work.nodes.length>=64){this.onExplain('桌面已放满 64 件部件。可以先收藏这一件，再开一张工作台。');return}const n={id:uid(),type:b.dataset.part,x:0,y:partInfo(b.dataset.part).half+.2,z:2.5,ry:0,color:$('toy-color').value};this.change(()=>this.work.nodes.push(n));this.select(n.id)});listen('toy-run',()=>{this.stage.running=!this.stage.running;$('toy-run').textContent=this.stage.running?'停下观看 □':'试运行 ▷';$('toy-help').textContent=this.stage.running?'连线代表设计中的传动关系，试运行是机关动作预览。':'点选部件继续调整，或把这一件收入作品馆。'});listen('toy-rotate',()=>this.editSelected(n=>n.ry=(n.ry+Math.PI/2)%(Math.PI*2)));listen('toy-lift',()=>this.editSelected(n=>n.y=Math.min(7,n.y+.25)));listen('toy-lower',()=>this.editSelected(n=>n.y=Math.max(partInfo(n.type).half,n.y-.25)));listen('toy-remove',()=>{if(!this.selected)return;this.change(()=>{this.work.nodes=this.work.nodes.filter(n=>n.id!==this.selected);this.work.links=this.work.links.filter(l=>!l.includes(this.selected));this.selected=null})});listen('toy-connect',()=>{if(!this.selected||!this.previous)return this.onExplain('先选择一件，再选择另一件，便可建立连接。金色连线表示你设计的传动或联动关系。');this.change(()=>connect(this.work,this.previous,this.selected))});listen('toy-undo',()=>{if(!this.history.length)return;this.work=this.history.pop();this.refresh();this.onChange(this.work)});listen('toy-save',()=>{if(!this.work.nodes.length)return this.onExplain('先往工作台放一件部件，再收藏作品。');this.onSave(this.work)});listen('toy-clear',()=>this.change(()=>{this.work.nodes=[];this.work.links=[];this.selected=null;this.work.name='自由工作台';this.work.recipe=-1}));listen('toy-help-toggle',()=>this.onExplain('点击部件选中，拖动可在当前高度平移；靠近榫口会吸附。抬高、放低和旋转按钮调整空间位置。先选两件，再建立连接。拖动空白处观察背面，滚轮缩放；键盘方向键也可移动选中部件。试运行展示设计的联动，不进行真实承载或碰撞验算。'));$('toy-color').addEventListener('change',()=>this.editSelected(n=>n.color=$('toy-color').value),{signal});$('toy-part-select').addEventListener('change',e=>this.select(e.target.value),{signal});$('toy-tools').addEventListener('click',e=>{const b=e.target.closest('[data-move]');if(b){const [x,z]=b.dataset.move.split(',').map(Number);this.move(x,z)}if(e.target.id==='toy-view-reset')this.stage.focus()},{signal});
 const canvas=$('atelier-canvas');canvas.tabIndex=0;canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;const hit=this.stage.pick(e);if(!hit){this.select(null);return}this.select(hit.userData.partId);this.stage.controls.enabled=false;this.stage.running=false;this.remember();const n=this.work.nodes.find(n=>n.id===this.selected),p=this.stage.ground(e,n.y);this.drag={n,p,start:{x:n.x,z:n.z}};canvas.setPointerCapture(e.pointerId)},{signal});canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const d=this.drag,p=this.stage.ground(e,d.n.y);if(!p||!d.p)return;d.n.x=Math.max(-7,Math.min(7,Math.round((d.start.x+p.x-d.p.x)*4)/4));d.n.z=Math.max(-7,Math.min(7,Math.round((d.start.z+p.z-d.p.z)*4)/4));const g=this.stage.group.children.find(g=>g.userData.partId===d.n.id);g.position.x=d.n.x;g.position.z=d.n.z;this.stage.outline?.update()},{signal});const finish=()=>{if(!this.drag)return;snapPart(this.work,this.drag.n.id);this.drag=null;this.stage.controls.enabled=true;this.work.updated=Date.now();this.refresh();this.onChange(this.work)};canvas.addEventListener('pointerup',finish,{signal});canvas.addEventListener('pointercancel',finish,{signal});canvas.addEventListener('keydown',e=>{const moves={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(moves[e.key]){e.preventDefault();this.move(...moves[e.key])}},{signal})}
 move(x,z){this.editSelected(n=>{n.x=Math.max(-7,Math.min(7,n.x+x*.25));n.z=Math.max(-7,Math.min(7,n.z+z*.25));snapPart(this.work,n.id)})}
 editSelected(fn){const n=this.work.nodes.find(n=>n.id===this.selected);if(!n)return this.onExplain('先点选一件部件，或从“桌上部件”中选择。');this.change(()=>fn(n))}
 dispose(){this.abort.abort();this.stage.dispose()}
}
