const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const files=['index.html','chronicle.css','revision.css','era-stories.mjs','chronicle.mjs','rocket-atlas.mjs','rocket-atlas-model.mjs','story-revision.mjs','trial-guide.mjs','chronicle-data.mjs','chronicle-world.mjs','chronicle-lab.mjs','lab-rules.mjs','craft-flow.mjs','sequence-diagram.mjs','game-audio.mjs','atelier.mjs','atelier-data.mjs','atelier-models.mjs','work-stage.mjs','poster.mjs','archive-store.mjs','archive-request.mjs','runtime-config.mjs','palace-v2.html','palace.css','palace-data.js','palace.mjs','palace-world.mjs','palace-models.mjs','palace-craft.mjs','workshop.html','workshop.css','art-v3.css','game-data.js','workshop.js','legacy.html','styles.css','app.js','adventure.js','model3d.js'];
for(const f of ['game-data.js','workshop.js','palace-data.js'])new vm.Script(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of files.filter(f=>f.endsWith('.mjs'))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr||f)}
const output=path.resolve(__dirname,'dist');if(path.dirname(output)!==__dirname||path.basename(output)!=='dist'||fs.existsSync(output)&&fs.lstatSync(output).isSymbolicLink())throw Error('Unsafe build target');fs.rmSync(output,{recursive:true,force:true});
const client=path.join(output,'client');fs.mkdirSync(client,{recursive:true});for(const f of files)fs.copyFileSync(f,path.join(client,f));
// A release-wide fingerprint keeps returning visitors from mixing old and new modules.
const revision=require('node:crypto').createHash('sha256').update(files.map(f=>fs.readFileSync(f,'utf8')).join('\n')).digest('hex').slice(0,12);
for(const f of files){if(!/\.(html|m?js)$/.test(f))continue;let content=fs.readFileSync(path.join(client,f),'utf8');content=content.replace(/(from\s*['"])(\.\.?\/[^'"?]+\.m?js)(['"])/g,(_,a,b,c)=>a+b+'?v='+revision+c).replace(/((?:src|href)=")((?!https?:)[^"?]+\.(?:css|m?js))(")/g,(_,a,b,c)=>a+b+'?v='+revision+c).replace('"three":"./vendor/three/three.module.js"','"three":"./vendor/three/three.module.js?v='+revision+'"');fs.writeFileSync(path.join(client,f),content)}
for(const dir of ['assets','vendor'])fs.cpSync(dir,path.join(client,dir),{recursive:true,filter:p=>{const name=path.basename(p);if(p.endsWith('.md'))return false;if(p.includes('posters')&&fs.statSync(p).isFile())return ['title-trails.webp','title-clean.webp'].includes(name);if((p.includes('rulers')||p.includes('chibi-rulers'))&&p.endsWith('.png'))return false;return name!=='throne-opening-v3.png'}});
fs.mkdirSync('dist/server',{recursive:true});const pure=['chronicle-data.mjs','atelier-data.mjs'].map(f=>fs.readFileSync(f,'utf8').replace(/^export /gm,'')).join('\n');const worker=fs.readFileSync('server.mjs','utf8').replace(/^import .*;\r?\n/gm,'');fs.writeFileSync('dist/server/index.js',require('esbuild').transformSync(pure+'\n'+worker,{format:'esm',target:'es2022',minify:true}).code);
fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');fs.cpSync('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Built the chronicle, 3D atelier, preserved games and account archive.');
