const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{spawnSync}=require('node:child_process');
const files=['index.html','chronicle.css','era-stories.mjs','chronicle.mjs','chronicle-data.mjs','chronicle-world.mjs','chronicle-lab.mjs','lab-rules.mjs','atelier.mjs','atelier-data.mjs','atelier-models.mjs','work-stage.mjs','poster.mjs','archive-store.mjs','palace-v2.html','palace.css','palace-data.js','palace.mjs','palace-world.mjs','palace-models.mjs','palace-craft.mjs','workshop.html','workshop.css','art-v3.css','game-data.js','workshop.js','legacy.html','styles.css','app.js','adventure.js','model3d.js'];
for(const f of ['game-data.js','workshop.js','palace-data.js'])new vm.Script(fs.readFileSync(f,'utf8'),{filename:f});
for(const f of files.filter(f=>f.endsWith('.mjs'))){const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr||f)}
const output=path.resolve(__dirname,'dist');if(path.dirname(output)!==__dirname||path.basename(output)!=='dist'||fs.existsSync(output)&&fs.lstatSync(output).isSymbolicLink())throw Error('Unsafe build target');fs.rmSync(output,{recursive:true,force:true});
const client=path.join(output,'client');fs.mkdirSync(client,{recursive:true});for(const f of files)fs.copyFileSync(f,path.join(client,f));
for(const dir of ['assets','vendor'])fs.cpSync(dir,path.join(client,dir),{recursive:true,filter:p=>!p.endsWith('.md')&&!(p.includes('rulers')&&p.endsWith('.png'))&&path.basename(p)!=='throne-opening-v3.png'});
fs.mkdirSync('dist/server',{recursive:true});const pure=['chronicle-data.mjs','atelier-data.mjs'].map(f=>fs.readFileSync(f,'utf8').replace(/^export /gm,'')).join('\n');const worker=fs.readFileSync('server.mjs','utf8').replace(/^import .*;\r?\n/gm,'');fs.writeFileSync('dist/server/index.js',require('esbuild').transformSync(pure+'\n'+worker,{format:'esm',target:'es2022',minify:true}).code);
fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');fs.cpSync('drizzle','dist/.openai/drizzle',{recursive:true});
console.log('Built the chronicle, 3D atelier, preserved games and account archive.');
