import * as T from './vendor/three/three.module.js?v=110b4a9c1695';
import {WorkStage} from './work-stage.mjs?v=110b4a9c1695';
import {makePart} from './atelier-models.mjs?v=110b4a9c1695';
import {box,cylinder,ring,materials} from './palace-models.mjs?v=110b4a9c1695';
import {newTrial,trialAction,SAMPLE_DATA} from './lab-rules.mjs?v=110b4a9c1695';
import {trialGuide} from './trial-guide.mjs?v=110b4a9c1695';
import {chibi} from './story-revision.mjs?v=110b4a9c1695';
const $=id=>document.getElementById(id),names={gate:'开门',lift:'升台',bell:'响铃'};
export class ChronicleLab{
 constructor(chapter,onDone){this.chapter=chapter;this.onDone=onDone;this.state=newTrial(chapter.id,chapter.level);$('lab-guide').open=chapter.level<2;this.abort=new AbortController();this.dialog=$('lab-modal');$('lab-title').textContent=chapter.title;$('lab-kicker').textContent=chapter.verb+' · 留下一次亲手发现';$('lab-story').textContent=chapter.summary;$('lab-science').textContent=chapter.lesson;$('lab-feedback').textContent='';$('lab-done').disabled=true;this.dialog.showModal();try{this.stage=new WorkStage($('lab-canvas'));this.stage.controls.enableRotate=true;this.stage.onFrame=(dt,t)=>this.animate(dt,t)}catch{ $('lab-object-label').textContent='图形显示不可用，仍可使用右侧操作完成实验。' }this.render();this.visual();$('lab-guide').addEventListener('toggle',()=>this.guide(),{signal:this.abort.signal});$('lab-actions').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.act(b.dataset.action,b.dataset.value)},{signal:this.abort.signal});$('lab-actions').addEventListener('input',e=>{if(e.target.dataset.mark!==undefined)this.act('mark',[Number(e.target.dataset.mark),e.target.value],false);if(e.target.id==='mix-color')this.act('color',e.target.value,false)},{signal:this.abort.signal});$('lab-done').onclick=()=>{if(this.state.passed)this.onDone(this.state)};
 const canvas=$('lab-canvas');canvas.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY];if(chapter.id==='mix'){this.dragging=true;this.angle=null;this.sweep=0;this.stage&&(this.stage.controls.enabled=false);canvas.setPointerCapture(e.pointerId)}},{signal:this.abort.signal});canvas.addEventListener('pointermove',e=>{if(!this.dragging)return;const r=canvas.getBoundingClientRect(),angle=Math.atan2(e.clientY-r.top-r.height*.52,e.clientX-r.left-r.width*.5);if(this.angle!==null){let d=angle-this.angle;d=Math.atan2(Math.sin(d),Math.cos(d));this.sweep+=Math.abs(d);if(this.sweep>Math.PI*1.6){this.act('stir');this.sweep=0}}this.angle=angle},{signal:this.abort.signal});canvas.addEventListener('pointerup',e=>{if(this.dragging){this.dragging=false;this.stage&&(this.stage.controls.enabled=true);return}if(this.down&&Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])<8){const hit=this.stage?.pick(e),v=hit?.userData.action;if(v)this.act(v[0],v[1])}},{signal:this.abort.signal});
 }
 act(a,v,rerender=true){const result=trialAction(this.state,a,v);if(a==='mark'){const out=$('lab-actions').querySelector('[data-offset="'+v[0]+'"]');if(out)out.textContent=this.state.marks[v[0]];}if(result.text)$('lab-feedback').textContent=result.text;$('lab-done').disabled=!this.state.passed;if(rerender)this.render();this.guide();$('lab-reaction').innerHTML=chibi(this.chapter.era,this.state.passed?2:result.ok===false?7:3);this.visual();if(a==='test'&&this.state.id==='sequence')this.playStart=performance.now();if(a==='test'&&this.state.id==='drive')this.drive=true}
 button(a,v,text,disabled=false){return `<button data-action="${a}" data-value="${v}" ${disabled?'disabled':''}>${text}</button>`}
 render(){const s=this.state,b=(...a)=>this.button(...a);let html='';
 if(s.id==='measure')html='<p class="instruction">移动零刻度，与铜色基准线对齐。木片本身不动。</p>'+s.marks.map((v,i)=>`<label>尺 ${i+1}${this.chapter.level<2?` · 零点偏移 <output data-offset="${i}">${v}</output>`:''}<input type="range" min="-4" max="4" step="1" value="${v}" data-mark="${i}" aria-label="尺 ${i+1} 的零点偏移"></label>`).join('')+b('test','','比较三份尺寸');
 if(s.id==='material')html='<p>点击台上的样品，观察同一载荷下的不同反应。提篮要求承载记录至少为 6。</p>'+SAMPLE_DATA.map(d=>`<div class="sample-row"><strong>${d.name}</strong>${b('test',d.id,s.seen.includes(d.id)?'再看一次':'放上砝码')}${s.seen.includes(d.id)?`<small>重 ${d.weight} · 弯 ${d.bend} · 载 ${d.load}</small>`:''}${b('choose',d.id,'采用')}</div>`).join('');
 if(s.id==='join')html='<p>铜色长边是榫口方向。先底座，后立柱，再落横梁。</p><p>预览件转向：'+s.rotation*90+'°</p>'+b('rotate','','旋转预览件 90°')+'<div class="actions">'+[['base','底座'],['left','左柱'],['right','右柱'],['top','横梁']].map(([id,n])=>b('insert',id,(s.pieces.includes(id)?'✓ ':'落下 ')+n,s.pieces.includes(id))).join('')+'</div>';
 if(s.id==='mix')html='<p>选好颜色。按这份试样记录操作：润湿 → 分散 → 合胶 → 轻拌 → 试涂。</p><label>颜料色 <input id="mix-color" type="color" value="'+s.colors+'"></label><div class="actions">'+[['water','清水'],['pigment','已研细颜料'],['binder','预制胶液']].map(([id,n])=>b('add',id,n,s.ingredients.includes(id))).join('')+'</div><p class="hint">在画面碗边划一圈，或使用下方动作。</p>'+b('stir','','沿碗缘慢拌一圈')+b('test','','试涂 · 等待干燥');
 if(s.id==='drive')html='<p>选择用途，然后将三个轮接到各自轴位。</p><div class="actions">'+b('purpose','strong',(s.purpose==='strong'?'✓ ':'')+'稳稳提篮')+b('purpose','fast',(s.purpose==='fast'?'✓ ':'')+'快速转旗')+'</div>'+['input','middle','output'].map((id,i)=>b('connect',id,(s.connections.includes(id)?'✓ ':'接上 ')+['输入轮','中间轮','输出轮'][i],s.connections.includes(id))).join('')+b('test','','摇动输入柄');
 if(s.id==='sequence')html='<p>交换相邻动作，让升台顺利通过门洞。</p><div class="sequence-strip">'+s.sequence.map((id,i)=>`<span>${i+1} · ${names[id]}</span>${i<2?b('swap',i,'⇄'):''}`).join('')+'</div>'+b('test','','让机关演一次');
 if(s.id==='diagnose')html='<p>让试验只改变一个条件。</p>'+b('control','humidity',(s.control==='humidity'?'✓ ':'')+'同种木料，仅改变环境湿度')+b('control','species',(s.control==='species'?'✓ ':'')+'湿木片与另一种干木片比较')+b('observe','','等待 · 测量样片')+'<div class="actions">'+b('conclude','movement','湿度相关的胀缩')+b('conclude','careless','一定是制作不认真')+'</div>';
 if(s.id==='assembly')html='<p>点选三处标记，找到接合处的缺口，再对齐并完成展示。</p>'+[['shell','壳片'],['ring','接合'],['mark','序号']].map(([id,n])=>b('inspect',id,(s.checked.includes(id)?'✓ ':'检查 ')+n)).join('')+b('align','','对齐接合标记')+b('test','','完成总装检查');
 $('lab-actions').innerHTML=html;if(s.passed)$('lab-actions').querySelectorAll('button,input,select').forEach(e=>e.disabled=true);this.guide();$('lab-reaction').innerHTML=chibi(this.chapter.era,s.passed?2:3);
 }
 visual(){if(!this.stage)return;const s=this.state,g=new T.Group(),m=materials(),add=(type,x,y,z=0,action)=>{const p=makePart(type,m,s.colors);p.position.set(x,y,z);p.userData.action=action;g.add(p);return p};let label='';
 if(s.id==='measure'){for(let i=0;i<3;i++){const z=(i-1)*1.3;box(g,m.wood,3.6,.2,.65,.3,.2,z);const ruler=new T.Group();g.add(ruler);ruler.position.set(s.marks[i]*.22,.4,z+.5);box(ruler,m.paper,4,.045,.3,.4);for(let k=0;k<17;k++)box(ruler,k===0?m.amber:m.dark,.018,.025,k%4===0?.26:.12,-1.6+k*.24,.04);box(g,m.metal,.025,.04,1.12,-1.6,.46,z)}label='同一条基准，才有可比较的尺寸。'}
 if(s.id==='material'){SAMPLE_DATA.forEach((d,i)=>{const p=new T.Group();p.position.x=(i-1)*2.2;p.userData.action=['test',d.id];g.add(p);for(const x of [-.8,.8])box(p,m.stone,.3,.5,.7,x,.25);const sample=box(p,m.wood,2,.1+(i*.11),.55,0,.58);if(s.seen.includes(d.id)){cylinder(p,m.metal,.25,.4,0,.87);sample.rotation.z=(d.bend-3)*.01}});label='样片试验记录 · 相对数值，仅供本次比较'}
 if(s.id==='join'){add('deck',0,.25);for(const [id,x,y,type]of [['left',-1.5,1.45,'post'],['right',1.5,1.45,'post'],['top',0,2.6,'beam']]){if(s.pieces.includes(id))add(type,x,y);else{const p=add(type,x,y+1,0,['insert',id]);p.rotation.y=s.rotation*Math.PI/2;p.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.3}})}}label='实体榫口 · 铜色轮廓标示落位方向'}
 if(s.id==='mix'){const bowl=cylinder(g,m.stone,1.25,.7,0,.35,0,36);const liquid=cylinder(g,s.ingredients.length>1?m.jade:m.paper,1.15,.04,0,.72,0,40);liquid.material=liquid.material.clone();liquid.material.color.set(s.ingredients.length>1?s.colors:'#a7bdba');for(let i=0;i<(s.stir?2:10);i++)box(g,m.jade,.1,.12,.1,Math.cos(i*2.4)*.8,.8,Math.sin(i*2.4)*.8);this.spoon=box(g,m.wood,.09,1.7,.09,.3,1.2,.3);this.spoon.rotation.z=.3;for(let i=0;i<3;i++)cylinder(g,[m.paper,m.jade,m.amber][i],.3,.5,(i-1)*1.3,.3,2.3);if(s.passed){const swatch=box(g,m.jade,1.5,.09,1.2,2,.2);swatch.material=liquid.material}label='水性胶彩示意 · 拌合、干燥过程经过时间压缩'}
 if(s.id==='drive'){this.rotors=[];const scales=s.purpose==='strong'?[.8,1,1.6]:[1.6,1,.8];for(let i=0;i<3;i++){const x=i===0?-(scales[0]+1)*.55:i===2?(scales[2]+1)*.55:0,p=add('gear',x,1.3);p.scale.setScalar(scales[i]);p.visible=s.connections.includes(['input','middle','output'][i]);this.rotors.push(p)}add('crank',-1.3,1.3,.5);label=s.purpose==='strong'?'小轮输入 · 大轮输出':'大轮输入 · 小轮输出'}
 if(s.id==='sequence'){add('deck',0,.2);for(const x of [-1.5,1.5])add('post',x,1.4);add('beam',0,2.55);this.gate=box(g,m.wood,2.55,1.8,.16,0,1.15,-.5);this.lift=add('basket',0,.8,.6);this.bell=add('bell',2.6,2);label='三段机关 · 带联锁的演示'}
 if(s.id==='diagnose'){for(let i=0;i<2;i++){const p=box(g,m.wood,s.observed&&i===1?2.2:2,.16,1.2,(i?1:-1)*1.6,.5);for(const x of [-1,1])box(g,m.metal,.035,.03,1.4,p.position.x+x,.62);if(s.observed&&i===1)ring(g,m.jade,.25,.02,1.6,1.2)}label=s.observed?'右侧：较湿环境 · 横向尺寸变化已作夸张示意':'一份对照样，一份实验样'}
 if(s.id==='assembly'){add('deck',0,.2);for(let i=0;i<3;i++){const id=['shell','ring','mark'][i],p=box(g,s.checked.includes(id)?m.jade:m.wood,1.2,.15,1.8,(i-1)*1.8,.45);p.userData.action=['inspect',id];if(i===1){const mark=ring(g,m.amber,.4,.035,0,.58,0);if(!s.aligned)mark.scale.x=.6}}label='总装图录检查 · 标记与视觉完整性'}

 this.stage.setGroup(g);this.stage.focus();$('lab-object-label').textContent=label;
 }
 guide(){const next=trialGuide(this.state);$('lab-guide-copy').textContent=next.text;const visible=$('lab-guide').open;$('lab-actions').querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('next-action',visible&&b.dataset.action===next.action&&(next.value===undefined||b.dataset.value===next.value)));$('lab-actions').querySelectorAll('[data-mark]').forEach(b=>b.classList.toggle('next-action',visible&&Number(b.dataset.mark)===next.mark));$('lab-done').classList.toggle('next-action',this.state.passed)}
 animate(dt,t){if(this.spoon&&this.dragging){this.spoon.position.x=Math.cos(t*4)*.6;this.spoon.position.z=Math.sin(t*4)*.6}if(this.drive)this.rotors?.forEach((p,i)=>p.userData.rotor.rotation.z+=dt*(i%2?-1:1)*(i===2?(this.state.purpose==='strong'?.5:2):1));if(this.playStart){const p=(performance.now()-this.playStart)/1000,sequence=this.state.sequence;let opened=false,lifted=false;for(let i=0;i<Math.min(3,Math.floor(p));i++){if(sequence[i]==='gate'){opened=true;this.gate.position.x=-2.4}if(sequence[i]==='lift'&&opened){lifted=true;this.lift.position.y=1.7}if(sequence[i]==='bell'&&lifted)this.bell.rotation.z=Math.sin(t*15)*.15}if(p>4)this.playStart=null}}
 dispose(){this.abort.abort();this.stage?.dispose();this.dialog.close();$('lab-done').onclick=null}
}
