import {GameAudio} from './game-audio.mjs';
import {RocketAtlas,PART_GROUPS,TOTAL_PARTS} from './rocket-atlas.mjs';
import {DIFFICULTIES,ENDINGS,chibi} from './story-revision.mjs';
import {ERAS,CHAPTERS,NODES,SOURCES,freshCampaign,sanitizeCampaign,legacyCampaign,completeChapter,dateLabel,eventFor} from './chronicle-data.mjs';
import {ChronicleWorld} from './chronicle-world.mjs';
import {ChronicleLab} from './chronicle-lab.mjs';
import {ArchiveStore,readLocal} from './archive-store.mjs';
import {Atelier} from './atelier.mjs';
import {recipe,uid,sanitizeWork,duplicateWork} from './atelier-data.mjs';
import {downloadFile,makePoster} from './poster.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const audio=new GameAudio();
const PERSON_NAMES=['嬴政','武曌','朱元璋（初名朱重八）','叶赫那拉氏'];
let atlas,endingStep=0,endingEra=0,endingBrowse=false,posterChosen=-1,sealTimer,sealStarted=false;
let s=freshCampaign(),selectedEra=0,world,lab,atelier,currentWorkKey=null,page=0,view='story',draftTimer,toastTimer,posterUrl;
const prefs=readLocal('tiangong-v3-prefs')||{};
const store=new ArchiveStore(text=>{$('sync-state').textContent=text;$('toy-save-status').textContent=text});
try{world=new ChronicleWorld($('world'),index=>{const c=CHAPTERS.find(c=>c.modules.includes(index));if(c&&s.completed.includes(c.id))showNote(c.title,s.results[c.id]?.note||c.lesson);else if(c?.id===CHAPTERS[s.chapter]?.id)startChapter()});world.configureNetwork(NODES);world.setQuality(!!prefs.simple)}catch(e){console.warn('三维场景初始化失败');$('graphics-note').hidden=false}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200)}
function suspend(){if(world)world.suspended=!!(lab||!$('atelier-screen').hidden||$('drawer').open||$('gallery-modal').open||!$('opening').hidden||!$('poster-cover').hidden||!$('game').hidden);if(atlas)atlas.paused=$('game').hidden||view!=='story'||!!lab||$('drawer').open||$('gallery-modal').open;if(atelier)atelier.stage.paused=$('atelier-screen').hidden||$('drawer').open||$('gallery-modal').open}
function showDrawer(html){$('drawer-body').innerHTML=html;if(!$('drawer').open)$('drawer').showModal();suspend()}
function showNote(title,text){showDrawer(`<p class="eyebrow">地宫札记</p><h2>${esc(title)}</h2><p>${esc(text)}</p>`)}
function save(){store.save(`campaign-${s.era}`,s);render()}
function eras(){$('eras').innerHTML=ERAS.map((e,i)=>`<button class="era-option ${i===posterChosen?'active':''}" data-era="${i}" aria-pressed="${i===posterChosen}"><img src="assets/rulers/${e.image}.webp" alt="${e.name}艺术形象"><span><strong>${e.name}</strong><small class="person-name">${PERSON_NAMES[i]}</small></span></button>`).join('');$('era-line').textContent=DIFFICULTIES[selectedEra].detail;$('era-place').textContent='四位人物操作、提示与进度规则完全相同；无倒计时，随时可重试。';const saved=sanitizeCampaign(store.get(`campaign-${selectedEra}`));$('resume').hidden=!saved?.entered;$('enter').hidden=false;$('enter').textContent=saved?.entered?'重看开场 · 入殿 ↓':'落玺 · 入殿 ↓';$('opening-art').dataset.era=selectedEra;world?.showThrone(selectedEra);suspend()}
function showOpening(){posterChosen=-1;view='opening';$('game').hidden=true;$('atelier-screen').hidden=true;$('poster-cover').hidden=true;$('opening').hidden=false;$('selection-art').hidden=false;$('opening-art').hidden=true;$('world').hidden=false;$('opening-art').style.cssText='';selectedEra=s.era;eras()}
function openCharacters(){posterChosen=-1;audio.unlock();$('selection-art').hidden=false;$('opening').hidden=false;$('poster-cover').classList.add('dissolving');setTimeout(()=>{$('poster-cover').hidden=true;suspend()},850);eras()}
function ensureAtlas(){if(atlas)return;try{atlas=new RocketAtlas($('atlas-canvas'),p=>{$('part-selection').innerHTML=`<h3>${p.name}</h3><p>第 ${p.group+1} 批 · ${p.group<s.chapter?'已点亮':'等待实验'}<br>对应：${CHAPTERS[p.group].title}</p>`;$('part-isolate').disabled=false});}catch{$('part-selection').innerHTML='<p>三维展示暂不可用，仍可展开零件清单与完成实验。</p>'}}
function renderParts(){ensureAtlas();atlas?.setProgress(s.chapter);$('atlas-status').textContent=`${s.chapter*24} / ${TOTAL_PARTS} 件已点亮`;$('part-filters').innerHTML='<button data-filter="-1">全部类别</button>'+PART_GROUPS.map((n,i)=>`<button data-filter="${i}" aria-pressed="${atlas?.filter===i}">${i<s.chapter?'●':'○'} ${n} <small>${i<s.chapter?24:0}/24</small></button>`).join('');$('part-list').innerHTML=PART_GROUPS.map((n,g)=>`<details><summary>${n} · ${g<s.chapter?'已点亮':'未点亮'}</summary>${Array.from({length:24},(_,i)=>`<button data-part="${g*24+i}">${n} ${String(i+1).padStart(2,'0')}</button>`).join('')}</details>`).join('')}
function render(){const c=CHAPTERS[s.chapter],e=ERAS[s.era],ev=eventFor(s);$('era-year').textContent=e.name+' · '+dateLabel(e.years[Math.min(s.chapter,7)]);$('chapter-label').textContent=c?`造物卷 · ${String(s.chapter+1).padStart(2,'0')} / 08`:'一卷成器 · 百工留名';$('chapter-title').textContent=c?.title||'此器已成，故事未尽';$('chapter-summary').textContent=c?.summary||'再去自由工作台，把新想法做成自己的作品；也可以开启另一个时代，听一段不同的工坊故事。';$('chapter-start').textContent=c?'动手点亮下一批 →':'重读专属结局 →';$('event-open').textContent=ev.title+' ↗';$('chapter-track').innerHTML=CHAPTERS.map((c,i)=>`<button class="${i===s.chapter?'active':i<s.chapter?'done':''}" data-chapter="${i}" aria-label="${i<s.chapter?'回看发现':i===s.chapter?'当前章节':'尚未经历'}：${c.title}" ${i>s.chapter?'disabled':''}><b>${i<s.chapter?'✓':String(i+1).padStart(2,'0')}</b><span>${c.verb}</span></button>`).join('');$('companion').innerHTML=chibi(s.era,s.chapter===8?6:3)+'<p>'+ (s.chapter===8?'此器已成，另一条命运等你揭开。':'每次发现，点亮一整批。')+'</p>';$('progress-label').textContent=`${s.chapter} / 8 段发现 · ${s.chapter*24} / 192 件零件`;renderParts();renderNetwork();updateExhibits()}
function renderNetwork(){let html='';for(let lane=0;lane<4;lane++){const nodes=NODES.filter(n=>n.branch===lane);html+=`<div class="network-lane"><b>${nodes[0].lane}</b>${nodes.map(n=>`<button class="tech-node ${s.known.includes(n.id)?'known':''}" data-node="${n.id}">${s.known.includes(n.id)?'✓ ':''}${n.name}</button>`).join('')}</div>`}html+=`<div class="network-end"><span>四条经验，在这里合流</span><button class="tech-node ${s.known.includes('final')?'known':''}" data-node="final">${s.known.includes('final')?'✓ ':''}巡天总成</button></div><p class="hint">经验来自章节中的发现。无需刷材料、反复点亮节点。</p>`;$('network').innerHTML=html}
function renderTeam(){}
function updateExhibits(){const works=store.all().filter(r=>r.key.startsWith('work-')&&r.value.featured).map(r=>sanitizeWork(r.value)).filter(Boolean);const signature=JSON.stringify(works.map(w=>[w.updated,w.name]));if(world&&world.exhibitSignature!==signature){world.exhibitSignature=signature;world.exhibitWorks(works)}}
function showView(next){if(next==='atelier'){openAtelier();return}if(next==='gallery'){openGallery();return}view=next;$('network-panel').hidden=next!=='network';for(const id of ['story-panel','companion','chapter-track','atlas-canvas','atlas-controls','atlas-inspector'])$(id).hidden=next!=='story';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===next));atlas?.resize();suspend()}
async function enter(resume=false){audio.unlock();audio.scene='hall';await ready;s=sanitizeCampaign(store.get(`campaign-${selectedEra}`))||(selectedEra===0?legacyCampaign(readLocal('tiangong-palace-v2')):freshCampaign(selectedEra));s.era=selectedEra;$('selection-art').hidden=true;$('poster-cover').hidden=true;$('opening-art').hidden=false;$('opening-art').style.cssText='';if(resume&&s.entered){$('opening').hidden=true;$('opening-art').hidden=true;$('game').hidden=false;$('world').hidden=true;render();showView('story');return}$('opening').hidden=true;$('descent').hidden=false;world&&(world.suspended=false);const lines=['殿上是诏令，殿下是双手。','视线越过御座，落向殿基。','穿过地基，听见百工。','灯火渐起，万象未形。','把这一卷未来，交给这个时代。'];const done=()=>{s.entered=true;$('opening-art').hidden=true;$('descent').hidden=true;$('game').hidden=false;$('world').hidden=true;save();showView('story')};if(world)world.descend(i=>$('descent-copy').textContent=lines[i],done,prefs.motion===false||matchMedia('(prefers-reduced-motion: reduce)').matches,p=>{const q=Math.min(1,p/.48);$('opening-art').style.transform=`scale(${1+q*.24}) translateY(${-q*38}%)`;$('opening-art').style.opacity=String(Math.max(0,1-Math.max(0,q-.45)/.55))});else{const anim=$('opening-art').animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(1.2) translateY(-30%)'}],{duration:1000,fill:'forwards'});anim.onfinish=done}}
function startChapter(){if(s.chapter>=8){ending();return}openLab()}
function openLab(){if(lab)return;audio.scene='lab';const chapter={...CHAPTERS[s.chapter],era:s.era,level:1,sound:kind=>audio.play(kind)};lab=new ChronicleLab(chapter,result=>{if(!completeChapter(s,result))return;closeLab();save();atlas?.setFilter(-1);atlas?.explode(1);$('explode-slider').value=100;$('explode-value').textContent='100%';toast('一整批 24 件零件已点亮。');if(s.chapter===8){ending();return}showDrawer(`<p class="eyebrow">第 ${s.chapter} 批 · 24 件零件点亮</p>${chibi(s.era,2)}<h2>${PART_GROUPS[s.chapter-1]}，已就绪。</h2><p>${esc(result.note)}</p><p>累计 ${s.chapter*24} / 192 件。回到拆解图，可以点选这一批零件。</p><div class="actions"><button class="primary" id="next-story">看本批零件 →</button><button id="reward-toy">去自由造物</button></div>`);$('next-story').onclick=()=>{$('drawer').close();atlas?.setFilter(s.chapter-1);renderParts()};$('reward-toy').onclick=()=>{$('drawer').close();openAtelier(recipe(chapter.toy))}});suspend()}
function closeLab(){lab?.dispose();lab=null;suspend()}
function ending(){endingBrowse=false;endingEra=s.era;audio.scene='ending';audio.play('success');endingStep=0;renderEnding()}
function renderEnding(){const e=ENDINGS[endingEra],beat=e.beats[endingStep];showDrawer(`${endingBrowse?'<button id="ending-index" class="secondary">← 全部结局</button>':''}<article class="ending-card"><p class="eyebrow">架空结局 · ${ERAS[endingEra].name} · ${dateLabel(e.year)}</p><h2>${e.title}</h2><div class="ending-reaction">${chibi(endingEra,beat[1])}</div><p class="ending-prose" key="${endingStep}">${beat[0]}</p><p class="hint">${endingStep+1} / ${e.beats.length} · 导弹改变命运的情节为虚构</p><div class="actions"><button id="ending-back" ${endingStep===0?'disabled':''}>上一段</button>${endingStep<e.beats.length-1?'<button id="ending-next" class="primary">继续读 →</button>':endingBrowse?'<span>本篇已读完，可选择下方其他人物。</span>':'<button id="ending-toy" class="primary">留下自己的作品</button><button id="ending-era">另一个时代</button>'}</div>${endingStep===e.beats.length-1&&(s.chapter>=8||endingBrowse)?`<section class="ending-library"><p class="eyebrow">一卷通关 · 四种命运</p><h3>直接查看其他人物结局</h3><p class="hint">无需重新制作，不改变你的故事进度。</p><div class="actions">${ERAS.map((era,i)=>i===endingEra?'':`<button data-ending-view="${i}">${chibi(i,3)}<span>${era.name}<small>阅读专属结局 →</small></span></button>`).join('')}</div></section>`:''}<details><summary>真实历史中的这一刻</summary><p>${e.history}</p><a href="${SOURCES[e.source].url}" target="_blank" rel="noopener noreferrer">${SOURCES[e.source].owner} · 史料出处 ↗</a></details></article>`);if(endingBrowse)$('ending-index').onclick=showAllEndings;$('ending-back').onclick=()=>{if(endingStep>0){endingStep--;renderEnding()}};if($('ending-next'))$('ending-next').onclick=()=>{endingStep++;renderEnding()};if($('ending-toy'))$('ending-toy').onclick=()=>{$('drawer').close();openAtelier(recipe(6))};if($('ending-era'))$('ending-era').onclick=()=>{$('drawer').close();showOpening()};$('drawer-body').querySelectorAll('[data-ending-view]').forEach(b=>b.onclick=()=>{if(s.chapter<8&&!endingBrowse)return;endingEra=Number(b.dataset.endingView);endingStep=0;audio.play('tick');renderEnding()})}
function showHistory(){const ev=eventFor(s),src=SOURCES[ev.source];showDrawer(`<p class="eyebrow">历史大事件 · ${dateLabel(ev.year)}</p>${chibi(s.era,ev.mood)}<h2>${ev.title}</h2><p>${ev.text}</p><a href="${src.url}" target="_blank" rel="noopener noreferrer">${src.owner} · ${src.name} ↗</a>`)}

function ensureAtelier(){if(atelier)return true;try{const draft=sanitizeWork(store.get('draft'))||recipe(0);atelier=new Atelier(draft,w=>{store.save('draft',structuredClone(w))},saveWork,txt=>showNote('造物间手记',txt));atelier.stage.onBell=()=>audio.play('bell');atelier.onNew=()=>currentWorkKey=null;return true}catch(e){toast('这台设备暂时无法开启三维工作台。故事中的文字操作仍然可用。');return false}}
function openAtelier(work,preserve=false){$('game').hidden=true;$('atelier-screen').hidden=false;if(!ensureAtelier()){$('atelier-screen').hidden=true;$('game').hidden=false;return}if(work){if(!preserve){work.era=s.era;work.nodes.forEach(n=>n.color=s.color)}atelier.setWork(work);currentWorkKey=null}atelier.stage.resize();view='atelier';suspend()}
function saveWork(work){showDrawer(`<p class="eyebrow">把这一件，留给未来的自己</p><h2>收入作品馆</h2><form id="save-work-form"><label>作品名<input name="name" maxlength="24" required value="${esc(work.name)}"></label><label>造物者<input name="author" maxlength="20" required value="${esc(work.author)}"></label><label><input name="featured" type="checkbox" ${work.featured?'checked':''}> 陈列在地宫（共六席）</label><button class="primary" type="submit">${currentWorkKey?'保存这次修改':'命名 · 收藏'}</button><p id="save-form-status" role="status"></p></form>`);$('save-work-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),w=structuredClone(work);w.name=String(data.get('name')).trim();w.author=String(data.get('author')).trim();if(!w.name||!w.author)return;w.featured=data.has('featured');const featured=store.all().filter(r=>r.key.startsWith('work-')&&r.value.featured&&r.key!==currentWorkKey);if(w.featured&&featured.length>=6){$('save-form-status').textContent='六个展位已满，先在作品馆撤下一件，或取消陈列。';return}w.updated=Date.now();const key=currentWorkKey||'work-'+uid();form.querySelector('button').disabled=true;$('save-form-status').textContent='正在收存…';const ok=await store.save(key,w);currentWorkKey=key;atelier.work=w;atelier.render();store.save('draft',w);updateExhibits();$('save-form-status').textContent=ok?'已收入云端作品馆。':'作品已留在设备草稿中，连接恢复后可在设置中重试同步。';form.querySelector('button').disabled=false;if(ok){$('drawer').close();openGallery()}}}
function workRows(){return store.all().filter(r=>r.key.startsWith('work-')).map(r=>({...r,value:sanitizeWork(r.value)})).filter(r=>r.value).sort((a,b)=>b.value.updated-a.value.updated)}
function openGallery(){if(!ensureAtelier())return;$('gallery-modal').showModal();page=0;renderGallery();suspend()}
function renderGallery(){const all=workRows(),featured=all.filter(r=>r.value.featured).slice(0,6);$('featured-works').innerHTML=Array.from({length:6},(_,i)=>`<div class="exhibit-slot ${featured[i]?'filled':''}"><small>藏位 ${String(i+1).padStart(2,'0')}</small><strong>${featured[i]?esc(featured[i].value.name):'留给下一件造物'}</strong></div>`).join('');page=Math.min(page,Math.max(0,Math.ceil(all.length/6)-1));const rows=all.slice(page*6,page*6+6);$('works-grid').innerHTML=rows.length?rows.map(r=>`<article class="work-card"><img id="thumb-${r.key}" alt="${esc(r.value.name)}的三维实物留影"><div><p class="eyebrow">${ERAS[r.value.era].name}时代 · ${r.value.nodes.length} 件</p><h3>${esc(r.value.name)}</h3><p>${esc(r.value.author)} · ${store.pending[r.key]?'待同步':'云端收藏'}</p><div class="actions"><button data-work="${r.key}" data-task="edit">继续制作</button><button data-work="${r.key}" data-task="poster">海报</button><button data-work="${r.key}" data-task="copy">复制</button><button data-work="${r.key}" data-task="feature">${r.value.featured?'撤下陈列':'陈列'}</button><button data-work="${r.key}" data-task="export">备份</button><button data-work="${r.key}" data-task="delete">移出作品馆</button></div></div></article>`).join(''):'<div class="empty-gallery"><h3>第一件藏品，正在等你。</h3><p>在百工造物间放上部件，为作品命名，即可留在这里。</p><button id="empty-toy" class="primary">走进造物间</button></div>';if(all.length>6)$('works-grid').insertAdjacentHTML('beforeend',`<div class="gallery-pages"><button id="gallery-prev" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${Math.ceil(all.length/6)}</span><button id="gallery-next" ${(page+1)*6>=all.length?'disabled':''}>下一页</button></div>`);rows.forEach(r=>{try{$('thumb-'+r.key).src=atelier.stage.capture(r.value,{width:640,height:480}).toDataURL('image/webp',.85)}catch{$('thumb-'+r.key).alt='三维留影暂不可用；作品结构已保留'}});$('empty-toy')&&($('empty-toy').onclick=()=>{$('gallery-modal').close();openAtelier()});$('gallery-prev')&&($('gallery-prev').onclick=()=>{page--;renderGallery()});$('gallery-next')&&($('gallery-next').onclick=()=>{page++;renderGallery()});$('gallery-message').textContent=`${all.length} 件作品 · 收藏结构可继续编辑，海报可独立保存。`}
async function workAction(key,task){const w=sanitizeWork(store.get(key));if(!w)return;if(task==='edit'){$('gallery-modal').close();openAtelier(w,true);currentWorkKey=key;return}if(task==='export'){downloadFile({format:'digong-zaowu-work-v3',work:w},'地宫造物-'+w.name+'.digong.json');return}if(task==='poster'){showDrawer(`<p class="eyebrow">成器留影 · 可下载的收藏海报</p><h2>${esc(w.name)}</h2><div class="actions"><button id="poster-whole">成器全貌</button><button id="poster-explode">拆解图录</button></div><img id="poster-preview" alt="收藏海报预览"><p id="poster-status" role="status">正在印制…</p><button id="poster-download" class="primary" disabled>下载海报</button>`);const generate=async exploded=>{$('poster-download').disabled=true;$('poster-status').textContent='正在印制…';try{const blob=await makePoster(atelier.stage,w,exploded);if(posterUrl)URL.revokeObjectURL(posterUrl);posterUrl=URL.createObjectURL(blob);$('poster-preview').src=posterUrl;$('poster-status').textContent='1600 × 2200 · 由当前三维作品生成';$('poster-download').disabled=false;$('poster-download').onclick=()=>downloadFile(blob,'地宫造物-'+w.name+(exploded?' · 拆解':' · 成器')+'.png','image/png')}catch{$('poster-status').textContent='印制未完成，请再试一次。'}};$('poster-whole').onclick=()=>generate(false);$('poster-explode').onclick=()=>generate(true);await generate(false);return}if(task==='delete'){showDrawer(`<h2>移出“${esc(w.name)}”？</h2><p>这会移除云端作品馆中的这一件。你可以先导出备份。</p><div class="actions"><button id="delete-backup">先导出备份</button><button id="delete-confirm">移出作品馆</button></div><p id="delete-status"></p>`);$('delete-backup').onclick=()=>downloadFile({format:'digong-zaowu-work-v3',work:w},w.name+'.digong.json');$('delete-confirm').onclick=async()=>{try{if(await store.remove(key)){$('drawer').close();renderGallery();updateExhibits();if(currentWorkKey===key)currentWorkKey=null}else $('delete-status').textContent='当前还有未同步的修改，或云端记录已改变。请先在设置里完成同步。'}catch{$('delete-status').textContent='连接未成功，作品仍然保留。'}};return}if(task==='copy'){await store.save('work-'+uid(),duplicateWork(w))}if(task==='feature'){if(!w.featured&&workRows().filter(r=>r.value.featured).length>=6){$('gallery-message').textContent='六个展位已满，请先撤下一件。';return}w.featured=!w.featured;w.updated=Date.now();await store.save(key,w)}renderGallery();updateExhibits()}
function settings(){showDrawer(`<p class="eyebrow">随手整理，随时继续</p><h2>设置与档案</h2><label><input id="motion-pref" type="checkbox" ${prefs.motion!==false?'checked':''}> 完整开场镜头</label><label><input id="quality-pref" type="checkbox" ${prefs.simple?'checked':''}> 轻量画面（减少阴影）</label><p>${esc($('sync-state').textContent)}</p><div class="actions"><button id="sync-retry">重试同步</button><button id="export-all">导出全部档案</button><button id="import-all">导入档案备份</button></div><details><summary>出现同步冲突时</summary><p>先导出当前设备上的修改，再选择读取云端版本。两份修改不会互相覆盖。</p><button id="use-cloud">读取云端版本</button></details><div class="archive-links"><a href="palace-v2.html">旧版地宫与原存档 ↗</a><a href="workshop.html">保留的工匠小操作 ↗</a></div><p class="hint">免登录即可游玩。各时代进度和作品保存到独立云端档案，此浏览器保留访客身份。清除浏览器数据或换设备前，请导出备份；无痕模式或禁止存储时，离开前务必备份。未同步修改暂留在设备上。</p><button id="era-menu" class="secondary">返回时代选择</button>`);for(const [id,key]of [['motion-pref','motion'],['quality-pref','simple']])$(id).onchange=e=>{prefs[key]=e.target.checked;try{localStorage.setItem('tiangong-v3-prefs',JSON.stringify(prefs))}catch{}world?.setQuality(!!prefs.simple)};$('sync-retry').onclick=async()=>{const ok=await store.retry();toast(ok?'档案已经同步。':'草稿仍然保留，请查看同步状态。');settings()};$('export-all').onclick=()=>downloadFile({format:'digong-zaowu-archive-v3',records:store.all(),legacy:readLocal('tiangong-palace-v2'),legacyWorkshop:readLocal('tiangong-workshop-v1')},'地宫造物-全部档案.json');$('import-all').onclick=()=>importFile(true);$('use-cloud').onclick=()=>{showDrawer('<h2>读取云端中的记录？</h2><p>当前设备未同步的修改会被放下。请先使用“导出全部档案”保存一份。</p><button id="cloud-confirm">已保留备份，读取云端版本</button>');$('cloud-confirm').onclick=async()=>{await store.useCloud();const next=sanitizeCampaign(store.get(`campaign-${s.era}`));if(next)s=next;render();settings()}};$('era-menu').onclick=()=>{$('drawer').close();showOpening()}}
function importFile(all=false){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>5_000_000){toast('这份文件太大，请选择地宫导出的档案。');return}try{const data=JSON.parse(await f.text());if(['digong-zaowu-work-v3','tiangong-work-v3'].includes(data.format)){const w=sanitizeWork(data.work);if(!w)throw Error();await store.save('work-'+uid(),duplicateWork(w));if($('gallery-modal').open)renderGallery();toast('作品已导入，原有藏品保留。')}else if(all&&['digong-zaowu-archive-v3','tiangong-archive-v3'].includes(data.format)&&Array.isArray(data.records)&&data.records.length<=260){let count=0;for(const r of data.records){if(r.key?.startsWith('work-')||r.key==='draft'){const w=sanitizeWork(r.value);if(w){await store.save('work-'+uid(),duplicateWork(w));count++}}else if(/^campaign-[0-3]$/.test(r.key)){const c=sanitizeCampaign(r.value);if(c&&!store.get(r.key)){await store.save(r.key,c);count++}}}toast(`已导入 ${count} 份记录。已有时代进度保留，作品作为副本收藏。`)}else throw Error()}catch{toast('未能读取这份档案，请使用地宫导出的 JSON 文件。')}};input.click()}
$('eras').onclick=e=>{const b=e.target.closest('[data-era]');if(b){selectedEra=Number(b.dataset.era);posterChosen=selectedEra;eras();showSeal()}};$('enter').onclick=showSeal;$('resume').onclick=()=>enter(true);$('skip').onclick=()=>{if(world)world.skipDescent();else{ $('descent').hidden=true;$('opening-art').hidden=true;$('world').hidden=true;$('game').hidden=false;s.entered=true;save();showView('story')}};$('home').onclick=showOpening;$('chapter-start').onclick=startChapter;$('chapter-track').onclick=e=>{const b=e.target.closest('[data-chapter]');if(!b)return;const i=Number(b.dataset.chapter);if(i===s.chapter)startChapter();else if(i<s.chapter)showNote(CHAPTERS[i].title,s.results[CHAPTERS[i].id]?.note||CHAPTERS[i].lesson)};$('event-open').onclick=showHistory;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('network').onclick=e=>{const b=e.target.closest('[data-node]');if(!b)return;const c=CHAPTERS.find(c=>c.unlocks.includes(b.dataset.node)),n=NODES.find(n=>n.id===b.dataset.node);showNote(n.name,s.known.includes(n.id)?s.results[c.id]?.note||c.lesson:`在“${c.title}”中，通过${c.verb}留下这份经验。`) };$('orbit').onclick=()=>atlas?.fit();$('lab-close').onclick=closeLab;$('lab-modal').addEventListener('cancel',e=>{e.preventDefault();closeLab()});$('drawer-close').onclick=()=>$('drawer').close();$('drawer').addEventListener('close',()=>{suspend();if(posterUrl){URL.revokeObjectURL(posterUrl);posterUrl=null}});$('gallery-close').onclick=()=>$('gallery-modal').close();$('gallery-modal').addEventListener('close',()=>{if(atelier)atelier.stage.setWork(atelier.work);suspend()});$('works-grid').onclick=e=>{const b=e.target.closest('[data-work]');if(b)workAction(b.dataset.work,b.dataset.task).catch(()=>toast('操作未完成，作品仍然保留。'))};$('open-gallery').onclick=openGallery;$('import-work').onclick=()=>importFile();$('atelier-back').onclick=()=>{$('atelier-screen').hidden=true;$('game').hidden=false;render();showView('story')};$('settings').onclick=settings;$('sources').onclick=()=>showDrawer(`<p class="eyebrow">知道从何而来，也知道止于何处</p><h2>史实 · 科学 · 架空</h2><p>御座画面为艺术想象，地宫造物、工匠人物与巡天器为架空故事。四条路线只采用所标明年代内的历史背景。</p>${Object.values(SOURCES).map(src=>`<article class="source-card"><a href="${src.url}" target="_blank" rel="noopener noreferrer">${src.owner} · ${src.name} ↗</a><p>${src.note}</p></article>`).join('')}`);
window.addEventListener('beforeunload',e=>{if(Object.keys(store.pending).length){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>store.retry());
const ready=store.init().then(()=>{const recent=store.all().filter(r=>/^campaign-[0-3]$/.test(r.key)).map(r=>sanitizeCampaign(r.value)).filter(Boolean);if(recent[0]){s=recent[0];selectedEra=s.era}eras()});eras();

$('poster-enter').onclick=openCharacters;
$('explode-slider').oninput=e=>{$('explode-value').textContent=e.target.value+'%';atlas?.explode(Number(e.target.value)/100)};
$('atlas-spread').onclick=()=>{atlas?.setFilter(-1);renderParts();$('explode-slider').value=100;$('explode-value').textContent='100%';atlas?.explode(1)};
$('atlas-reset').onclick=()=>{$('explode-slider').value=0;$('explode-value').textContent='0%';atlas?.setFilter(-1);atlas?.explode(0);renderParts()};
$('part-filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){atlas?.setFilter(Number(b.dataset.filter));renderParts()}};
$('part-list').onclick=e=>{const b=e.target.closest('[data-part]');if(b){if(atlas)atlas.select(Number(b.dataset.part));else{const i=Number(b.dataset.part);$('part-selection').textContent=PART_GROUPS[Math.floor(i/24)]+' '+(i%24+1)+' · '+(Math.floor(i/24)<s.chapter?'已点亮':'尚未点亮')}}};
$('part-isolate').onclick=()=>atlas?.isolate();

function resetHome(){showDrawer(`<p class="eyebrow">重新翻开一卷</p><h2>选择人物，从头体验</h2><p>仅重置所选人物的故事进度。作品馆、自由工作台和其他人物的进度都会保留。</p><div class="actions">${ERAS.map((e,i)=>`<button data-restart="${i}">${e.name}</button>`).join('')}</div>`);$('drawer-body').querySelectorAll('[data-restart]').forEach(b=>b.onclick=()=>confirmRestart(Number(b.dataset.restart)))}
function confirmRestart(era){showDrawer(`<h2>重新开始${ERAS[era].name}的故事？</h2><p>这一人物的八段发现将从第一段开始，收藏作品仍然保留。</p><div class="actions"><button id="restart-back">返回选择</button><button id="restart-confirm" class="primary">确认重置 · 进入龙椅开场</button></div><p id="restart-status" role="status"></p>`);$('restart-back').onclick=resetHome;$('restart-confirm').onclick=async()=>{const button=$('restart-confirm');button.disabled=true;await ready;const next=freshCampaign(era);const ok=await store.save(`campaign-${era}`,next);selectedEra=era;$('drawer').close();await enter(false);toast(ok?'已重新开始；收藏作品已保留。':'已从设备草稿重新开始，恢复连接后请同步进度。')}}
$('home-reset').onclick=resetHome;$('selection-reset').onclick=resetHome;
function audioLabel(){$('audio-toggle').textContent=audio.muted?'声音：关':'声音：开';$('audio-toggle').setAttribute?.('aria-pressed',String(!audio.muted))}
$('audio-toggle').onclick=()=>{audio.setMuted(!audio.muted);audio.unlock();audioLabel()};audioLabel();
window.addEventListener('visibilitychange',()=>audio.pause(document.hidden));
window.addEventListener('pagehide',()=>audio.pause(true));
window.addEventListener('pageshow',()=>audio.pause(false));

function showSeal(){posterChosen=selectedEra;eras();audio.unlock();sealStarted=false;$('seal-person').textContent=ERAS[selectedEra].name+' · '+PERSON_NAMES[selectedEra];$('seal-ritual').showModal();$('imperial-seal').disabled=false;cancelSeal();}
function cancelSeal(){clearTimeout(sealTimer);$('imperial-seal').classList.remove('pressed');$('seal-progress').style.width='0%';}
async function finishSeal(){if(sealStarted||!$('seal-ritual').open)return;sealStarted=true;cancelSeal();$('imperial-seal').disabled=true;audio.play('join');$('seal-ritual').close();await enter(false);}
$('imperial-seal').addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;e.preventDefault();if(sealStarted)return;cancelSeal();$('imperial-seal').classList.add('pressed');$('seal-progress').style.width='100%';sealTimer=setTimeout(finishSeal,650)});
for(const type of ['pointerup','pointercancel','pointerleave','lostpointercapture'])$('imperial-seal').addEventListener(type,cancelSeal);
$('imperial-seal').addEventListener('keydown',e=>{if((e.key==='Enter'||e.code==='Space')&&!e.repeat){e.preventDefault();finishSeal()}});
$('imperial-seal').onclick=e=>{if(e.detail===0)finishSeal()};
$('seal-back').onclick=()=>{$('seal-ritual').close();cancelSeal()};$('seal-ritual').addEventListener('cancel',cancelSeal);$('seal-ritual').addEventListener('close',cancelSeal);window.addEventListener('blur',cancelSeal);

function completeReset(){showDrawer(`<p class="eyebrow">清空这一份游戏档案</p><h2>完全重置？</h2><p>将清除当前档案中四个人物的全部进度、所有收藏作品与展位、自由工作台草稿，以及本浏览器的旧版游戏进度和声音、画面设置。其他玩家的档案不会受影响。</p><p>此操作不可撤销。可以先下载备份，再从首页重新开始。</p><div class="actions"><button id="reset-export">先下载全部备份</button><button id="reset-cancel">保留档案</button></div><label><input type="checkbox" id="reset-understood"> 我确认清除上述全部内容</label><button id="reset-everything" class="danger" disabled>完全清空并返回首页</button><p id="reset-all-status" role="status"></p>`);$('reset-export').onclick=()=>downloadFile({format:'digong-zaowu-archive-v3',records:store.all(),legacy:readLocal('tiangong-palace-v2'),legacyWorkshop:readLocal('tiangong-workshop-v1')},'地宫造物-重置前备份.json');$('reset-cancel').onclick=()=>$('drawer').close();$('reset-understood').onchange=e=>$('reset-everything').disabled=!e.target.checked;$('reset-everything').onclick=async()=>{if(!$('reset-understood').checked)return;const button=$('reset-everything');button.disabled=true;$('reset-all-status').textContent='正在清空当前档案…';await ready;const ok=await store.resetAll();if(!ok){$('reset-all-status').textContent='尚未完成重置，设备档案仍保留。请恢复连接或核对登录身份后再试。';button.disabled=false;return}try{for(const key of ['tiangong-v3-pending','tiangong-v3-prefs','tiangong-palace-v2','tiangong-palace-preferences','tiangong-workshop-v1','digong-audio-muted'])localStorage.removeItem(key)}catch{}window.location.reload()}}
$('complete-reset').onclick=completeReset;$('selection-complete-reset').onclick=completeReset;

function showAllEndings(){endingBrowse=true;audio.unlock();audio.scene='ending';showDrawer(`<p class="eyebrow">四种命运 · 结局图录</p><h2>查看全部结局</h2><p>无需通关，选择人物即可阅读完整结局与表情。阅读不会改变你的游戏进度。</p><div class="all-ending-cards">${ERAS.map((era,i)=>`<button data-ending-open="${i}">${chibi(i,3)}<span><strong>${era.name}</strong><small>${ENDINGS[i].title}</small></span></button>`).join('')}</div>`);$('drawer-body').querySelectorAll('[data-ending-open]').forEach(b=>b.onclick=()=>{endingEra=Number(b.dataset.endingOpen);endingStep=0;renderEnding()})}
$('home-endings').onclick=showAllEndings;$('selection-endings').onclick=showAllEndings;
