import * as T from './vendor/three/three.module.js?v=dbeb0ef5889a';
import {WorkStage} from './work-stage.mjs?v=dbeb0ef5889a';
import {makePart} from './atelier-models.mjs?v=dbeb0ef5889a';
import {box,cylinder,ring,materials} from './palace-models.mjs?v=dbeb0ef5889a';
import {newTrial,trialAction,SAMPLE_DATA} from './lab-rules.mjs?v=dbeb0ef5889a';
import {trialGuide} from './trial-guide.mjs?v=dbeb0ef5889a';
import {chibi} from './story-revision.mjs?v=dbeb0ef5889a';
const $=id=>document.getElementById(id),names={gate:'开门',lift:'升台',bell:'响铃'};
export class ChronicleLab{
 constructor(chapter,onDone){this.chapter=chapter;this.onDone=onDone;this.state=newTrial(chapter.id,chapter.level);$('lab-guide').open=true;this.abort=new AbortController();this.dialog=$('lab-modal');$('lab-title').textContent=chapter.title;$('lab-kicker').textContent=chapter.verb+' · 留下一次亲手发现';$('lab-story').textContent=chapter.summary;$('lab-science').textContent=chapter.lesson;$('lab-feedback').textContent='';$('lab-done').disabled=true;this.dialog.showModal();try{this.stage=new WorkStage($('lab-canvas'));this.stage.controls.enableRotate=true;this.stage.onFrame=(dt,t)=>this.animate(dt,t)}catch{ $('lab-object-label').textContent='图形显示不可用，仍可使用右侧操作完成实验。' }this.render();this.visual();$('lab-guide').addEventListener('toggle',()=>this.guide(),{signal:this.abort.signal});$('lab-actions').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.act(b.dataset.action,b.dataset.value)},{signal:this.abort.signal});$('lab-actions').addEventListener('input',e=>{if(e.target.dataset.mark!==undefined)this.act('mark',[Number(e.target.dataset.mark),e.target.value],false);if(e.target.id==='mix-color')this.act('color',e.target.value,false)},{signal:this.abort.signal});$('lab-done').onclick=()=>{if(this.state.passed)this.onDone(this.state)};
 const canvas=$('lab-canvas');canvas.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY]},{signal:this.abort.signal});canvas.addEventListener('pointerup',e=>{if(chapter.id==='material'&&this.down&&Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])<8){const v=this.stage?.pick(e)?.userData.action;if(v)this.act(v[0],v[1])}},{signal:this.abort.signal});
 }
 act(a,v,rerender=true){if(this.busy)return;const result=trialAction(this.state,a,v);this.chapter.sound?.(this.state.passed?'success':this.state.id==='mix'?'mix':a==='mark'?'tick':'join');if(a==='step'&&result.ok){this.busy=true;this.motionUntil=performance.now()+650;this.timer=setTimeout(()=>{this.busy=false;this.render();$('lab-done').disabled=!this.state.passed},this.state.id==='sequence'&&this.state.passed?4200:650);}if(a==='mark'){const out=$('lab-actions').querySelector('[data-offset="'+v[0]+'"]');if(out)out.textContent=this.state.marks[v[0]];}if(result.text)$('lab-feedback').textContent=result.text;$('lab-done').disabled=!this.state.passed||this.busy;if(rerender)this.render();this.guide();$('lab-reaction').innerHTML=chibi(this.chapter.era,this.state.passed?2:result.ok===false?7:3);this.visual();if(this.state.passed&&this.state.id==='sequence')this.playStart=performance.now();if(this.state.passed&&this.state.id==='drive')this.drive=true}
 button(a,v,text,disabled=false){return `<button data-action="${a}" data-value="${v}" ${disabled?'disabled':''}>${text}</button>`}
 render(){const s=this.state,b=(...a)=>this.button(...a);let html='';
 if(s.id==='measure')html='<p class="instruction">移动零刻度，与铜色基准线对齐。木片本身不动。</p>'+s.marks.map((v,i)=>`<label>尺 ${i+1}${this.chapter.level<2?` · 零点偏移 <output data-offset="${i}">${v}</output>`:''}<input type="range" min="-4" max="4" step="1" value="${v}" data-mark="${i}" aria-label="尺 ${i+1} 的零点偏移"></label>`).join('')+b('test','','比较三份尺寸');
 if(s.id==='material')html='<p class="load-requirement">提篮要求：承载记录 <strong>至少 6</strong><br><small>先测试三份样品：红色表示不足，绿色表示符合要求，再选一份采用。</small></p>'+SAMPLE_DATA.map(d=>{const seen=s.seen.includes(d.id),fit=d.load>=6;return `<div class="sample-row ${seen?(fit?'load-pass':'load-fail'):''}"><strong>${d.name}</strong>${b('test',d.id,seen?'再看一次':'放上砝码')}${seen?`<div class="load-result"><b>${fit?'✓ 符合要求':'✕ 承载不足'}</b><span>承载 ${d.load} / 要求 6</span></div><small>相对重量 ${d.weight} · 同载弯曲 ${d.bend}</small>`:'<small>尚未测试</small>'}${b('choose',d.id,seen&&!fit?'承载不足':s.seen.length<3?'测完三份后采用':'采用这份',!seen||!fit||s.seen.length<3)}</div>`}).join('');
 if(!['measure','material'].includes(s.id)){const next=trialGuide(s);html=s.passed?'<p class="instruction">本批操作完成，等待光芒落定。</p>':`<p class="instruction">${next.text}</p><p class="hint">当前第 ${s.step+1} 步 · 跟随提示即可</p>`+b('step',next.value,this.busy?'正在完成…':next.label,this.busy);}
 $('lab-actions').innerHTML=html;$('lab-done').hidden=!s.passed;if(s.passed)$('lab-actions').querySelectorAll('button,input,select').forEach(e=>e.disabled=true);this.guide();$('lab-reaction').innerHTML=chibi(this.chapter.era,s.passed?2:3);
 }
 visual(){if(!this.stage)return;const s=this.state,g=new T.Group(),m=materials(),add=(type,x,y,z=0,action)=>{const p=makePart(type,m,s.colors);p.position.set(x,y,z);p.userData.action=action;g.add(p);return p};let label='';
 if(s.id==='measure'){for(let i=0;i<3;i++){const z=(i-1)*1.3;box(g,m.wood,3.6,.2,.65,.3,.2,z);const ruler=new T.Group();g.add(ruler);ruler.position.set(s.marks[i]*.22,.4,z+.5);box(ruler,m.paper,4,.045,.3,.4);for(let k=0;k<17;k++)box(ruler,k===0?m.amber:m.dark,.018,.025,k%4===0?.26:.12,-1.6+k*.24,.04);box(g,m.metal,.025,.04,1.12,-1.6,.46,z)}label='同一条基准，才有可比较的尺寸。'}
 if(s.id==='material'){SAMPLE_DATA.forEach((d,i)=>{const p=new T.Group();p.position.x=(i-1)*2.2;p.userData.action=['test',d.id];g.add(p);for(const x of [-.8,.8])box(p,m.stone,.3,.5,.7,x,.25);const sample=box(p,m.wood,2,.1+(i*.11),.55,0,.58);if(s.seen.includes(d.id)){sample.material=m.wood.clone();sample.material.color.set(d.load>=6?'#54bd84':'#e66f69');cylinder(p,m.metal,.25,.4,0,.87);sample.rotation.z=(d.bend-3)*.01}});label='测试后：红色承载不足 · 绿色符合要求 · 相对数值仅供本次比较'}
 if(s.id==='join'){const stage=s.step;const metal=m.metal.clone();metal.color.set('#bc9a60');for(let i=0;i<2;i++){const r=ring(g,metal,.95,.09,0,i*2+.3);r.rotation.x=Math.PI/2;r.visible=stage>=(i?4:1)}for(let i=0;i<2;i++){const mat=m.jade.clone();mat.side=T.DoubleSide;mat.transparent=true;mat.opacity=stage>=i+2?1:.18;const p=new T.Mesh(new T.CylinderGeometry(.93,.93,2,40,1,true,i*Math.PI,Math.PI),mat);p.position.set(stage>=i+2?0:(i?1:-1)*1.2,1.3,0);g.add(p)}label='弧壳拼合 · 外观展示模型'}
 if(s.id==='mix'){const step=s.step;cylinder(g,m.metal,1.15,.2,0,.1);const light=m.jade.clone();light.emissive=new T.Color('#39cbb2');light.emissiveIntensity=.7;this.core=new T.Group();g.add(this.core);for(let i=0;i<(step?24:0);i++){const angle=i*2.4,radius=step>=4?.35:.8;const p=new T.Mesh(new T.IcosahedronGeometry(step>=4?.12:.065,0),light);p.position.set(Math.cos(angle)*radius,.35+(step>=4?i*.035:Math.sin(i)*.06),Math.sin(angle)*radius);this.core.add(p)}if(step>=2){const halo=ring(g,m.amber,step>=4?.5:.95,.025,0,.4);halo.rotation.x=Math.PI/2}if(step>=5){const glass=new T.MeshPhysicalMaterial({color:'#bceadd',transparent:true,opacity:.2,roughness:.2,side:T.DoubleSide});const cover=new T.Mesh(new T.CylinderGeometry(.65,.65,1.5,32),glass);cover.position.y=.85;g.add(cover)}label='架空燃料芯 · 星砂与凝光无现实配方'}
 if(s.id==='drive'){this.rotors=[];const scales=s.purpose==='strong'?[.8,1,1.6]:[1.6,1,.8];for(let i=0;i<3;i++){const x=i===0?-(scales[0]+1)*.55:i===2?(scales[2]+1)*.55:0,p=add('gear',x,1.3);p.scale.setScalar(scales[i]);p.visible=s.connections.includes(['input','middle','output'][i]);this.rotors.push(p)}add('crank',-1.3,1.3,.5);label=s.purpose==='strong'?'小轮输入 · 大轮输出':'大轮输入 · 小轮输出'}
 if(s.id==='sequence'){add('deck',0,.2);for(const x of [-1.5,1.5])add('post',x,1.4);add('beam',0,2.55);this.gate=box(g,m.wood,2.55,1.8,.16,0,1.15,-.5);this.lift=add('basket',0,.8,.6);this.bell=add('bell',2.6,2);label='三段机关 · 带联锁的演示'}
 if(s.id==='diagnose'){for(let i=0;i<2;i++){const p=box(g,m.wood,s.observed&&i===1?2.2:2,.16,1.2,(i?1:-1)*1.6,.5);for(const x of [-1,1])box(g,m.metal,.035,.03,1.4,p.position.x+x,.62);if(s.observed&&i===1)ring(g,m.jade,.25,.02,1.6,1.2)}label=s.observed?'右侧：较湿环境 · 横向尺寸变化已作夸张示意':'一份对照样，一份实验样'}
 if(s.id==='assembly'){add('deck',0,.2);for(let i=0;i<3;i++){const id=['shell','ring','mark'][i],p=box(g,s.checked.includes(id)?m.jade:m.wood,1.2,.15,1.8,(i-1)*1.8,.45);p.userData.action=['inspect',id];if(i===1){const mark=ring(g,m.amber,.4,.035,0,.58,0);if(!s.aligned)mark.scale.x=.6}}label='总装图录检查 · 标记与视觉完整性'}

 this.stage.setGroup(g);this.stage.focus();$('lab-object-label').textContent=label;
 }
 guide(){const next=trialGuide(this.state);$('lab-guide-copy').textContent=next.text;const visible=$('lab-guide').open;$('lab-actions').querySelectorAll('[data-action]').forEach(b=>b.classList.toggle('next-action',visible&&b.dataset.action===next.action&&(next.value===undefined||b.dataset.value===next.value)));$('lab-actions').querySelectorAll('[data-mark]').forEach(b=>b.classList.toggle('next-action',visible&&Number(b.dataset.mark)===next.mark));$('lab-done').classList.toggle('next-action',this.state.passed)}
 animate(dt,t){if(this.core&&this.state.step>=3)this.core.rotation.y+=dt*(performance.now()<this.motionUntil?3:.25);if(this.spoon&&this.dragging){this.spoon.position.x=Math.cos(t*4)*.6;this.spoon.position.z=Math.sin(t*4)*.6}if(this.drive)this.rotors?.forEach((p,i)=>p.userData.rotor.rotation.z+=dt*(i%2?-1:1)*(i===2?(this.state.purpose==='strong'?.5:2):1));if(this.playStart){const p=(performance.now()-this.playStart)/1000,sequence=this.state.sequence;let opened=false,lifted=false;for(let i=0;i<Math.min(3,Math.floor(p));i++){if(sequence[i]==='gate'){opened=true;this.gate.position.x=-2.4}if(sequence[i]==='lift'&&opened){lifted=true;this.lift.position.y=1.7}if(sequence[i]==='bell'&&lifted)this.bell.rotation.z=Math.sin(t*15)*.15}if(p>4)this.playStart=null}}
 dispose(){clearTimeout(this.timer);this.abort.abort();this.stage?.dispose();this.dialog.close();$('lab-done').onclick=null}
}
