import {ERAS,CHAPTERS,NODES,PEOPLE,SOURCES,DECISIONS,freshCampaign,sanitizeCampaign,legacyCampaign,decide,completeChapter,hallState,dateLabel,eventFor} from './chronicle-data.mjs';
import {ERA_SCENES} from './era-stories.mjs';
import {ChronicleWorld} from './chronicle-world.mjs';
import {ChronicleLab} from './chronicle-lab.mjs';
import {ArchiveStore,readLocal} from './archive-store.mjs';
import {Atelier} from './atelier.mjs';
import {recipe,uid,sanitizeWork,duplicateWork} from './atelier-data.mjs';
import {downloadFile,makePoster} from './poster.mjs';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let s=freshCampaign(),selectedEra=0,world,lab,atelier,currentWorkKey=null,page=0,view='story',draftTimer,toastTimer,posterUrl;
const prefs=readLocal('tiangong-v3-prefs')||{};
const store=new ArchiveStore(text=>{$('sync-state').textContent=text;$('toy-save-status').textContent=text});
try{world=new ChronicleWorld($('world'),index=>{const c=CHAPTERS.find(c=>c.modules.includes(index));if(c&&s.completed.includes(c.id))showNote(c.title,s.results[c.id]?.note||c.lesson);else if(c?.id===CHAPTERS[s.chapter]?.id)startChapter()});world.configureNetwork(NODES);world.setQuality(!!prefs.simple)}catch(e){console.warn('三维场景初始化失败');$('graphics-note').hidden=false}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200)}
function suspend(){if(world)world.suspended=!!(lab||!$('atelier-screen').hidden||$('drawer').open||$('gallery-modal').open||!$('opening').hidden);if(atelier)atelier.stage.paused=$('atelier-screen').hidden||$('drawer').open||$('gallery-modal').open}
function showDrawer(html){$('drawer-body').innerHTML=html;if(!$('drawer').open)$('drawer').showModal();suspend()}
function showNote(title,text){showDrawer(`<p class="eyebrow">地宫札记</p><h2>${esc(title)}</h2><p>${esc(text)}</p>`)}
function save(){store.save(`campaign-${s.era}`,s);render()}
function eras(){ $('eras').innerHTML=ERAS.map((e,i)=>`<button class="era-option ${i===selectedEra?'active':''}" data-era="${i}" aria-pressed="${i===selectedEra}"><img src="assets/rulers/${e.image}.webp" alt="${e.name}艺术形象"><span><strong>${e.name}</strong><small>${e.theme}</small></span></button>`).join('');$('era-line').textContent=ERAS[selectedEra].line;$('era-place').textContent=(selectedEra===3?'帘后诏令':'御座之下')+' · 宫阙为艺术想象';const saved=sanitizeCampaign(store.get(`campaign-${selectedEra}`));$('resume').hidden=!saved?.entered;$('enter').hidden=!!saved?.entered;$('opening-art').dataset.era=selectedEra;world?.showThrone(selectedEra);suspend()}
function showOpening(){view='opening';$('game').hidden=true;$('atelier-screen').hidden=true;$('opening').hidden=false;$('opening-art').hidden=false;$('opening-art').style.cssText='';selectedEra=s.era;eras()}
function render(){const c=CHAPTERS[s.chapter],e=ERAS[s.era],ev=eventFor(s);$('era-year').textContent=e.name+' · '+dateLabel(e.years[Math.min(s.chapter,7)]);$('chapter-label').textContent=c?`造物卷 · ${String(s.chapter+1).padStart(2,'0')} / 08`:'一卷成器 · 百工留名';$('chapter-title').textContent=c?.title||'此器已成，故事未尽';$('chapter-summary').textContent=(c?ERA_SCENES[s.era][s.chapter]:null)||'再去自由工作台，把新想法做成自己的作品；也可以开启另一个时代，听一段不同的工坊故事。';$('chapter-start').textContent=c?'走近工作台 →':'走进百工造物间 →';$('event-open').textContent=ev.title+' ↗';$('chapter-track').innerHTML=CHAPTERS.map((c,i)=>`<button class="${i===s.chapter?'active':i<s.chapter?'done':''}" data-chapter="${i}" aria-label="${i<s.chapter?'回看发现':i===s.chapter?'当前章节':'尚未经历'}：${c.title}" ${i>s.chapter?'disabled':''}><b>${i<s.chapter?'✓':String(i+1).padStart(2,'0')}</b><span>${c.verb}</span></button>`).join('');const p=PEOPLE.find(p=>p.id===c?.person)||PEOPLE[5];$('companion').innerHTML=`<small>${p.job} · ${p.name}</small><h3>“${s.chapter===8?'还有想做的吗？':s.decisions[6]==='listen'&&p.id==='ce'?'先听他把话说完。':'先试一试。'}”</h3><p>${p.text}</p>`;$('progress-label').textContent=`${s.chapter} / 8 段经历 · ${s.known.length} / 17 项经验`;world?.applyState(hallState(s));if(world?.modules?.[2])world.modules[2].traverse(o=>{if(o.userData.panel){if(!o.userData.personalColor){o.material=o.material.clone();o.userData.personalColor=true}o.material.color.set(s.color)}});renderNetwork();renderTeam();updateExhibits()}
function renderNetwork(){let html='';for(let lane=0;lane<4;lane++){const nodes=NODES.filter(n=>n.branch===lane);html+=`<div class="network-lane"><b>${nodes[0].lane}</b>${nodes.map(n=>`<button class="tech-node ${s.known.includes(n.id)?'known':''}" data-node="${n.id}">${s.known.includes(n.id)?'✓ ':''}${n.name}</button>`).join('')}</div>`}html+=`<div class="network-end"><span>四条经验，在这里合流</span><button class="tech-node ${s.known.includes('final')?'known':''}" data-node="final">${s.known.includes('final')?'✓ ':''}巡天总成</button></div><p class="hint">经验来自章节中的发现。无需刷材料、反复点亮节点。</p>`;$('network').innerHTML=html}
function renderTeam(){$('people').innerHTML=PEOPLE.map(p=>`<article class="person"><div class="monogram">${p.name.slice(-1)}</div><h3>${p.name} <small>${p.job}</small></h3><p>${p.skill}</p><p>${p.text}</p></article>`).join('');$('team-record').innerHTML='<h3>工坊记事</h3>'+(s.record.length?s.record.slice(-8).map(r=>`<p><small>第 ${r.chapter+1} 段</small>　${esc(r.text)}</p>`).join(''):'<p>一起完成第一件事，这里便有了记录。</p>')}
function updateExhibits(){const works=store.all().filter(r=>r.key.startsWith('work-')&&r.value.featured).map(r=>sanitizeWork(r.value)).filter(Boolean);const signature=JSON.stringify(works.map(w=>[w.updated,w.name]));if(world&&world.exhibitSignature!==signature){world.exhibitSignature=signature;world.exhibitWorks(works)}}
function showView(next){view=next;if(next==='atelier'){openAtelier();return}if(next==='gallery'){openGallery();return}$('network-panel').hidden=next!=='network';$('team-panel').hidden=next!=='team';$('story-panel').hidden=next!=='story';$('companion').hidden=next!=='story';$('chapter-track').hidden=next!=='story';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===next));world?.setMode(next==='network'?'tech':'overview');suspend()}
async function enter(resume=false){await ready;s=sanitizeCampaign(store.get(`campaign-${selectedEra}`))||(selectedEra===0?legacyCampaign(readLocal('tiangong-palace-v2')):freshCampaign(selectedEra));s.era=selectedEra;if(resume&&s.entered){$('opening').hidden=true;$('opening-art').hidden=true;$('game').hidden=false;render();showView('story');return}$('opening').hidden=true;$('descent').hidden=false;world&&(world.suspended=false);const lines=['殿上是诏令，殿下是双手。','视线越过御座，落向殿基。','穿过地基，听见百工。','灯火渐起，万象未形。','把这一卷未来，交给这个时代。'];const done=()=>{s.entered=true;$('opening-art').hidden=true;$('descent').hidden=true;$('game').hidden=false;save();showView('story')};if(world)world.descend(i=>$('descent-copy').textContent=lines[i],done,prefs.motion===false||matchMedia('(prefers-reduced-motion: reduce)').matches,p=>{const q=Math.min(1,p/.48);$('opening-art').style.transform=`scale(${1+q*.24}) translateY(${-q*38}%)`;$('opening-art').style.opacity=String(Math.max(0,1-Math.max(0,q-.45)/.55))});else{const anim=$('opening-art').animate([{opacity:1,transform:'scale(1)'},{opacity:0,transform:'scale(1.2) translateY(-30%)'}],{duration:1000,fill:'forwards'});anim.onfinish=done}}
function startChapter(){if(s.chapter>=8){openAtelier();return}const d=DECISIONS[s.chapter];if(d&&!s.decisions[s.chapter]){showDrawer(`<p class="eyebrow">人和手艺 · 一次决定</p><h2>${d.title}</h2><p>${d.text}</p>${d.options.map(o=>`<button class="choice" data-decision="${o.id}">${o.label}</button>`).join('')}`);document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{if(decide(s,s.chapter,b.dataset.decision)){store.save(`campaign-${s.era}`,s);$('drawer').close();openLab()}});return}openLab()}
function openLab(){if(lab)return;const chapter={...CHAPTERS[s.chapter],summary:ERA_SCENES[s.era][s.chapter]+' '+CHAPTERS[s.chapter].summary,mentored:s.decisions[2]==='mentor',apprentice:s.decisions[7]==='apprentice'};lab=new ChronicleLab(chapter,result=>{if(!completeChapter(s,result))return;closeLab();save();toast('发现已留在工艺图中，工匠会复用这份经验。');if(s.chapter===8){world?.finale(()=>ending());if(!world)ending()}else{chapter.modules.forEach(id=>world?.reveal(id));showDrawer(`<p class="eyebrow">这一段，留下了什么</p><h2>${chapter.title}</h2><p>${esc(result.note)}</p><p>${esc(eventFor(s).text)}</p><div class="actions"><button class="primary" id="next-story">继续故事 →</button><button id="reward-toy">去玩新机关</button></div>`);$('next-story').onclick=()=>$('drawer').close();$('reward-toy').onclick=()=>{$('drawer').close();openAtelier(recipe(chapter.toy))}}});suspend()}
function closeLab(){lab?.dispose();lab=null;suspend()}
function ending(){showDrawer(`<p class="eyebrow">一卷成器 · ${ERAS[s.era].name}时代</p><h2>抬头时，百工已在身旁。</h2><p>巡天器离开了展台。让它来到此处的，还有 ${PEOPLE.map(p=>p.name).join('、')}留下的试样与记录。</p><p class="hint">终局是架空的艺术演出。所学基础工艺不能直接实现现代导弹，机关也不包含现实推进、制导或武器构造。</p><div class="actions"><button id="ending-toy" class="primary">做一件自己的作品</button><button id="ending-era">换一个时代</button></div>`);$('ending-toy').onclick=()=>{$('drawer').close();openAtelier(recipe(6))};$('ending-era').onclick=()=>{$('drawer').close();showOpening()}}
function ensureAtelier(){if(atelier)return true;try{const draft=sanitizeWork(store.get('draft'))||recipe(0);atelier=new Atelier(draft,w=>{store.save('draft',structuredClone(w))},saveWork,txt=>showNote('造物间手记',txt));atelier.onNew=()=>currentWorkKey=null;return true}catch(e){toast('这台设备暂时无法开启三维工作台。故事中的文字操作仍然可用。');return false}}
function openAtelier(work,preserve=false){$('game').hidden=true;$('atelier-screen').hidden=false;if(!ensureAtelier()){$('atelier-screen').hidden=true;$('game').hidden=false;return}if(work){if(!preserve){work.era=s.era;work.nodes.forEach(n=>n.color=s.color)}atelier.setWork(work);currentWorkKey=null}atelier.stage.resize();view='atelier';suspend()}
function saveWork(work){showDrawer(`<p class="eyebrow">把这一件，留给未来的自己</p><h2>收入作品馆</h2><form id="save-work-form"><label>作品名<input name="name" maxlength="24" required value="${esc(work.name)}"></label><label>造物者<input name="author" maxlength="20" required value="${esc(work.author)}"></label><label><input name="featured" type="checkbox" ${work.featured?'checked':''}> 陈列在地宫（共六席）</label><button class="primary" type="submit">${currentWorkKey?'保存这次修改':'命名 · 收藏'}</button><p id="save-form-status" role="status"></p></form>`);$('save-work-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),w=structuredClone(work);w.name=String(data.get('name')).trim();w.author=String(data.get('author')).trim();if(!w.name||!w.author)return;w.featured=data.has('featured');const featured=store.all().filter(r=>r.key.startsWith('work-')&&r.value.featured&&r.key!==currentWorkKey);if(w.featured&&featured.length>=6){$('save-form-status').textContent='六个展位已满，先在作品馆撤下一件，或取消陈列。';return}w.updated=Date.now();const key=currentWorkKey||'work-'+uid();form.querySelector('button').disabled=true;$('save-form-status').textContent='正在收存…';const ok=await store.save(key,w);currentWorkKey=key;atelier.work=w;atelier.render();store.save('draft',w);updateExhibits();$('save-form-status').textContent=ok?'已收入云端作品馆。':'作品已留在设备草稿中，连接恢复后可在设置中重试同步。';form.querySelector('button').disabled=false;if(ok){$('drawer').close();openGallery()}}}
function workRows(){return store.all().filter(r=>r.key.startsWith('work-')).map(r=>({...r,value:sanitizeWork(r.value)})).filter(r=>r.value).sort((a,b)=>b.value.updated-a.value.updated)}
function openGallery(){if(!ensureAtelier())return;$('gallery-modal').showModal();page=0;renderGallery();suspend()}
function renderGallery(){const all=workRows(),featured=all.filter(r=>r.value.featured).slice(0,6);$('featured-works').innerHTML=Array.from({length:6},(_,i)=>`<div class="exhibit-slot ${featured[i]?'filled':''}"><small>藏位 ${String(i+1).padStart(2,'0')}</small><strong>${featured[i]?esc(featured[i].value.name):'留给下一件造物'}</strong></div>`).join('');page=Math.min(page,Math.max(0,Math.ceil(all.length/6)-1));const rows=all.slice(page*6,page*6+6);$('works-grid').innerHTML=rows.length?rows.map(r=>`<article class="work-card"><img id="thumb-${r.key}" alt="${esc(r.value.name)}的三维实物留影"><div><p class="eyebrow">${ERAS[r.value.era].name}时代 · ${r.value.nodes.length} 件</p><h3>${esc(r.value.name)}</h3><p>${esc(r.value.author)} · ${store.pending[r.key]?'待同步':'云端收藏'}</p><div class="actions"><button data-work="${r.key}" data-task="edit">继续制作</button><button data-work="${r.key}" data-task="poster">海报</button><button data-work="${r.key}" data-task="copy">复制</button><button data-work="${r.key}" data-task="feature">${r.value.featured?'撤下陈列':'陈列'}</button><button data-work="${r.key}" data-task="export">备份</button><button data-work="${r.key}" data-task="delete">移出作品馆</button></div></div></article>`).join(''):'<div class="empty-gallery"><h3>第一件藏品，正在等你。</h3><p>在百工造物间放上部件，为作品命名，即可留在这里。</p><button id="empty-toy" class="primary">走进造物间</button></div>';if(all.length>6)$('works-grid').insertAdjacentHTML('beforeend',`<div class="gallery-pages"><button id="gallery-prev" ${page===0?'disabled':''}>上一页</button><span>${page+1} / ${Math.ceil(all.length/6)}</span><button id="gallery-next" ${(page+1)*6>=all.length?'disabled':''}>下一页</button></div>`);rows.forEach(r=>{try{$('thumb-'+r.key).src=atelier.stage.capture(r.value,{width:640,height:480}).toDataURL('image/webp',.85)}catch{$('thumb-'+r.key).alt='三维留影暂不可用；作品结构已保留'}});$('empty-toy')&&($('empty-toy').onclick=()=>{$('gallery-modal').close();openAtelier()});$('gallery-prev')&&($('gallery-prev').onclick=()=>{page--;renderGallery()});$('gallery-next')&&($('gallery-next').onclick=()=>{page++;renderGallery()});$('gallery-message').textContent=`${all.length} 件作品 · 收藏结构可继续编辑，海报可独立保存。`}
async function workAction(key,task){const w=sanitizeWork(store.get(key));if(!w)return;if(task==='edit'){$('gallery-modal').close();openAtelier(w,true);currentWorkKey=key;return}if(task==='export'){downloadFile({format:'digong-zaowu-work-v3',work:w},'地宫造物-'+w.name+'.digong.json');return}if(task==='poster'){showDrawer(`<p class="eyebrow">成器留影 · 可下载的收藏海报</p><h2>${esc(w.name)}</h2><div class="actions"><button id="poster-whole">成器全貌</button><button id="poster-explode">拆解图录</button></div><img id="poster-preview" alt="收藏海报预览"><p id="poster-status" role="status">正在印制…</p><button id="poster-download" class="primary" disabled>下载海报</button>`);const generate=async exploded=>{$('poster-download').disabled=true;$('poster-status').textContent='正在印制…';try{const blob=await makePoster(atelier.stage,w,exploded);if(posterUrl)URL.revokeObjectURL(posterUrl);posterUrl=URL.createObjectURL(blob);$('poster-preview').src=posterUrl;$('poster-status').textContent='1600 × 2200 · 由当前三维作品生成';$('poster-download').disabled=false;$('poster-download').onclick=()=>downloadFile(blob,'地宫造物-'+w.name+(exploded?' · 拆解':' · 成器')+'.png','image/png')}catch{$('poster-status').textContent='印制未完成，请再试一次。'}};$('poster-whole').onclick=()=>generate(false);$('poster-explode').onclick=()=>generate(true);await generate(false);return}if(task==='delete'){showDrawer(`<h2>移出“${esc(w.name)}”？</h2><p>这会移除云端作品馆中的这一件。你可以先导出备份。</p><div class="actions"><button id="delete-backup">先导出备份</button><button id="delete-confirm">移出作品馆</button></div><p id="delete-status"></p>`);$('delete-backup').onclick=()=>downloadFile({format:'digong-zaowu-work-v3',work:w},w.name+'.digong.json');$('delete-confirm').onclick=async()=>{try{if(await store.remove(key)){$('drawer').close();renderGallery();updateExhibits();if(currentWorkKey===key)currentWorkKey=null}else $('delete-status').textContent='当前还有未同步的修改，或云端记录已改变。请先在设置里完成同步。'}catch{$('delete-status').textContent='连接未成功，作品仍然保留。'}};return}if(task==='copy'){await store.save('work-'+uid(),duplicateWork(w))}if(task==='feature'){if(!w.featured&&workRows().filter(r=>r.value.featured).length>=6){$('gallery-message').textContent='六个展位已满，请先撤下一件。';return}w.featured=!w.featured;w.updated=Date.now();await store.save(key,w)}renderGallery();updateExhibits()}
function settings(){showDrawer(`<p class="eyebrow">随手整理，随时继续</p><h2>设置与档案</h2><label><input id="motion-pref" type="checkbox" ${prefs.motion!==false?'checked':''}> 完整开场镜头</label><label><input id="quality-pref" type="checkbox" ${prefs.simple?'checked':''}> 轻量画面（减少阴影）</label><p>${esc($('sync-state').textContent)}</p><div class="actions"><button id="sync-retry">重试同步</button><button id="export-all">导出全部档案</button><button id="import-all">导入档案备份</button></div><details><summary>出现同步冲突时</summary><p>先导出当前设备上的修改，再选择读取云端版本。两份修改不会互相覆盖。</p><button id="use-cloud">读取云端版本</button></details><div class="archive-links"><a href="palace-v2.html">旧版地宫与原存档 ↗</a><a href="workshop.html">保留的工匠小操作 ↗</a></div><p class="hint">免登录即可游玩。各时代进度和作品保存到独立云端档案，此浏览器保留访客身份。清除浏览器数据或换设备前，请导出备份；无痕模式或禁止存储时，离开前务必备份。未同步修改暂留在设备上。</p><button id="era-menu" class="secondary">返回时代选择</button>`);for(const [id,key]of [['motion-pref','motion'],['quality-pref','simple']])$(id).onchange=e=>{prefs[key]=e.target.checked;try{localStorage.setItem('tiangong-v3-prefs',JSON.stringify(prefs))}catch{}world?.setQuality(!!prefs.simple)};$('sync-retry').onclick=async()=>{const ok=await store.retry();toast(ok?'档案已经同步。':'草稿仍然保留，请查看同步状态。');settings()};$('export-all').onclick=()=>downloadFile({format:'digong-zaowu-archive-v3',records:store.all(),legacy:readLocal('tiangong-palace-v2'),legacyWorkshop:readLocal('tiangong-workshop-v1')},'地宫造物-全部档案.json');$('import-all').onclick=()=>importFile(true);$('use-cloud').onclick=()=>{showDrawer('<h2>读取云端中的记录？</h2><p>当前设备未同步的修改会被放下。请先使用“导出全部档案”保存一份。</p><button id="cloud-confirm">已保留备份，读取云端版本</button>');$('cloud-confirm').onclick=async()=>{await store.useCloud();const next=sanitizeCampaign(store.get(`campaign-${s.era}`));if(next)s=next;render();settings()}};$('era-menu').onclick=()=>{$('drawer').close();showOpening()}}
function importFile(all=false){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>5_000_000){toast('这份文件太大，请选择地宫导出的档案。');return}try{const data=JSON.parse(await f.text());if(['digong-zaowu-work-v3','tiangong-work-v3'].includes(data.format)){const w=sanitizeWork(data.work);if(!w)throw Error();await store.save('work-'+uid(),duplicateWork(w));if($('gallery-modal').open)renderGallery();toast('作品已导入，原有藏品保留。')}else if(all&&['digong-zaowu-archive-v3','tiangong-archive-v3'].includes(data.format)&&Array.isArray(data.records)&&data.records.length<=260){let count=0;for(const r of data.records){if(r.key?.startsWith('work-')||r.key==='draft'){const w=sanitizeWork(r.value);if(w){await store.save('work-'+uid(),duplicateWork(w));count++}}else if(/^campaign-[0-3]$/.test(r.key)){const c=sanitizeCampaign(r.value);if(c&&!store.get(r.key)){await store.save(r.key,c);count++}}}toast(`已导入 ${count} 份记录。已有时代进度保留，作品作为副本收藏。`)}else throw Error()}catch{toast('未能读取这份档案，请使用地宫导出的 JSON 文件。')}};input.click()}
$('eras').onclick=e=>{const b=e.target.closest('[data-era]');if(b){selectedEra=Number(b.dataset.era);eras()}};$('enter').onclick=()=>enter();$('resume').onclick=()=>enter(true);$('skip').onclick=()=>world?.skipDescent();$('home').onclick=showOpening;$('chapter-start').onclick=startChapter;$('chapter-track').onclick=e=>{const b=e.target.closest('[data-chapter]');if(!b)return;const i=Number(b.dataset.chapter);if(i===s.chapter)startChapter();else if(i<s.chapter)showNote(CHAPTERS[i].title,s.results[CHAPTERS[i].id]?.note||CHAPTERS[i].lesson)};$('event-open').onclick=()=>{const ev=eventFor(s),src=SOURCES[ev.source];showDrawer(`<p class="eyebrow">${dateLabel(ERAS[s.era].years[Math.min(s.chapter,7)])} · ${ev.fiction?'架空工坊事件':'史事背景'}</p><h2>${ev.title}</h2><p>${ev.text}</p><a href="${src.url}" target="_blank" rel="noopener noreferrer">${src.owner} · ${src.name} ↗</a><p class="hint">${src.note}</p>`)};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('network').onclick=e=>{const b=e.target.closest('[data-node]');if(!b)return;const c=CHAPTERS.find(c=>c.unlocks.includes(b.dataset.node)),n=NODES.find(n=>n.id===b.dataset.node);showNote(n.name,s.known.includes(n.id)?s.results[c.id]?.note||c.lesson:`在“${c.title}”中，通过${c.verb}留下这份经验。`) };$('orbit').onclick=()=>{world?.setMode(world.mode==='assembly'?'overview':'assembly');$('orbit').textContent=world?.mode==='assembly'?'回到殿中全景':'总装近景 ↻'};$('lab-close').onclick=closeLab;$('lab-modal').addEventListener('cancel',e=>{e.preventDefault();closeLab()});$('drawer-close').onclick=()=>$('drawer').close();$('drawer').addEventListener('close',()=>{suspend();if(posterUrl){URL.revokeObjectURL(posterUrl);posterUrl=null}});$('gallery-close').onclick=()=>$('gallery-modal').close();$('gallery-modal').addEventListener('close',()=>{if(atelier)atelier.stage.setWork(atelier.work);suspend()});$('works-grid').onclick=e=>{const b=e.target.closest('[data-work]');if(b)workAction(b.dataset.work,b.dataset.task).catch(()=>toast('操作未完成，作品仍然保留。'))};$('open-gallery').onclick=openGallery;$('import-work').onclick=()=>importFile();$('atelier-back').onclick=()=>{$('atelier-screen').hidden=true;$('game').hidden=false;render();showView('story')};$('settings').onclick=settings;$('sources').onclick=()=>showDrawer(`<p class="eyebrow">知道从何而来，也知道止于何处</p><h2>史实 · 科学 · 架空</h2><p>御座画面为艺术想象，地宫造物、工匠人物与巡天器为架空故事。四条路线只采用所标明年代内的历史背景。</p>${Object.values(SOURCES).map(src=>`<article class="source-card"><a href="${src.url}" target="_blank" rel="noopener noreferrer">${src.owner} · ${src.name} ↗</a><p>${src.note}</p></article>`).join('')}`);
window.addEventListener('beforeunload',e=>{if(Object.keys(store.pending).length){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>store.retry());
const ready=store.init().then(()=>{const recent=store.all().filter(r=>/^campaign-[0-3]$/.test(r.key)).map(r=>sanitizeCampaign(r.value)).filter(Boolean);if(recent[0]){s=recent[0];selectedEra=s.era}eras()});eras();
