// Original pentatonic score, synthesized locally after a player gesture.
export class GameAudio{
 constructor(env=globalThis){this.env=env;this.scene='hall';this.index=0;this.voices=new Set();try{this.muted=env.localStorage?.getItem('digong-audio-muted')==='1'}catch{} }
 async unlock(){try{const Context=this.env.AudioContext||this.env.webkitAudioContext;if(!Context)return false;if(!this.ctx){this.ctx=new Context();this.master=this.ctx.createGain();this.master.gain.value=this.muted?0:.28;this.master.connect(this.ctx.destination)}await this.ctx.resume();this.schedule();return true}catch{return false}}
 setMuted(value){this.muted=!!value;if(this.master)this.master.gain.setTargetAtTime(value?0:.28,this.ctx.currentTime,.08);try{this.env.localStorage?.setItem('digong-audio-muted',value?'1':'0')}catch{} }
 tone(freq,time,duration,gain=.1,type='sine'){if(!this.ctx||this.muted)return;const osc=this.ctx.createOscillator(),amp=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,time);amp.gain.setValueAtTime(.0001,time);amp.gain.exponentialRampToValueAtTime(gain,time+.025);amp.gain.exponentialRampToValueAtTime(.0001,time+duration);osc.connect(amp);amp.connect(this.master);this.voices.add(osc);osc.onended=()=>{osc.disconnect();amp.disconnect();this.voices.delete(osc)};osc.start(time);osc.stop(time+duration+.04)}
 schedule(){if(this.timer||!this.ctx)return;const tick=()=>{if(this.ctx.state!=='running'||this.muted)return;const notes=[0,7,12,9,7,null,4,2,0,null,7,9,12,16,14,null,12,9,7,4,2,null,4,7,9,7,4,2,0,null,null,null];const n=notes[this.index%notes.length],t=this.ctx.currentTime+.03,base=this.scene==='ending'?220:174.61;if(n!==null){this.tone(base*2**(n/12),t,1.7,.13,'triangle');this.tone(base*2**(n/12)*2,t,1.1,.025)}if(this.index%8===0){this.tone(base/2,t,4,.14);this.tone(base*.75,t,3.8,.045)}this.index++};tick();this.timer=this.env.setInterval(tick,570)}
 play(kind='tick'){if(!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime+.01;const notes=kind==='success'?[523,659,784,1047]:kind==='mix'?[220,294,392]:kind==='join'?[180,360]:[660];notes.forEach((n,i)=>this.tone(n,t+i*.105,kind==='success'?.85:.3,.2,kind==='join'?'triangle':'sine'))}
 async pause(hidden){if(!this.ctx)return;try{if(hidden)await this.ctx.suspend();else await this.ctx.resume()}catch{}}
 dispose(){if(this.timer)this.env.clearInterval(this.timer);this.timer=null;for(const v of this.voices){try{v.stop()}catch{}}this.voices.clear();this.ctx?.close()}
}
