(function(root){'use strict';
const parts={body:{name:'榆木车身',kind:'body',desc:'小车的底座'},axle:{name:'木轮轴组',kind:'axle',desc:'两根轮轴分别连接前后两对车轮',craft:'hammer'},wheel:{name:'小木轮',kind:'wheel',desc:'打磨后转得更顺',craft:'sand',size:1},bigwheel:{name:'大木轮',kind:'wheel',desc:'换种大小，看看会怎样',craft:'sand',size:1.4},support:{name:'木支架',kind:'support',desc:'稳稳托住转轴'},waterwheel:{name:'提水轮',kind:'waterwheel',desc:'带着小水斗转起来',craft:'align'},crank:{name:'手摇柄',kind:'crank',desc:'把手的运动传给轮轴'},bucket:{name:'小水斗',kind:'bucket',desc:'跟着水轮把水提起来',craft:'wrap'},gear:{name:'木齿轮',kind:'gear',desc:'把旋转传给相邻零件',craft:'align'},cam:{name:'偏心轮',kind:'cam',desc:'把转圈变成一上一下'},striker:{name:'小木槌',kind:'striker',desc:'跟着偏心轮起落',craft:'hammer'},bell:{name:'黄铜铃',kind:'bell',desc:'敲一下，听一声清响'}};
// One assembly coordinate system per machine. Slot centers, painted pivots and
// animation paths share these anchors, including the two ends of each axle.
const geometry={
 car:{plane:[.92,.408,0,1],body:{x:490,y:245},near:[{x:368,y:292},{x:528,y:363}],depth:{x:80,y:-75}},
 water:{plane:[1,.265,0,1],hub:{x:455,y:293},handle:{x:560,y:258},radius:83,start:-2.3},
 bell:{plane:[1,.265,0,1],gear:{x:399,y:281},cam:{x:500,y:307.765},pivot:{x:467,y:255},bell:{x:642,y:291}}
};
function planePoint(origin,plane,x,y){return {x:origin.x+plane[0]*x+plane[2]*y,y:origin.y+plane[1]*x+plane[3]*y}}
function bucketPose(t=0){const g=geometry.water,a=g.start-t*.8;return planePoint(g.hub,g.plane,Math.cos(a)*g.radius,Math.sin(a)*g.radius)}
const projects={
car:{title:'会跑的小木车',short:'小木车',number:'壹',tag:'木作初习',prompt:'先从零件匣里拿一只木轮，亲手磨一磨。',slots:[{id:'body',kind:'body',name:'车身',...geometry.car.body},{id:'axle',kind:'axle',name:'轮轴组',x:448,y:327.5},{id:'left',kind:'wheel',name:'前轮组',...geometry.car.near[0]},{id:'right',kind:'wheel',name:'后轮组',...geometry.car.near[1]}],parts:['body','axle','wheel','bigwheel'],tech:['round','axle','roll'],success:'两只轮子一起转，小木车跑起来了。',note:'轮轴支撑车身，转动的轮子让小车向前。',next:'water'},
water:{title:'把水提起来',short:'提水装置',number:'贰',tag:'转动的力量',prompt:'先拼好支架，再让水轮和小水斗一起转起来。',slots:[{id:'support',kind:'support',name:'支架',x:515,y:320},{id:'waterwheel',kind:'waterwheel',name:'提水轮',...geometry.water.hub},{id:'crank',kind:'crank',name:'摇柄',...geometry.water.handle},{id:'bucket',kind:'bucket',name:'小水斗',...bucketPose(0)}],parts:['support','waterwheel','crank','bucket'],tech:['turn','lift','join'],success:'水沿着小水斗升起来，落进了竹槽。',note:'手摇提供动力，水斗随轮转动，把水带到高处。',next:'bell'},
bell:{title:'会自己敲的铃',short:'自动敲铃器',number:'叁',tag:'让动作接力',prompt:'拼好传动零件，再把木槌和铃放到一起。',slots:[{id:'support',kind:'support',name:'木架',x:505,y:325},{id:'gear',kind:'gear',name:'齿轮',...geometry.bell.gear},{id:'cam',kind:'cam',name:'偏心轮',...geometry.bell.cam},{id:'striker',kind:'striker',name:'木槌',...geometry.bell.pivot},{id:'bell',kind:'bell',name:'铜铃',...geometry.bell.bell}],parts:['support','gear','cam','striker','bell'],tech:['gear','cam','sound'],success:'转一圈，敲一下。你的第一台自动装置开始工作了。',note:'偏心轮的高低变化带动木槌起落，连续旋转变成反复敲击。',next:'free'},
free:{title:'想怎么拼，就怎么拼',short:'自由工作台',number:'∞',tag:'没有标准答案',prompt:'拿取零件放上桌。相邻零件会连接，再拉动把手看它们接力。',slots:[],parts:Object.keys(parts),tech:[]}};
const techs=[{id:'round',name:'圆与打磨',text:'把粗糙的木料变成能转动的轮子。',x:170,y:105},{id:'axle',name:'轮轴',text:'让轮子围绕稳定的轴心转动。',x:395,y:75},{id:'roll',name:'滚动',text:'让整件造物向前运动。',x:625,y:105},{id:'join',name:'结构连接',text:'让零件组合成稳固的整体。',x:170,y:250},{id:'turn',name:'旋转传递',text:'把手的动作带到装置上。',x:395,y:230},{id:'lift',name:'提水',text:'让转动的轮子把水带往高处。',x:625,y:250},{id:'gear',name:'齿轮传动',text:'相邻的齿轮互相带动。',x:170,y:395},{id:'cam',name:'动作转换',text:'让旋转变成反复起落。',x:395,y:385},{id:'sound',name:'自动敲击',text:'让装置替你重复敲铃。',x:625,y:395}];
function fresh(){return {version:1,project:'car',crafted:[],completed:[],tech:[],discoveries:[],assemblies:{car:{},water:{},bell:{}},free:[],muted:false};}
function sanitize(raw){const s=fresh();if(!raw||raw.version!==1)return s;const list=(v,valid)=>Array.isArray(v)?[...new Set(v.filter(x=>valid.includes(x)))]:[];s.crafted=list(raw.crafted,Object.keys(parts));s.completed=list(raw.completed,['car','water','bell']);s.tech=list(raw.tech,techs.map(t=>t.id));s.discoveries=list(raw.discoveries,['wobble','mixed']);s.project=projects[raw.project]&&(raw.project!=='free'||s.completed.length===3)?raw.project:'car';s.muted=raw.muted===true;for(const id of ['car','water','bell'])for(const slot of projects[id].slots){const p=raw.assemblies?.[id]?.[slot.id];if(parts[p]?.kind===slot.kind)s.assemblies[id][slot.id]=p;}if(Array.isArray(raw.free))s.free=raw.free.filter(p=>parts[p?.part]&&Number.isFinite(p.x)&&Number.isFinite(p.y)).slice(0,18).map((p,i)=>({id:i+1,part:p.part,x:Math.max(110,Math.min(840,p.x)),y:Math.max(150,Math.min(430,p.y))}));return s;}
function evaluate(id,assembly){const p=projects[id];const missing=p.slots.filter(s=>parts[assembly[s.id]]?.kind!==s.kind);if(missing.length)return {ok:false,missing:missing.map(s=>s.name),type:'missing',message:'还缺'+missing.map(s=>s.name).join('、')+'。补上后再拉一次把手。'};if(id==='car'&&parts[assembly.left].size!==parts[assembly.right].size)return {ok:true,type:'wobble',message:'一大一小，小车拐弯了！换成一样大，就能跑得更直。'};return {ok:true,type:'success',message:p.success};}
function network(items){const powered=new Set();if(!items.length)return powered;const first=items.find(p=>['crank','waterwheel'].includes(p.part))||items[0];powered.add(first.id);let changed=true;while(changed){changed=false;for(const a of items)if(powered.has(a.id))for(const b of items)if(!powered.has(b.id)&&Math.hypot(a.x-b.x,a.y-b.y)<=150){powered.add(b.id);changed=true;}}return powered;}
function unlock(state,id){const p=projects[id];if(!p||id==='free')return [];const newly=p.tech.filter(t=>!state.tech.includes(t));state.tech=[...new Set([...state.tech,...p.tech])];if(!state.completed.includes(id))state.completed.push(id);return newly;}
const api={parts,projects,techs,fresh,sanitize,evaluate,network,unlock,geometry,planePoint,bucketPose};root.Tiangong=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
