export const SAMPLE_DATA=[{id:'a',name:'薄木片',weight:2,bend:7,load:2},{id:'b',name:'层叠木片',weight:4,bend:3,load:7},{id:'c',name:'厚木块',weight:8,bend:1,load:9}];
export function newTrial(id,level=2){return {id,passed:false,note:'',value:'',marks:level===0?[0,-3,1]:[2,-3,1],seen:[],pieces:[],rotation:0,ingredients:[],stir:0,colors:'#4f8877',purpose:'strong',connections:[],sequence:level===0?['gate','bell','lift']:['bell','lift','gate'],observed:false,control:'',checked:[],aligned:false}}
export function trialAction(s,action,value){if(s.passed)return {ok:false,text:'本次发现已经记录。'};let ok=true,text='';
 if(s.id==='measure'){if(action==='mark')s.marks[value[0]]=Math.max(-4,Math.min(4,Number(value[1])||0));if(action==='test'){s.passed=s.marks.every(v=>v===0);text=s.passed?'三份零点都与基准线重合，现在可以比较长度。':'还没有对齐。先把每把尺的零刻度移到同一条基准线上。'}}
 if(s.id==='material'){if(action==='test'){if(!s.seen.includes(value))s.seen.push(value);const d=SAMPLE_DATA.find(d=>d.id===value);text=d?`${d.name}：相对重量 ${d.weight}，同载弯曲 ${d.bend}，本次承载记录 ${d.load}。`:''}if(action==='choose'){const d=SAMPLE_DATA.find(d=>d.id===value);s.passed=s.seen.length===3&&['b','c'].includes(value);s.value=value==='b'?'light':'strong';text=s.passed?`${d.name}满足本次承载要求。${value==='b'?'带走更轻的方案。':'接受重量，换取更高的承载余量。'}`:s.seen.length<3?'先把三份样品放到同一条件下比较。':'薄片的本次承载结果不足，换一份再试。'}}
 if(s.id==='join'){if(action==='rotate')s.rotation=(s.rotation+1)%4;if(action==='insert'){const deps={base:[],left:['base'],right:['base'],top:['left','right']};if(!deps[value]||s.pieces.includes(value))return {ok:false,text:'这一件已经就位。'};if(!deps[value].every(p=>s.pieces.includes(p))){ok=false;text:'它还没有支撑。看一看下方的榫口。'}else if(s.rotation!==0){ok=false;text:'长边方向还没有对上。旋转预览件，再试一次。'}else{s.pieces.push(value);s.passed=s.pieces.length===4;text=s.passed?'框架站稳了。左右立柱的装配顺序可以交换。':'榫口贴合，下一处结构有了支撑。';s.rotation=1}}}
 if(s.id==='mix'){if(action==='add'){if(s.ingredients.includes(value))return {ok:false,text:'这一份已经加入。'};const next=['water','pigment','binder'][s.ingredients.length];if(value!==next){ok=false;text='本次用预先分散的水性料：先润湿颜料、拌散，再合入胶液。不是所有涂料都用同一顺序。'}else if(value==='binder'&&s.stir<1){ok=false;text='还有颗粒团聚，先轻轻拌散，再合入胶液。'}else{s.ingredients.push(value);if(value==='binder')s.stir=1;text=value==='binder'?'胶液加入了，轻拌均匀后试涂。':'已加入。'}}if(action==='stir'){if(s.ingredients.length<2)text='先加清水与颜料，才有需要分散的颗粒。';else s.stir=Math.min(s.ingredients.includes('binder')?2:1,s.stir+1)};if(action==='color')s.colors=value;if(action==='test'){s.passed=s.ingredients.length===3&&s.stir>=2;s.value=s.colors;text=s.passed?'试涂、干燥后的示意样片均匀连成一层。把这份颜色带回造物间。':'检查颗粒是否分散、胶液是否加入，再试涂一次。'}}
 if(s.id==='drive'){if(action==='purpose')s.purpose=value;if(action==='connect'){if(!s.connections.includes(value))s.connections.push(value)}if(action==='test'){s.passed=['input','middle','output'].every(v=>s.connections.includes(v));s.value=s.purpose;text=s.passed?(s.purpose==='strong'?'大轮作为输出：转得较慢，但理想情况下可获得更大转矩。':'小轮作为输出：转得较快，理想输出转矩相应降低。'):'动作在缺口处停了。依次把输入、中间轮和输出接到传动线上。'}}
 if(s.id==='sequence'){if(action==='swap'){const i=Number(value);if(i>=0&&i<2)[s.sequence[i],s.sequence[i+1]]=[s.sequence[i+1],s.sequence[i]]}if(action==='test'){s.passed=s.sequence.join(',')==='gate,lift,bell';text=s.passed?'开门 → 升台 → 响铃。动作顺利接上了。':'联锁暂停了：门打开后，升台才有空间；升到位后再响铃。'}}
 if(s.id==='diagnose'){if(action==='control')s.control=value;if(action==='observe'){s.observed=s.control==='humidity';text=s.observed?'同一木料、相同方向、相同温度：较湿环境的样片横向尺寸变化更明显。（时间经过压缩）':'这个试验同时改变了木料种类，无法单独判断湿度的影响。'}if(action==='conclude'){s.passed=s.observed&&value==='movement';text=s.passed?'证据支持湿度相关的胀缩。留下环境与尺寸记录，再调整接合间隙。':'先看对照结果。现有证据不能说明是工匠偷工减料。'}}
 if(s.id==='assembly'){if(action==='inspect'&&['shell','ring','mark'].includes(value)&&!s.checked.includes(value)){s.checked.push(value);text=value==='ring'?'这道接合标记没有闭合。请把它对齐。':'这一处检查标记完整。'}if(action==='align'){s.aligned=s.checked.includes('ring');text=s.aligned?'标记已闭合，留下一条检查记录。':'先点选接合处，观察缺口。'}if(action==='test'){s.passed=s.checked.length===3&&s.aligned;text=s.passed?'三处展示标记已检查，总装图录可以合拢。':'检查壳片、接合与序号标记，并修正发现的缺口。'}}
 if(s.passed)s.note=text;return {ok,text};
}
