import * as T from './vendor/three/three.module.js?v=5061f3da916d';
import {OrbitControls} from './vendor/three/OrbitControls.js?v=5061f3da916d';
import {THEMES,materials,createHall,createModule,mesh,ring,spinWheel} from './palace-models.mjs?v=5061f3da916d';

export class PalaceWorld{
 label(text,color='#d4c99c'){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const c=canvas.getContext('2d');c.strokeStyle=color;c.fillStyle=color;c.lineWidth=2;c.strokeRect(16,12,480,102);c.font='700 40px SimSun';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,64);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(2.1,.525),new T.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false}))}
 constructor(canvas,onPick=()=>{}){
  this.canvas=canvas;this.onPick=onPick;this.era=0;this.mode='overview';this.enabled=false;this.animations=[];this.state=null;this.selected=-1;
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;
  this.scene=new T.Scene();this.scene.background=new T.Color(0x071b25);this.scene.fog=new T.FogExp2(0x0a2531,.021);this.camera=new T.PerspectiveCamera(48,1,.1,100);this.camera.position.set(0,9.5,28);
  this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,4,-2);this.controls.enableDamping=true;this.controls.enablePan=false;this.controls.minDistance=13;this.controls.maxDistance=38;this.controls.maxPolarAngle=Math.PI*.49;this.controls.minPolarAngle=.35;this.controls.enabled=false;
  this.ambient=new T.HemisphereLight(0xc4edeb,0x33452f,2.1);this.scene.add(this.ambient);const key=new T.DirectionalLight(0xffddb1,3.7);key.position.set(-7,16,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);Object.assign(key.shadow.camera,{left:-16,right:16,top:18,bottom:-16,near:1,far:55});key.shadow.bias=-.001;this.scene.add(key);this.keyLight=key;const rim=new T.DirectionalLight(0x92dddd,2.3);rim.position.set(5,10,-13);this.scene.add(rim);
  this.mat=materials();this.rebuild(0);this.ray=new T.Raycaster();this.ray.params.Line.threshold=.08;this.pointer=new T.Vector2();this.down=null;
  canvas.addEventListener('pointerdown',e=>this.down=[e.clientX,e.clientY]);canvas.addEventListener('pointerup',e=>{if(!this.enabled||!this.down||Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])>8)return;const r=canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hit=this.ray.intersectObjects([...this.modules.filter(g=>g.visible),...this.blueprints],true).find(h=>h.object.userData.module!==undefined);if(hit)this.onPick(hit.object.userData.module)});
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas);this.resize();this.last=0;this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame);
 }
 rebuild(era){
  if(this.hall){this.scene.remove(this.hall,this.assembly,this.wall);for(const group of [this.hall,this.assembly,this.wall])group.traverse(o=>o.geometry?.dispose());Object.values(this.mat).forEach(m=>m.dispose())}
  this.era=era;this.mat=materials(THEMES[era]);this.hall=createHall(this.mat);this.scene.add(this.hall);this.assembly=new T.Group();this.scene.add(this.assembly);this.wall=new T.Group();this.wall.position.set(0,.15,-16.25);this.scene.add(this.wall);this.modules=[];this.blueprints=[];
  for(let i=0;i<8;i++){
   const model=createModule(i,this.mat);model.visible=false;this.assembly.add(model);this.modules.push(model);
   const blueprint=new T.Group();blueprint.userData.module=i;const source=createModule(i,this.mat);source.updateMatrixWorld(true);source.traverse(o=>{if(o.isMesh){const geo=new T.EdgesGeometry(o.geometry,25);geo.applyMatrix4(o.matrixWorld);const line=new T.LineSegments(geo,new T.LineBasicMaterial({color:0xc2e8dd,transparent:true,opacity:.48}));line.scale.z=.018;line.userData.module=i;blueprint.add(line);o.geometry.dispose()}});const hit=mesh(blueprint,new T.BoxGeometry(i===0?6:4,1.2,.08),new T.MeshBasicMaterial({visible:false}),0,[.4,4.2,4.2,2.4,1.2,3,6.8,8.3][i],.1);hit.userData.module=i;this.wall.add(blueprint);this.blueprints.push(blueprint);
  }
  this.stamps=[];for(let i=0;i<8;i++){const stamp=this.label('已 成','#ac7052');stamp.position.set(i%2?3.6:-3.6,1.4+Math.floor(i/2)*1.9,.2);stamp.scale.setScalar(.6);stamp.visible=false;this.wall.add(stamp);this.stamps.push(stamp)}this.failureMarks=new T.Group();this.wall.add(this.failureMarks);if(this.networkNodes)this.configureNetwork(this.networkNodes);this.applyState(this.state);
 }
 configureNetwork(nodes){this.networkNodes=nodes;const stars=this.hall.userData.stars;while(stars.children.length){const o=stars.children[0];o.geometry?.dispose();if(o.userData.tech||o.userData.edge)o.material?.dispose();stars.remove(o)}this.techStars=new Map();this.techEdges=[];const coords=new Map();for(const n of nodes){const a=n.branch/7*Math.PI*2-.4,r=2.5+n.rank*.63,x=Math.sin(a)*r,z=Math.cos(a)*r,y=Math.sqrt(Math.max(0,100-r*r))*.38;coords.set(n.id,new T.Vector3(x,y,z));const o=mesh(stars,new T.IcosahedronGeometry(.065,0),new T.MeshBasicMaterial({color:0x688c95}),x,y,z);o.userData.tech=n.id;this.techStars.set(n.id,o)}for(const n of nodes)for(const d of n.deps){const edge=new T.Line(new T.BufferGeometry().setFromPoints([coords.get(d),coords.get(n.id)]),new T.LineBasicMaterial({color:0x587b86,transparent:true,opacity:.3}));edge.userData={edge:true,from:d,to:n.id};stars.add(edge);this.techEdges.push(edge)}}
 highlightTech(chain){if(!this.techStars)return;this.techStars.forEach((o,id)=>o.scale.setScalar(chain?.has(id)?1.8:1));for(const edge of this.techEdges){const on=chain?.has(edge.userData.from)&&chain?.has(edge.userData.to);edge.material.color.set(on?0xf3da9b:0x668e97);edge.material.opacity=chain?(on?.9:.12):.3}}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 applyState(state){this.state=state;if(!state)return;this.enabled=state.phase==='playing'||state.phase==='victory';if(this.era!==state.era){this.rebuild(state.era);return}for(let i=0;i<8;i++){this.modules[i].visible=!!state.modules?.[i];if(this.stamps)this.stamps[i].visible=!!state.modules?.[i];this.blueprints[i].traverse(o=>{if(o.isLineSegments)o.material.opacity=state.modules?.[i]?.18:.53})}this.hall.userData.bays.forEach((b,i)=>{b.userData.door.visible=!this.enabled;b.userData.details.visible=this.enabled;b.userData.wheel.visible=this.enabled;b.userData.upgradeOne.visible=this.enabled&&(state.upgrades?.[i]||0)>=1;b.userData.upgradeTwo.visible=this.enabled&&(state.upgrades?.[i]||0)>=2;b.scale.y=1+(state.upgrades?.[i]||0)*.04});this.ambient.intensity=this.enabled?2.1:1.15;this.keyLight.intensity=this.enabled?3.7:2;this.hall.userData.stars.visible=this.enabled;if(this.techStars)for(const n of this.networkNodes){const color=state.known?.includes(n.id)?0xe3c388:n.deps.every(id=>state.known?.includes(id))?0xb1e9e2:0x547482;this.techStars.get(n.id).material.color.set(color)}this.controls.enabled=this.enabled&&this.mode==='assembly';while(this.failureMarks.children.length){const c=this.failureMarks.children[0];c.geometry?.dispose();c.material?.dispose();this.failureMarks.remove(c)}for(let i=0;i<Math.min(state.failures||0,8);i++){const mark=ring(this.failureMarks,new T.MeshBasicMaterial({color:0xa55343}),.3,.012,-4.4+(i%2)*.8,2+Math.floor(i/2)*1.2,.05);mark.rotation.x=0}}
 setMode(mode){this.mode=mode;this.controls.enabled=this.enabled&&mode==='assembly';const presets={overview:[[0,9.5,28],[0,4,-2]],assembly:[[11,8,15],[0,4,0]],tech:[[0,6,19],[0,13,-3]]};const [pos,target]=presets[mode]||presets.overview;this.cameraMove={from:this.camera.position.clone(),to:new T.Vector3(...pos),a:this.controls.target.clone(),b:new T.Vector3(...target),t:0}}
 select(index){this.selected=index;this.blueprints.forEach((g,i)=>g.traverse(o=>{if(o.isLineSegments){o.material.color.set(i===index?0xffd990:0xb8dedb);o.material.opacity=i===index?.95:this.state?.modules?.[i]?.18:.5}}))}
 reveal(index,onDone=()=>{}){const obj=this.modules[index],surfaces=[],edges=[];obj.visible=true;obj.position.set(0,0,-15);obj.scale.set(1,1,.025);obj.traverse(o=>{if(o.isMesh){const original=o.material;o.material=original.clone();o.material.transparent=true;o.material.opacity=0;surfaces.push({o,original});const edge=new T.LineSegments(new T.EdgesGeometry(o.geometry),new T.LineBasicMaterial({color:0xd2ead7,transparent:true,opacity:1}));o.add(edge);edges.push(edge)}});this.animations.push({kind:'reveal',obj,t:0,duration:4.2,surfaces,edges,onDone});this.select(index)}
 beginCeremony(){this.hall.userData.stars.visible=false;this.ambient.intensity=.8;this.keyLight.intensity=1.4}
 ceremonyStep(i){this.ambient.intensity=1.15+i*.24;this.keyLight.intensity=2+i*.4;this.hall.userData.bays.forEach((b,n)=>{if(n<=i*2){b.userData.door.visible=false;b.userData.details.visible=true;b.userData.wheel.visible=true}});if(i>=2)this.hall.userData.stars.visible=true}
 finale(){this.hall.userData.stars.visible=true;this.finalTime=0;this.keyLight.intensity=5;for(let i=0;i<8;i++)this.inspect(i)}
 inspect(index){this.select(index);this.animations.push({kind:'test',obj:this.modules[index],t:0,duration:2.5,onDone:()=>{}})}
 setQuality(simple){this.renderer.setPixelRatio(simple?1:Math.min(devicePixelRatio||1,1.7));this.renderer.shadowMap.enabled=!simple;this.resize()}
 frame(now){const dt=Math.min(.05,(now-this.last)/1000||0);this.last=now;if(!document.hidden&&!this.suspended){if(this.cameraMove){const m=this.cameraMove;m.t=Math.min(1,m.t+dt/1.1);const t=m.t*m.t*(3-2*m.t);this.camera.position.lerpVectors(m.from,m.to,t);this.controls.target.lerpVectors(m.a,m.b,t);if(m.t===1)this.cameraMove=null}this.controls.update();if(this.finalTime!==undefined){this.finalTime+=dt;this.hall.userData.stars.rotation.y+=dt*.3;this.keyLight.intensity=3.7+Math.max(0,1.3-this.finalTime*.2);if(this.finalTime>6)this.finalTime=undefined}for(const b of this.hall.userData.bays)if(this.enabled&&b.userData.wheel)spinWheel(b.userData.wheel,dt*.09);for(const a of this.animations){a.t+=dt;const p=Math.min(1,a.t/a.duration),s=p*p*(3-2*p);if(a.kind==='reveal'){a.obj.position.z=-15*(1-s);a.obj.scale.z=.025+.975*s;a.obj.rotation.y=Math.sin(p*Math.PI)*.15;for(const v of a.surfaces)v.o.material.opacity=Math.max(0,Math.min(1,(p-.27)/.6));for(const edge of a.edges)edge.material.opacity=1-Math.max(0,(p-.55)/.45)}else a.obj.rotation.y=Math.sin(p*Math.PI*4)*.045;if(p===1){a.obj.position.z=0;a.obj.scale.z=1;a.obj.rotation.y=0;if(a.surfaces){for(const v of a.surfaces){v.o.material.dispose();v.o.material=v.original}for(const edge of a.edges){edge.parent?.remove(edge);edge.geometry.dispose();edge.material.dispose()}}a.onDone();a.done=true}}this.animations=this.animations.filter(a=>!a.done);this.hall.userData.stars.rotation.y+=dt*.012;if(this.state?.modules?.[6])this.modules[6].traverse(o=>{if(o.userData.spin)o.rotation.y+=dt*.15});this.renderer.render(this.scene,this.camera)}this.raf=requestAnimationFrame(this.frame)}
 dispose(){cancelAnimationFrame(this.raf);this.resizeObserver.disconnect();this.controls.dispose();this.scene.traverse(o=>o.geometry?.dispose());this.renderer.dispose()}
}
