import * as T from './vendor/three/three.module.js?v=8e433e6a8218';
import {materials,THEMES,createModule,ring,box} from './palace-models.mjs?v=8e433e6a8218';

function lighting(scene){scene.add(new T.HemisphereLight(0xe5f3d8,0x17303b,2.5));const a=new T.DirectionalLight(0xffd6a3,4);a.position.set(-4,8,8);scene.add(a);const b=new T.DirectionalLight(0x89d9dd,2);b.position.set(6,5,-5);scene.add(b)}
function centeredModel(id,mat){const model=id==='final'?new T.Group():createModule(id,mat);if(id==='final')for(let i=0;i<8;i++)model.add(createModule(i,mat));const bounds=new T.Box3().setFromObject(model),center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3());model.position.sub(center);const holder=new T.Group();holder.add(model);holder.scale.setScalar(3.8/Math.max(size.x,size.y,size.z));return {holder,model}}

export class PropPortraits{
 constructor(){this.canvas=document.createElement('canvas');this.renderer=new T.WebGLRenderer({canvas:this.canvas,antialias:true,alpha:true});this.renderer.setSize(240,170,false);this.renderer.setPixelRatio(1);this.renderer.outputColorSpace=T.SRGBColorSpace;this.scene=new T.Scene();lighting(this.scene);this.camera=new T.PerspectiveCamera(37,240/170,.1,40);this.camera.position.set(4,2.8,7);this.camera.lookAt(0,0,0);this.cache=new Map()}
 draw(canvas,id,era=0){const key=era+':'+id;if(!this.cache.has(key)){const mat=materials(THEMES[era]),{holder}=centeredModel(id,mat);this.scene.add(holder);this.renderer.render(this.scene,this.camera);const copy=document.createElement('canvas');copy.width=240;copy.height=170;copy.getContext('2d').drawImage(this.canvas,0,0);this.cache.set(key,copy);this.scene.remove(holder);holder.traverse(o=>o.geometry?.dispose());Object.values(mat).forEach(m=>m.dispose())}const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.drawImage(this.cache.get(key),0,0,canvas.width,canvas.height)}
 dispose(){this.renderer.dispose();this.cache.clear()}
}

export class CraftBench{
 constructor(canvas,{onProgress=()=>{},onFeedback=()=>{},targets}){
  this.canvas=canvas;this.onProgress=onProgress;this.onFeedback=onFeedback;this.targets=targets;this.progress=0;this.quality=1;this.active=false;this.angle=-1.15;this.down=false;this.last=null;this.taps=0;this.time=0;this.mode='polish';this.renderer=null;
  try{this.renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;this.scene=new T.Scene();lighting(this.scene);this.camera=new T.PerspectiveCamera(42,1,.1,40);this.camera.position.set(4.5,2.8,6.8);this.camera.lookAt(0,0,0)}catch(e){console.warn('Craft 3D unavailable',e.message)}
  canvas.addEventListener('pointerdown',e=>{if(!this.active)return;this.down=true;this.last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);if(this.mode==='join')this.tap()});canvas.addEventListener('pointermove',e=>{if(!this.active||!this.down||!this.last)return;const dx=e.clientX-this.last.x,dy=e.clientY-this.last.y,r=canvas.getBoundingClientRect();if(this.mode==='polish'){this.add(Math.min(5,Math.hypot(dx,dy)*.10));if(this.holder)this.holder.rotation.y+=dx*.002}else if(this.mode==='align'){this.angle+=dx*.009;this.align()}else if(this.mode==='turn'){let d=Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)-Math.atan2(this.last.y-r.top-r.height/2,this.last.x-r.left-r.width/2);d=Math.atan2(Math.sin(d),Math.cos(d));if(Math.abs(d)<.8){this.angle+=d;this.add(Math.abs(d)*12)}}this.last={x:e.clientX,y:e.clientY}});for(const name of ['pointerup','pointercancel'])canvas.addEventListener(name,()=>{this.down=false;this.last=null});this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame);
 }
 start(mode,id,era=0){this.stop();this.active=true;this.mode=mode;this.progress=0;this.quality=1;this.angle=-1.15;this.taps=0;this.down=false;this.time=0;this.onProgress(0);this.targets.innerHTML='';if(this.renderer){this.mat=materials(THEMES[era]);const c=centeredModel(id,this.mat);this.holder=c.holder;this.model=c.model;this.parts=[];this.model.traverse(o=>{if(o.isMesh){o.userData.origin=o.position.clone();this.parts.push(o)}});this.scene.add(this.holder);if(mode==='align')this.holder.rotation.y=this.angle;this.resize()}
  if(mode==='join'){for(let i=0;i<4;i++){const b=document.createElement('button');b.className='craft-target';b.style.left=(i%2?68:32)+'%';b.style.top=(i<2?31:66)+'%';b.textContent=String(i+1);b.setAttribute('aria-label','拼合第 '+(i+1)+' 处接口');b.onclick=()=>this.tap(i);this.targets.append(b)}this.onFeedback('按顺序点击 1—4，让接口一处处扣合')}
  else if(mode==='balance'){const track=document.createElement('div');track.className='balance-track';track.innerHTML='<span></span><i></i>';this.targets.append(track);this.onFeedback('按住零件，光标经过中间区域时会逐步稳定')}
  else this.onFeedback(({polish:'按住并来回打磨 · 表面会慢慢显露光泽',turn:'按住绕着零件画圈 · 顺时针或逆时针都可以',align:'按住向右拖动，直到两道标记对齐'})[mode]);
 }
 tap(index=this.taps){if(this.mode!=='join'||!this.active||this.progress>=100)return;if(index!==this.taps){this.onFeedback('先拼合第 '+(this.taps+1)+' 处，接口会依次亮起');return}this.targets.children[this.taps]?.classList.add('hit');this.taps++;this.add(25)}
 align(){const error=Math.abs(Math.atan2(Math.sin(this.angle),Math.cos(this.angle)));this.progress=error<.085?100:Math.max(0,100-error/1.15*100);this.update();if(this.holder)this.holder.rotation.y=this.angle;this.onFeedback(this.progress>=100?'对齐了，环架已经回到同一个方向。':'还差一点，慢慢向亮起的位置靠拢')}
 add(amount){if(this.progress>=100)return;this.progress=Math.min(100,this.progress+amount);this.update()}
 update(){if(this.progress>=100){this.down=false;this.onFeedback('做好了，这件零件已经可以参与工程。')}this.onProgress(Math.round(this.progress));if(this.mode==='join'&&this.parts){const p=1-this.progress/100;this.parts.forEach((o,i)=>{o.position.copy(o.userData.origin);o.position.x+=(i%2?1:-1)*p*.32;o.position.y+=p*.1})}if(this.mat&&this.mode==='polish'){this.mat.wood.roughness=.9-this.progress*.004;this.mat.metal.roughness=.75-this.progress*.005}}
 assist(){if(!this.active||this.progress>=100)return;if(this.mode==='join')this.tap();else if(this.mode==='align'){this.angle*=.68;this.align()}else this.add(12.5)}
 resize(){if(!this.renderer)return;const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 frame(now){const dt=Math.min(.04,(now-(this.lastTime||now))/1000);this.lastTime=now;if(this.active&&!document.hidden){this.time+=dt;if(this.mode==='balance'){const phase=.5+Math.sin(this.time*1.6)*.37,marker=this.targets.querySelector('i');if(marker)marker.style.left=(phase*100)+'%';if(this.down&&phase>.28&&phase<.72)this.add(dt*23);if(this.mat)this.mat.amber.opacity=.45+this.progress*.0045}if(this.holder&&this.mode==='turn')this.holder.rotation.y=this.angle;if(this.renderer){this.renderer.render(this.scene,this.camera)}}this.raf=requestAnimationFrame(this.frame)}
 stop(){this.active=false;this.down=false;if(this.holder){this.scene.remove(this.holder);this.holder.traverse(o=>o.geometry?.dispose());Object.values(this.mat).forEach(m=>m.dispose());this.holder=null}this.targets.innerHTML=''}
 dispose(){this.stop();cancelAnimationFrame(this.raf);this.observer.disconnect();this.renderer?.dispose()}
}
