import {PalaceWorld} from './palace-world.mjs?v=433f66e85192';
import {CraftBench,PropPortraits} from './palace-craft.mjs?v=433f66e85192';
const G=window.PalaceGame,$=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)],KEY='tiangong-palace-v2',PREF='tiangong-palace-preferences';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let state=G.sanitize(read(KEY,null)),era=state?.era??0,mode='overview',selected=null,plan='steady',world,portraits,craft=null,toastTimer,holdTimer,ceremonyTimer,ceremony=false,readyOnly=false,zoom=1,audio;
const prefs={muted:false,simple:false,ceremonies:0,...read(PREF,{})};const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){try{if(state)localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(PREF,JSON.stringify(prefs));$('save-status').textContent='进度自动记下'}catch{$('save-status').textContent='本次进度暂时无法保存'}}
function say(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4200)}
function sound(kind='click'){if(prefs.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,o=audio.createOscillator(),gain=audio.createGain();o.type=kind==='seal'?'triangle':'sine';const f=kind==='seal'?100:kind==='success'?660:kind==='failure'?170:420;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(kind==='success'?880:f*.6,now+.25);gain.gain.setValueAtTime(.055,now);gain.gain.exponentialRampToValueAtTime(.001,now+1);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(now+1)}catch{}}
try{world=new PalaceWorld($('palace'),id=>selectModule(id));world.configureNetwork(G.nodes);world.setQuality(prefs.simple)}catch(e){console.error(e);$('graphics-warning').hidden=false}
try{portraits=new PropPortraits()}catch(e){console.warn('Module portraits use text fallback',e.message)}
const bench=new CraftBench($('craft-3d'),{targets:$('craft-targets'),onProgress:n=>{$('craft-progress').value=n;$('craft-percent').textContent=n+'%';$('craft-submit').disabled=n<100;$('craft-submit').textContent=n>=100?'做好了，提交验证 →':'继续加工'},onFeedback:t=>$('craft-feedback').textContent=t});

function showEras(){
 $('era-screen').hidden=false;$('founding').hidden=true;$('game-hud').hidden=true;document.body.dataset.phase='choose';$('resume').hidden=!state;world?.applyState({era,phase:'founding',modules:{},upgrades:{},failures:0});
 $('era-cards').innerHTML=G.eras.map((e,i)=>`<button class="era-card ${i===era?'active':''}" data-era="${i}" aria-pressed="${i===era}"><span class="era-portrait"><img src="${e.portrait}" alt="" aria-hidden="true"><i>${e.seal}</i></span><div><strong>${e.name}</strong><small>${e.date}</small></div><em>${e.tag}</em></button>`).join('');$('era-description').textContent=G.eras[era].summary;
 $$('[data-era]').forEach(b=>b.onclick=()=>{era=+b.dataset.era;showEras()});
}
function enterNew(){state=G.fresh(era,state?.legacy||[]);save();showFounding()}
function showFounding(){selected=null;closePanel();$('era-screen').hidden=true;$('game-hud').hidden=true;$('founding').hidden=false;$('imperial-seal').hidden=false;$('imperial-seal').disabled=false;$('ceremony-copy').textContent='';$('skip-ceremony').hidden=true;document.body.dataset.phase='founding';world?.applyState(state);world?.setMode('overview')}
function startCeremony(){if(ceremony||state?.phase!=='founding')return;ceremony=true;clearTimeout(holdTimer);$('imperial-seal').hidden=true;$('skip-ceremony').hidden=prefs.ceremonies<1;world?.beginCeremony?.();sound('seal');const captions=['地宫启封，七座侧殿依次苏醒。','铜轨归位，灯火沿着中轴亮起。','完整的文明星图，正在穹顶展开。','墙上的未来始终完整，现实需要你亲手造就。','地宫造物已经启封。工程纪年，自今日始。'];let i=0;$('ceremony-copy').textContent=captions[0];ceremonyTimer=setInterval(()=>{i++;if(i>=captions.length){endCeremony();return}$('ceremony-copy').textContent=captions[i];world?.ceremonyStep?.(i)},reduced?400:2500)}
function endCeremony(){if(!ceremony)return;clearInterval(ceremonyTimer);ceremony=false;G.establish(state);prefs.ceremonies++;save();showGame();selectModule(0);sound('success')}
$('imperial-seal').addEventListener('pointerdown',e=>{e.preventDefault();$('imperial-seal').classList.add('pressed');$('seal-progress').style.transition='width .65s linear';$('seal-progress').style.width='100%';holdTimer=setTimeout(startCeremony,650)});
for(const type of ['pointerup','pointercancel','pointerleave'])$('imperial-seal').addEventListener(type,()=>{clearTimeout(holdTimer);$('imperial-seal').classList.remove('pressed');$('seal-progress').style.transition='none';$('seal-progress').style.width='0'});
$('imperial-seal').addEventListener('keydown',e=>{if(e.key==='Enter'||e.code==='Space'){e.preventDefault();startCeremony()}});$('imperial-seal').onclick=e=>{if(e.detail===0)startCeremony()};$('skip-ceremony').onclick=endCeremony;
$('enter-era').onclick=()=>{if(state&&state.phase!=='founding')confirmNew(enterNew);else enterNew()};$('resume').onclick=()=>{era=state.era;if(state.phase==='founding')showFounding();else{showGame();if(state.phase==='ended'||state.phase==='victory')showEnding()}};

function showGame(){document.body.dataset.phase=state.phase;$('era-screen').hidden=true;$('founding').hidden=true;$('game-hud').hidden=false;setMode('overview');render();if(state.pendingEvent!==null)showEvent()}
function render(){if(!state)return;save();world?.applyState(state);$('sound').textContent=prefs.muted?'♪':'♫';const e=G.eras[state.era];$('resources').innerHTML=[['国库',state.coins,'材料与征调'],['工匠',state.crew+' 人','常备手作队'],['支持',state.support+'%','成果会恢复'],['工程时间',state.months+' / '+state.limit+' 月','只随你的行动推进']].map(([label,value,note])=>`<div class="resource"><label>${label}</label><b>${value}</b><small>${note}</small></div>`).join('');$('era-menu').textContent=e.seal+' · '+e.name+'　工程第 '+(Math.floor(state.months/12)+1)+' 年';$('module-count').textContent=Object.keys(state.modules).length+' / 8 已成';
 $('module-tray').innerHTML=G.modules.map(m=>{const done=!!state.modules[m.id],ready=G.moduleReady(state,m.id),matches=selected?.type==='module'&&selected.id===m.id;return `<button class="module-card ${done?'complete':''} ${matches?'active':''}" data-module="${m.id}" aria-label="${m.name}，${done?'已成':ready?'可以制作':'查看前置'}"><canvas width="240" height="170" aria-hidden="true"></canvas><strong>${m.short}</strong><small>${done?'已成':ready?'可以制作':G.moduleMissing(state,m.id).length+' 项待攻克'}</small></button>`}).join('');$$('[data-module]').forEach(b=>{portraits?.draw(b.querySelector('canvas'),+b.dataset.module,state.era);b.onclick=()=>selectModule(+b.dataset.module)});
 const next=G.nextStep(state);if(state.phase==='victory'){$('chapter').textContent='巡天之器 · '+state.ending;$('objective-title').textContent='未来已经有了重量';$('objective-copy').textContent='继续完善侧殿、重复验证，或重看这次工程。';$('next-action').textContent='查看本轮成果 →';$('next-action').onclick=showEnding}
 else if(state.phase==='ended'){$('chapter').textContent='本轮工程 · 暂时停下';$('objective-title').textContent='把经验留给下一次';$('next-action').textContent='查看工程记录 →';$('next-action').onclick=showEnding}
 else{$('chapter').textContent=Object.keys(state.modules).length?'造物渐成 · 第 '+(Object.keys(state.modules).length+1)+' 章':'造物初启 · 第一卷';$('objective-title').textContent=next?.type==='tech'?'下一步 · '+G.nodeById[next.id].name:next?.type==='module'?'亲手做出'+G.modules[next.id].short:next?.type==='system'?'验证'+G.systems.find(t=>t.id===next.id).name:'让巡天器完整苏醒';$('objective-copy').textContent=next?.type==='tech'?'从这项能力开始，离下一个实体更近一点。':next?.type==='module'?G.modules[next.id].text:'四个系统已经具备条件，最后再把它们接在一起。';$('next-action').textContent=state.pendingEvent!==null?'处理工坊来信 →':'继续这一步 →';$('next-action').onclick=()=>state.pendingEvent!==null?showEvent():activateNext(next)}
 if(mode==='tech')renderNetwork();if(selected)renderPanel();
}
function activateNext(next=G.nextStep(state)){if(!next)return say('可以到侧殿整理资源，或查看未完成的部件。');if(next.type==='tech')selectTech(next.id);if(next.type==='module')selectModule(next.id);if(next.type==='system')selectSystem(next.id);if(next.type==='final')beginFinal()}
function setMode(value){mode=value;document.body.dataset.view=value;world?.setMode(value);$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===value));$('tech-view').hidden=value!=='tech';if(value==='tech')renderNetwork();else if(selected?.type==='tech')closePanel()}
$$('[data-mode]').forEach(b=>b.onclick=()=>{setMode(b.dataset.mode);sound()});
function closePanel(){selected=null;$('context-panel').hidden=true;document.body.classList.remove('panel-open');world?.select(-1)}$('close-panel').onclick=()=>{closePanel();render()};
function selectModule(id){if(!state||state.phase==='founding')return;selected={type:'module',id};world?.select(id);renderPanel();highlightNetwork();$$('[data-module]').forEach(b=>b.classList.toggle('active',+b.dataset.module===id));sound()}
function selectTech(id){if(!G.nodeById[id]||!state||state.phase==='founding')return;selected={type:'tech',id};renderPanel();highlightNetwork();sound()}
function selectSystem(id){selected={type:'system',id};renderPanel();sound()}
function dependencyButtons(ids){return ids.map(id=>`<button class="dependency ${state.known.includes(id)?'done':''}" data-dependency="${id}"><span>${state.known.includes(id)?'✓':'◇'}</span>${G.nodeById[id].name}<span class="status">${state.known.includes(id)?'已具备':G.status(state,id)==='ready'?'可攻克':'查看前置'}</span></button>`).join('')}
function renderPanel(){if(!selected)return;$('context-panel').hidden=false;document.body.classList.add('panel-open');const out=$('panel-content');
 if(selected.type==='module'){const m=G.modules[selected.id],done=state.modules[m.id],missing=G.moduleMissing(state,m.id),before=m.before.filter(id=>!state.modules[id]);out.innerHTML=`<p class="eyebrow">M${String(m.id+1).padStart(2,'0')} · ${done?'已成':'总装构件'}</p><h2>${m.name}</h2><canvas class="module-preview" width="480" height="250" aria-label="${m.name}的三维预览"></canvas><p>${m.text}</p><div class="detail-label">制造能力 · ${m.deps.length-missing.length}/${m.deps.length}</div>${dependencyButtons(m.deps)}${before.length?'<p class="risk-note">先装好：'+before.map(id=>G.modules[id].short).join('、')+'</p>':''}${done?`<p class="risk-note">已经在中央就位 · 第 ${done.built} 月制成</p><button class="primary" id="module-inspect">局部验证 · 看它动起来</button>`:`<div class="cost-line"><span>国库 12</span><span>工匠 2 人</span><span>耗时 2 月</span></div><button class="primary" id="module-build" ${G.moduleReady(state,m.id)?'':'disabled'}>亲手制作并装配 →</button><button class="secondary" id="module-next">${missing.length?'去攻克最接近的前置':'查看下一步'}</button>`}`;portraits?.draw(out.querySelector('canvas'),m.id,state.era);if(done)$('module-inspect').onclick=()=>{world?.inspect(m.id);sound('success');say('局部验证：'+m.short+'保持稳定。')};else{$('module-build').onclick=()=>beginModule(m.id);$('module-next').onclick=()=>{const chain=new Set();m.deps.forEach(id=>G.dependencyChain(id,chain));const n=G.nodes.find(n=>chain.has(n.id)&&G.status(state,n.id)==='ready');if(n)selectTech(n.id);else if(before.length)selectModule(before[0]);else activateNext()}}}
 else if(selected.type==='tech'){const n=G.nodeById[selected.id],st=G.status(state,n.id),done=state.known.includes(n.id),q=G.quote(state,n.id,plan),missing=G.missing(state,n.id),source=G.sources[n.source];const affected=G.modules.filter(m=>m.deps.some(id=>G.dependencyChain(id).has(n.id)));out.innerHTML=`<p class="eyebrow">${G.branches[n.branch].name} · ${done?'实现完成':st==='ready'?'可攻克':'尚缺文明能力'}</p><h2>${n.name}</h2><p>理论知识：始终已掌握<br>当前制造：${done?'可以稳定用于工程':st==='ready'?'前置齐备，可以亲手试制':'有完整构想，尚需补齐基础'}</p>${n.deps.length?'<div class="detail-label">前置能力</div>'+dependencyButtons(n.deps):'<p class="risk-note">这是一项基础能力，可以直接开始。</p>'}<div class="detail-label">将用于</div><p>${affected.map(m=>m.short).join(' · ')||'文明工业体系'}</p>${done?`<p class="risk-note">工艺可靠度 ${state.reliability[n.id]||90}% · 游戏评分</p><button id="tech-next" class="primary">继续下一步 →</button>`:`<div class="plan-options">${Object.entries(G.plans).map(([id,p])=>`<button class="plan-option ${plan===id?'active':''}" data-plan="${id}">${p.name}<small>${p.note.split(' · ')[0]}</small></button>`).join('')}</div><div class="cost-line"><span>国库 ${q.coins}</span><span>工匠 ${q.crew} 人</span><span>${q.months} 月</span></div><p class="risk-note">${missing.length?'缺少 '+missing.length+' 项前置。强行试制通常会失败，但会指出具体瓶颈。':plan==='rush'?'省时间，完成度不足可能需要再磨合一次。':'完成手作即可实现。'+(plan==='thrifty'?'多花一点时间，节省材料。':'稳妥推进，适合第一次玩。')}</p><button class="primary" id="trial-normal" ${missing.length?'disabled':''}>亲手试制 →</button><button class="quiet" id="trial-force">强行试制 · 国库 ${G.quote(state,n.id,plan,true).coins}</button>`}<details class="history-note"><summary>史实参考与游戏推演</summary><p>时代起点：${n.eraLevels[state.era]===2?'本局设为已有基础':n.eraLevels[state.era]===1?'本局设为相邻可实现层级':'本局尚无稳定制造体系'}。以上为游戏化推演。</p><p>${n.history}</p><p>${source.note}</p><a href="${source.url}" target="_blank" rel="noopener">${source.title} ↗</a></details>`;
  $$('[data-plan]').forEach(b=>b.onclick=()=>{plan=b.dataset.plan;renderPanel()});if(done)$('tech-next').onclick=()=>activateNext();else{$('trial-normal').onclick=()=>beginTrial(n.id,false);$('trial-force').onclick=()=>beginTrial(n.id,true)}}
 else{const t=G.systems.find(x=>x.id===selected.id),done=state.systems[t.id];out.innerHTML=`<p class="eyebrow">独立系统验证</p><h2>${t.name}</h2><p>确认所属部件能够配合，而不只是单独工作。</p><div class="detail-label">所需部件</div>${t.modules.map(id=>`<button class="dependency ${state.modules[id]?'done':''}" data-module-link="${id}">${state.modules[id]?'✓':'○'} ${G.modules[id].name}</button>`).join('')}<div class="cost-line"><span>国库 5</span><span>工匠 2 人</span><span>耗时 1 月</span></div>${done?`<p class="risk-note">已通过 ${done.repeats} 次 · 协同评分 ${done.quality}%</p>`:''}<button id="system-test" class="primary" ${G.systemReady(state,t.id)?'':'disabled'}>${done?'再验证一次':'开始独立验证'} →</button>`;$('system-test').onclick=()=>beginSystem(t.id)}
 $$('[data-dependency]').forEach(b=>b.onclick=()=>selectTech(b.dataset.dependency));$$('[data-module-link]').forEach(b=>b.onclick=()=>selectModule(+b.dataset.moduleLink));
}

function nodePosition(n){return {x:78+n.branch*185+(n.rank%2?22:0),y:78+n.rank*70}}
function renderNetwork(){if(!state)return;const search=$('tech-search').value.trim().toLowerCase(),branch=$('branch-filter').value;const passes=n=>(branch==='all'||n.branch===+branch)&&(!search||n.name.toLowerCase().includes(search))&&(!readyOnly||G.status(state,n.id)==='ready');
 let markup=G.branches.map((b,i)=>`<text class="branch-title" x="${78+i*185}" y="31" text-anchor="middle">${b.name}</text>`).join('');
 for(const n of G.nodes)for(const id of n.deps){const a=nodePosition(G.nodeById[id]),b=nodePosition(n),on=state.known.includes(id)&&state.known.includes(n.id);markup+=`<path class="network-edge" data-from="${id}" data-to="${n.id}" d="M${a.x} ${a.y} C${a.x} ${(a.y+b.y)/2},${b.x} ${(a.y+b.y)/2},${b.x} ${b.y}" fill="none" stroke="${on?'#b6a272':'#5b7d8066'}" stroke-width="${on?1.5:1}"/>`}
 for(const n of G.nodes){const p=nodePosition(n),st=G.status(state,n.id),color=st==='known'||st==='breakthrough'?'#dfc48e':st==='ready'?'#b7e3dc':'#668a91',show=passes(n);markup+=`<g class="network-node" data-node="${n.id}" role="button" tabindex="0" aria-label="${n.name}，${({known:'已有',breakthrough:'本轮突破',ready:'可攻克',blocked:'缺少前置'})[st]}" opacity="${show?1:.17}"><circle cx="${p.x}" cy="${p.y}" r="${st==='breakthrough'?14:12}" fill="#17343d" stroke="${color}" stroke-width="${st==='ready'?2:1.3}"/>${st==='breakthrough'?`<circle cx="${p.x}" cy="${p.y}" r="18" fill="none" stroke="#ad755b" stroke-width="1"/>`:''}<text x="${p.x}" y="${p.y+4}" text-anchor="middle" fill="${color}" font-size="10">${state.known.includes(n.id)?'◆':st==='ready'?'◇':'·'}</text><text x="${p.x}" y="${p.y+30}" text-anchor="middle" fill="${color}" font-size="11">${n.name}</text></g>`}
 for(let i=0;i<4;i++){const t=G.systems[i],x=265+i*255;markup+=`<g role="button" tabindex="0" data-system="${t.id}" class="network-node"><rect x="${x-78}" y="699" width="156" height="44" rx="2" fill="#254443" stroke="${state.systems[t.id]?'#dac18d':'#91b9b1'}"/><text x="${x}" y="725" fill="#dbdac0" font-size="12" text-anchor="middle">${state.systems[t.id]?'✓ ':''}${t.name}</text></g>`}
 markup+='<g role="button" tabindex="0" data-final="true" class="network-node"><path d="M610 785 L650 758 L690 785 L650 812 Z" fill="#35534b" stroke="#d5c69a"/><text x="650" y="789" fill="#efe2b2" text-anchor="middle" font-size="11">系统集成</text></g>';$('tech-network').innerHTML=markup;$('tech-network').style.width=zoom*100+'%';
 $$('[data-node]').forEach(b=>{const id=b.dataset.node;b.onclick=()=>selectTech(id);b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectTech(id)}};b.onmouseenter=()=>highlightNetwork(G.dependencyChain(id));b.onmouseleave=()=>highlightNetwork()});$$('[data-system]').forEach(b=>{b.onclick=()=>selectSystem(b.dataset.system);b.onkeydown=e=>{if(e.key==='Enter')selectSystem(b.dataset.system)}});const final=document.querySelector('[data-final]');if(final){final.onclick=beginFinal;final.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();beginFinal()}}};highlightNetwork();
}
function highlightNetwork(chain){if(!chain){if(selected?.type==='tech')chain=G.dependencyChain(selected.id);else if(selected?.type==='module'){chain=new Set();G.modules[selected.id].deps.forEach(id=>G.dependencyChain(id,chain))}}world?.highlightTech(chain);$$('.network-edge').forEach(e=>{const active=chain?.has(e.dataset.from)&&chain?.has(e.dataset.to);e.style.opacity=chain?active?'1':'.14':'1';e.style.stroke=active?'#ede1a7':''});$$('[data-node]').forEach(e=>{e.style.filter=chain?.has(e.dataset.node)?'drop-shadow(0 0 5px #e8d69088)':''})}
$('branch-filter').innerHTML='<option value="all">全部七大分支</option>'+G.branches.map((b,i)=>`<option value="${i}">${b.name}</option>`).join('');$('tech-search').oninput=renderNetwork;$('branch-filter').onchange=renderNetwork;$('ready-filter').onclick=()=>{readyOnly=!readyOnly;$('ready-filter').setAttribute('aria-pressed',String(readyOnly));renderNetwork()};$('tech-zoom-in').onclick=()=>{zoom=Math.min(2,zoom+.2);renderNetwork()};$('tech-zoom-out').onclick=()=>{zoom=Math.max(.7,zoom-.2);renderNetwork()};

function canBegin(q){if(!G.canSpend(state,q)){say(state.pendingEvent!==null?'先处理工坊来信。':state.phase==='ended'?'本轮已结束，可以带着记录重新启封。':'材料或时间暂时不够，到七座侧殿整备一下。');if(state.pendingEvent!==null)showEvent();return false}return true}
function openCraft(config){craft=config;if(world)world.suspended=true;$('craft-eyebrow').textContent=config.eyebrow;$('craft-name').textContent=config.name;$('craft-guide').textContent=config.guide;$('craft-modal').showModal();bench.start(config.mode,config.module,state.era);sound()}
function beginTrial(id,force){const q=G.quote(state,id,plan,force);if(!canBegin(q))return;const n=G.nodeById[id];if(!force&&G.missing(state,id).length)return say('先完成对应的前置。');const module=G.modules.find(m=>m.deps.some(d=>G.dependencyChain(d).has(id)))?.id??0;openCraft({type:'tech',id,force,plan,mode:n.craft,module,name:n.name,eyebrow:force?'跨越瓶颈 · 强行试制':'亲手试制 · '+G.branches[n.branch].hall,guide:({polish:'按住零件来回打磨，让粗糙的表面慢慢变得平整。',join:'从第一处接口开始，一处一处把构件扣合。',turn:'按住绕着零件画圈，让机关连续运转起来。',balance:'按住能量核心，光标经过中间亮区时会逐步稳定。',align:'按住并向右缓慢转动，直到环架与参考方向对齐。'})[n.craft]})}
function beginModule(id){if(!G.moduleReady(state,id))return;if(!canBegin({coins:12,months:2,crew:2}))return;const m=G.modules[id];openCraft({type:'module',id,mode:m.craft,module:id,name:m.name,eyebrow:'部件总装 · 从草图到实体',guide:'完成这段手作，部件将从后墙的构想中走下来。可随时使用辅助操作。'})}
function beginSystem(id){if(!G.systemReady(state,id))return;if(!canBegin({coins:5,months:1,crew:2}))return;const t=G.systems.find(t=>t.id===id);openCraft({type:'system',id,mode:t.craft,module:t.modules[t.modules.length-1],name:t.name+'验证',eyebrow:'独立验证 · 让部件彼此配合',guide:'让已经制成的部件在同一节奏里工作。完成操作即可通过本次抽象验证。'})}
function beginFinal(){if(!G.finalReady(state)){const t=G.systems.find(t=>!state.systems[t.id]);if(t){selectSystem(t.id);say('先完成对应部件与四项独立验证。')}return}if(!canBegin({coins:10,months:2,crew:2}))return;openCraft({type:'final',mode:'join',module:'final',name:'最后一次总装闭合',eyebrow:'巡天器 · 系统集成',guide:'按顺序闭合最后四处接口，让整座地宫见证这一次造物。'})}
function cancelCraft(){craft=null;if(world)world.suspended=false;bench.stop();$('craft-modal').close()}
$('craft-assist').onclick=()=>bench.assist();$('craft-modal').addEventListener('keydown',e=>{if(e.code==='Space'&&e.target!==$('craft-submit')){e.preventDefault();bench.assist()}});$('craft-modal').addEventListener('cancel',()=>{craft=null;bench.stop();if(world)world.suspended=false});
$('craft-submit').onclick=()=>{if(!craft||bench.progress<100)return;const c=craft,quality=bench.quality;let result;if(c.type==='tech')result=G.trial(state,c.id,c.plan,quality,c.force);else if(c.type==='module')result=G.buildModule(state,c.id,quality);else if(c.type==='system')result=G.validateSystem(state,c.id,quality);else result=G.finish(state,quality);if(!result.ok)return say(result.error||'这一步暂时无法执行。');cancelCraft();render();if(c.type==='module'){world?.reveal(c.id);say('纸上之形，今日有了重量。');sound('success')}else if(c.type==='final'){runFinale()}else if(result.type==='failure'||result.type==='partial'){say(result.text);sound('failure');if(result.bottleneck)selectTech(result.bottleneck)}else{say(c.type==='system'?'独立验证通过。':G.nodeById[c.id].name+'已经可以用于工程。');sound('success')}if(state.phase==='ended')showEnding();else if(state.pendingEvent!==null)showEvent();};

function showEvent(){if(state.pendingEvent===null)return;const e=G.events[state.pendingEvent];$('event-title').textContent=e.title;$('event-copy').textContent=e.copy;$('event-choices').innerHTML=e.choices.map((c,i)=>`<button class="event-option" data-choice="${i}">${c.name}<small>${c.note}</small></button>`).join('');$$('[data-choice]').forEach(b=>b.onclick=()=>{const r=G.chooseEvent(state,+b.dataset.choice);if(!r.ok)return say(r.error);$('event-modal').close();render();if(state.phase==='ended')showEnding()});if(!$('event-modal').open)$('event-modal').showModal()}
$('event-modal').addEventListener('cancel',e=>e.preventDefault());
function openLibrary(html){$('library-content').innerHTML=html;if(!$('library-modal').open)$('library-modal').showModal()}
function showHalls(){openLibrary(`<p class="eyebrow">七座侧殿 · 让能力成为体系</p><h2>工匠有余力，造物更从容。</h2><p class="muted">扩建是可选的。每级让对应分支省 12% 材料、可靠度提高 4 点。</p><div class="settings-row"><div>整备一季<small>国库 +28 · 工匠 +1 · 支持 +8 · 耗时 3 月</small></div><button id="rest-halls" class="primary">整备补给</button></div><div class="hall-grid">${G.branches.map((b,i)=>`<article class="hall-card"><p class="eyebrow">${b.name}</p><h3>${b.hall}</h3><p>${b.benefit}</p><p>当前：${['基础工坊','协作工坊','成熟工坊'][state.upgrades[i]||0]}</p><button class="secondary" data-upgrade="${i}" ${(state.upgrades[i]||0)>=2?'disabled':''}>${(state.upgrades[i]||0)>=2?'已经建成':'扩建 · 国库 '+(24+(state.upgrades[i]||0)*12)+' / 2 月'}</button></article>`).join('')}</div>`);$('rest-halls').onclick=()=>{const r=G.rest(state);if(!r.ok)return say(r.error);render();showHalls();say('材料入库，工匠也歇过一口气。');if(state.phase==='ended'){$('library-modal').close();showEnding()}};$$('[data-upgrade]').forEach(b=>b.onclick=()=>{const r=G.upgrade(state,+b.dataset.upgrade);if(!r.ok)return say(r.error);render();showHalls();sound('success');if(state.phase==='ended'){$('library-modal').close();showEnding()}})}
function showJournal(){const records=[...state.records].reverse();openLibrary(`<p class="eyebrow">工程档案 · 每一次试制都有来处</p><h2>让经验留下痕迹。</h2><p class="muted">本轮 ${state.attempts} 次试制 · ${state.failures} 次返工或失败 · ${state.legacy.length} 条跨局诊断</p>${records.map(r=>`<article class="journal-entry ${r.type==='failure'?'failure':''}"><small>工程第 ${r.month} 月 · ${esc(r.type==='failure'?'瓶颈记录':'工程记录')}</small><h3>${esc(r.title)}</h3><p>${esc(r.text)}</p></article>`).join('')}${state.legacy.length?'<h3>跨局保留的批注</h3>'+state.legacy.slice().reverse().map(r=>`<article class="journal-entry failure"><small>${G.eras[r.era]?.name||'前次工程'}</small><p>${esc(r.text)}</p></article>`).join(''):''}`)}
function settings(){openLibrary(`<p class="eyebrow">造物手册</p><h2>不必赶工，先动手。</h2><p>顺着左上角的下一步，亲手完成短操作，再看构件进入总装。科技穹顶始终完整可见；发呆与观察不消耗工程时间。</p><div class="settings-row"><div>声音<small>印玺、铜件与造物提示音</small></div><button id="pref-sound" class="secondary">${prefs.muted?'已关闭':'已开启'}</button></div><div class="settings-row"><div>简化画面<small>减少像素与实时阴影，适合较慢设备</small></div><button id="pref-quality" class="secondary">${prefs.simple?'已开启':'已关闭'}</button></div><div class="settings-row"><div>切换时代或重新启封<small>本轮进度会重置，失败批注与百工玩具存档保留</small></div><button id="pref-era" class="secondary">查看时代</button></div><p class="risk-note">架空工程体验。历史资料与游戏评分分别呈现；巡天器是非参数化的虚构造物。进度保存在当前浏览器与此网址。</p><div class="settings-row"><div>本地存档备份<small>可导出并在另一浏览器恢复本游戏工程</small></div><button id="export-save" class="secondary">导出存档</button></div><label class="settings-row">导入已有存档<input type="file" id="import-save" accept="application/json,.json" style="max-width:170px;font-size:10px"></label>`);$('pref-sound').onclick=()=>{prefs.muted=!prefs.muted;save();settings();render()};$('pref-quality').onclick=()=>{prefs.simple=!prefs.simple;world?.setQuality(prefs.simple);save();settings()};$('pref-era').onclick=()=>{$('library-modal').close();era=state.era;showEras()};$('export-save').onclick=()=>download('地宫-工程存档.json',JSON.stringify(state,null,2),'application/json');$('import-save').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1024*1024)return say('存档文件过大，请选择本游戏导出的文件。');let loaded;try{loaded=G.sanitize(JSON.parse(await file.text()))}catch{}if(!loaded)return say('无法识别这份存档。');confirmNew(()=>{state=loaded;era=state.era;save();$('library-modal').close();state.phase==='founding'?showFounding():showGame()})}}
function confirmNew(action){openLibrary('<p class="eyebrow">重新启封</p><h2>将这次经验留在墙上。</h2><p>继续后，当前工程会被新起点替换。跨局诊断与百工造物间的作品会保留。</p><div class="craft-controls"><button id="keep-current" class="secondary">保留当前工程</button><button id="confirm-new" class="primary">确认继续</button></div>');$('keep-current').onclick=()=>$('library-modal').close();$('confirm-new').onclick=()=>{$('library-modal').close();action()}}
$('side-halls').onclick=showHalls;$('journal').onclick=showJournal;$('settings').onclick=settings;$('sound').onclick=()=>{prefs.muted=!prefs.muted;save();render();if(!prefs.muted)sound()};$('era-menu').onclick=$('brand-menu').onclick=e=>{e?.preventDefault();era=state.era;showEras()};
$('toy-workshop').onclick=()=>{$('toy-frame').src=$('toy-frame').dataset.src;if(world)world.suspended=true;$('toy-modal').showModal()};function closeToy(){$('toy-modal').close();$('toy-frame').src='about:blank';if(world)world.suspended=false;try{const old=read('tiangong-workshop-v1',{}),n=G.claimWorkshop(state,old.completed||[]);if(n)say('百工手作已收录，获得 '+n*12+' 份材料。')}catch{}render()}
$('return-palace').onclick=closeToy;$('toy-modal').addEventListener('cancel',e=>{e.preventDefault();closeToy()});
function runFinale(){closePanel();setMode('overview');world?.finale?.();sound('success');say('七殿汇光，巡天之器，今日成形。');setTimeout(showEnding,reduced?400:4500)}
function showEnding(){const won=state.phase==='victory';$('ending-label').textContent=won?'整体试验通过 · '+state.ending:'本轮工程暂停 · 时代的边界';$('ending-title').innerHTML=won?'纸上之形，<br>今日有了重量。':'这一回，<br>经验先抵达了未来。';$('ending-stats').className='ending-stats';$('ending-stats').innerHTML=[['工程历时',state.months+' 月'],['本轮突破',state.breakthroughs.length+' 项'],['实体部件',Object.keys(state.modules).length+' / 8'],['工匠经验',state.failures+' 次']].map(([label,n])=>`<div><b>${n}</b><small>${label}</small></div>`).join('');$('ending-description').textContent=won?({原型成立:'第一次整体成功已经完成。继续重复验证，可以让工程不只成功一次。',工程可复制:'四个系统都经受了重复验证。这份手艺，已经可以留给后来的人。',时代跃迁:'成熟的侧殿与机器工厂，让一次造物成为一套可持续的工业能力。',代价过高:'造物已经成形，但支持或国库十分紧张。下一轮试试多整备、少强行试制。'})[state.ending]:'墙上的诊断记录会保留。换一个历史起点，或用更稳妥的安排再试一次。';$('replay-finale').hidden=!won;$('continue-build').textContent=won?'留在地宫':'重新选择时代';if(!$('ending-modal').open)$('ending-modal').showModal()}
$('continue-build').onclick=()=>{$('ending-modal').close();if(state.phase==='ended'){era=state.era;showEras()}};$('replay-finale').onclick=()=>{$('ending-modal').close();runFinale()};
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export-record').onclick=()=>{const e=G.eras[state.era],html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>地宫 · ${esc(state.ending)}</title><style>body{background:#0b2733;color:#e7dfbf;max-width:760px;padding:65px 40px;margin:auto;font:16px/2 serif}small{color:#a7bcb0}h1{font-size:42px}section{border-top:1px solid #e7dfbf44;padding:25px 0}b{color:#d6c38d}</style><small>地宫造物 · 地宫造物</small><h1>${esc(state.ending||'工程记录')}</h1><p>${e.name} · ${e.date}</p><section>工程历时 <b>${state.months} 月</b>　实体部件 <b>${Object.keys(state.modules).length}/8</b><br>本轮突破 <b>${state.breakthroughs.length} 项</b>　工艺返工 <b>${state.failures} 次</b><br>国库消耗 <b>${state.spent}</b>　支持 <b>${state.support}%</b></section><p>墙上的未来始终完整，现实中的未来由我一块块造出来。</p><small>架空工程体验 · 数值为游戏记录，不是史实结论或现实性能。</small></html>`;download('地宫-'+(state.ending||'工程记录')+'.html',html,'text/html;charset=utf-8')};
$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='craft-modal')cancelCraft();else $(b.dataset.close).close()});
document.addEventListener('visibilitychange',()=>{if(document.hidden){bench.down=false;save()}});window.addEventListener('beforeunload',save);
showEras();
