import {sanitizeCampaign} from './chronicle-data.mjs';
import {sanitizeWork} from './atelier-data.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
export function repository(db,owner){return {
 list:()=>db.prepare('SELECT key, value, revision, updated FROM tiangong_records WHERE owner = ? ORDER BY updated DESC LIMIT 260').bind(owner).all(),
 put:async(key,value,revision)=>{const now=Date.now(),data=JSON.stringify(value);if(revision===0)return db.prepare('INSERT INTO tiangong_records (owner, key, value, revision, updated) SELECT ?, ?, ?, 1, ? WHERE (SELECT count(*) FROM tiangong_records WHERE owner = ?) < 260 ON CONFLICT (owner, key) DO NOTHING RETURNING revision, updated').bind(owner,key,data,now,owner).first();return db.prepare('UPDATE tiangong_records SET value = ?, revision = revision + 1, updated = ? WHERE owner = ? AND key = ? AND revision = ? RETURNING revision, updated').bind(data,now,owner,key,revision).first()},
 remove:(key,revision)=>db.prepare('DELETE FROM tiangong_records WHERE owner = ? AND key = ? AND revision = ? RETURNING key').bind(owner,key,revision).first()
}}
export async function api(request,env){const url=new URL(request.url);if(url.pathname!=='/api/records')return json({error:'not_found'},404);const owner=request.headers.get('oai-authenticated-user-id');if(!owner)return json({error:'sign_in_required'},401);if(!env.DB)return json({error:'storage_unavailable'},503);const repo=repository(env.DB,owner);if(request.method==='GET'){const rows=await repo.list();return json({scope:owner,records:rows.results.map(r=>({...r,value:JSON.parse(r.value)}))})}
 if(!['PUT','DELETE'].includes(request.method))return json({error:'method_not_allowed'},405);const origin=request.headers.get('Origin');if(origin&&origin!==url.origin||request.headers.get('Sec-Fetch-Site')==='cross-site')return json({error:'origin_mismatch'},403);if(!request.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'json_required'},415);if(Number(request.headers.get('Content-Length'))>65536)return json({error:'too_large'},413);const body=await request.text();if(body.length>65536)return json({error:'too_large'},413);let input;try{input=JSON.parse(body)}catch{return json({error:'invalid_json'},400)}if(!input||typeof input.key!=='string'||!/^((campaign-[0-3])|draft|(work-[a-zA-Z0-9-]{1,90}))$/.test(input.key)||!Number.isSafeInteger(input.revision)||input.revision<0)return json({error:'invalid_record'},400);
 if(request.method==='DELETE'){if(!input.key.startsWith('work-'))return json({error:'invalid_record'},400);const deleted=await repo.remove(input.key,input.revision);return deleted?json({deleted:true}):json({error:'conflict'},409)}let value;try{value=input.key.startsWith('campaign-')?sanitizeCampaign(input.value):sanitizeWork(input.value)}catch{return json({error:'invalid_value'},400)}if(!value||input.key.startsWith('work-')&&!value.nodes.length||input.key.startsWith('campaign-')&&Number(input.key.slice(-1))!==value.era)return json({error:'invalid_value'},400);const saved=await repo.put(input.key,value,input.revision);return saved?json(saved):json({error:'conflict_or_capacity'},409)
}
export default {async fetch(request,env){try{if(new URL(request.url).pathname.startsWith('/api/'))return await api(request,env);return await env.ASSETS.fetch(request)}catch{return json({error:'temporarily_unavailable'},503)}}};
