(function(){
'use strict';
const {parts,projects,techs,fresh,sanitize,evaluate,network,unlock}=Tiangong;
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const KEY='tiangong-workshop-v1';let state;try{state=sanitize(JSON.parse(localStorage.getItem(KEY)))}catch{state=fresh()}
let selected=null,view='bench',running=false,startTime=0,resultTimer=0,toastTimer=0,history=[],craft=null,drag=null,freeDrag=null,hover=null,particles=[],lastBell=-1,audioContext=null,lastSound=0;
const canvas=$('scene'),ctx=canvas.getContext('2d'),craftCanvas=$('craft-canvas'),cc=craftCanvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saved-label').textContent='进度自动记下'}catch{$('saved-label').textContent='当前浏览器无法保存'}}
function say(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600)}
function sound(type='wood'){if(state.muted)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime;if(now-lastSound<.045)return;lastSound=now;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type==='bell'?'sine':'triangle';o.frequency.setValueAtTime(type==='bell'?880:type==='win'?660:type==='sand'?170:240,now);o.frequency.exponentialRampToValueAtTime(type==='bell'?700:type==='win'?990:75,now+.15);g.gain.setValueAtTime(type==='sand'?.018:.065,now);g.gain.exponentialRampToValueAtTime(.001,now+(type==='bell'?.9:.24));o.connect(g);g.connect(audioContext.destination);o.start();o.stop(now+1)}catch{}}
function circle(c,x,y,r,fill,stroke){c.beginPath();c.arc(x,y,r,0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.stroke()}}
function line(c,x1,y1,x2,y2,color='#816344',width=4){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.lineWidth=width;c.strokeStyle=color;c.lineCap='round';c.stroke()}
function poly(c,points,fill,stroke){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=1.3;c.stroke()}}
function wood(c,x,y,w,h,depth=10){poly(c,[[x,y],[x+w,y],[x+w+depth,y-depth],[x+depth,y-depth]],'#d4ad75','#8c7048');poly(c,[[x+w,y],[x+w+depth,y-depth],[x+w+depth,y+h-depth],[x+w,y+h]],'#8f603c','#805b37');c.fillStyle='#b9864e';c.fillRect(x,y,w,h);c.strokeStyle='#936939';c.lineWidth=1;c.strokeRect(x,y,w,h);for(let i=0;i<3;i++)line(c,x+7,y+5+i*h/4,x+w-6,y+5+i*h/4,'#c69a62',.7)}
function drawPart(c,id,x,y,scale=1,angle=0,opacity=1){c.save();c.translate(x,y);c.scale(scale,scale);c.globalAlpha*=opacity;const kind=parts[id].kind;let r=55*(parts[id].size||1);
if(kind==='wheel'||kind==='gear'||kind==='waterwheel'||kind==='cam'){
 c.rotate(angle);if(kind==='gear'){r=59;const points=[];for(let i=0;i<48;i++){const a=i*Math.PI/24,rr=i%4<2?65:54;points.push([Math.cos(a)*rr,Math.sin(a)*rr])}poly(c,points,'#bb955c','#7a603c')}
 if(kind==='waterwheel')r=99;if(kind==='cam')r=39;
 const off=kind==='cam'?14:0;circle(c,4+off,5,r,'#7f5838','#6e5437');circle(c,off,0,r,kind==='gear'?'#be9659':'#bb874f','#80603b');circle(c,off,0,r-7,null,'#d8b582');circle(c,off,0,r-14,null,'#98723f');
 if(kind==='waterwheel'){circle(c,0,0,r-18,'#e1dec9','#8c6e41');for(let i=0;i<10;i++){c.save();c.rotate(i*Math.PI/5);wood(c,-5,0,10,90,3);wood(c,-20,79,40,13,5);c.restore()}}
 else if(kind==='wheel'||kind==='gear'){for(let i=0;i<6;i++){c.save();c.rotate(i*Math.PI/3);line(c,0,0,r-18,0,'#e0ba80',7);line(c,0,1,r-18,1,'#976d3e',1);c.restore()}}
 circle(c,0,0,14,'#d0a86f','#87673d');circle(c,0,0,5,'#344b43','#d3bd86');
}else if(kind==='body'){wood(c,-145,-10,290,46,35);for(let i=0;i<4;i++)line(c,-125+i*65,-35,-145+i*65,-10,'#b18a58',2);wood(c,-125,-20,13,35,26);wood(c,103,-20,13,35,26)}
else if(kind==='axle'){wood(c,-139,-7,278,17,7);circle(c,-139,2,9,'#d1ad73','#936c42');circle(c,143,-3,9,'#d1ad73','#936c42')}
else if(kind==='support'){wood(c,-100,76,212,18,20);wood(c,-88,-93,19,171,13);wood(c,73,-93,19,171,13);wood(c,-99,-94,192,17,15);line(c,-80,70,64,-79,'#926638',9)}
else if(kind==='crank'){c.rotate(angle);circle(c,0,0,18,'#b98d48','#7c663d');line(c,0,0,49,-25,'#be9a5a',13);circle(c,50,-25,11,'#3d6055','#223e39');wood(c,47,-58,11,35,4)}
else if(kind==='bucket'){poly(c,[[-27,-20],[27,-20],[20,26],[-20,26]],'#a97740','#78542f');poly(c,[[-27,-20],[0,-29],[27,-20],[0,-10]],'#6e5437','#c79e65');for(let i=-12;i<20;i+=11)line(c,i,-7,i,20,'#d0a76a',1);line(c,-24,-1,24,-1,'#4b6655',3);line(c,-21,18,21,18,'#4b6655',3);c.strokeStyle='#bea66c';c.lineWidth=3;c.beginPath();c.arc(0,-15,25,Math.PI,0);c.stroke()}
else if(kind==='striker'){c.rotate(angle);wood(c,-80,-5,130,11,4);wood(c,43,-24,24,46,8)}
else if(kind==='bell'){c.rotate(angle);const g=c.createLinearGradient(-40,0,40,0);g.addColorStop(0,'#8d722f');g.addColorStop(.5,'#debf69');g.addColorStop(1,'#aa8837');circle(c,0,-40,9,null,'#9d8237');c.beginPath();c.moveTo(-10,-40);c.bezierCurveTo(-42,-32,-20,3,-44,21);c.quadraticCurveTo(0,39,44,21);c.bezierCurveTo(20,3,42,-32,10,-40);c.closePath();c.fillStyle=g;c.fill();c.strokeStyle='#8f7738';c.lineWidth=2;c.stroke();c.beginPath();c.ellipse(0,23,43,10,0,0,7);c.fillStyle='#907438';c.fill();circle(c,0,25,8,'#d7b361');line(c,-29,10,29,10,'#eedda0',2)}
c.restore();}
function fit(c,el,w,h){const ratio=Math.min(devicePixelRatio||1,2),r=el.getBoundingClientRect();if(!r.width||!r.height)return;const pw=Math.round(r.width*ratio),ph=Math.round(r.height*ratio);if(el.width!==pw||el.height!==ph){el.width=pw;el.height=ph}c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,pw,ph);const s=Math.min(pw/w,ph/h);c.setTransform(s,0,0,s,(pw-w*s)/2,(ph-h*s)/2);return s;}
function worldPoint(e,el,w=1000,h=560){const r=el.getBoundingClientRect(),s=Math.min(r.width/w,r.height/h);return{x:(e.clientX-r.left-(r.width-w*s)/2)/s,y:(e.clientY-r.top-(r.height-h*s)/2)/s};}
function background(c){c.fillStyle='#e7eadf';c.fillRect(-300,-300,1600,1200);c.strokeStyle='#d5dccc';c.lineWidth=.65;for(let x=0;x<1100;x+=40){line(c,x,120,x,470,'#d5dccc',.65)}for(let y=140;y<480;y+=35)line(c,35,y,970,y,'#d5dccc',.65);
 c.save();c.shadowColor='#30452c24';c.shadowBlur=20;c.shadowOffsetY=18;poly(c,[[140,210],[772,210],[950,431],[28,431]],'#d5c3a2');c.restore();poly(c,[[28,431],[950,431],[950,443],[28,443]],'#ad9471');poly(c,[[140,210],[772,210],[950,431],[28,431]],'#d9c8aa','#b7a27e');for(let i=0;i<12;i++){const y=225+i*17;line(c,140-(y-210)*.5,y,772+(y-210)*.8,y,'#cabb9c',.9)}
 poly(c,[[206,228],[726,228],[839,407],[108,407]],'#82917c','#72836d');for(let i=0;i<10;i++)line(c,160+i*66,248,130+i*69,390,'#9aa68f',.5);for(let i=0;i<7;i++)line(c,184-i*9,250+i*22,738+i*13,250+i*22,'#9aa68f',.5);
 // working rulers and tools on the bench
 c.save();c.translate(160,375);c.rotate(-.2);wood(c,-73,-7,135,12,3);for(let i=0;i<24;i++)line(c,-65+i*5,-6,-65+i*5,i%5===0?3:-1,'#826e46',1);c.restore();c.save();c.translate(819,359);c.rotate(.45);wood(c,-5,-38,11,83,4);wood(c,-23,-45,48,18,5);c.restore();
 c.font='10px Georgia';c.fillStyle='#bcc3ad';c.fillText('TIANGONG  /  WORKBENCH',375,470);
}
function ghost(c,slot){c.save();const target=selected&&parts[selected].kind===slot.kind;c.strokeStyle=target?'#f0d08d':'#c2cbb2';c.fillStyle=target?'#ead7a326':'#b5c1a114';c.lineWidth=1.6;c.setLineDash([5,5]);c.beginPath();c.ellipse(slot.x,slot.y,slot.kind==='body'?151:slot.kind==='axle'?135:slot.kind==='support'?75:slot.kind==='waterwheel'?88:44,slot.kind==='body'?36:slot.kind==='axle'?16:slot.kind==='support'?90:slot.kind==='waterwheel'?88:44,0,0,7);c.fill();c.stroke();c.setLineDash([]);c.font='13px Microsoft YaHei';c.textAlign='center';c.fillStyle=target?'#fff1c6':'#e0e4d5';c.fillText('+ '+slot.name,slot.x,slot.y+5);c.restore()}
function drawMachine(c,id,assembly,t=0,preview=false){const p=projects[id];let dx=0,dy=0,tilt=0;const active=running&&!preview;
 if(id==='car'&&active){const wobble=evaluate(id,assembly).type==='wobble';dx=Math.sin(t*.85)*95;dy=wobble?Math.sin(t*3)*10:0;tilt=wobble?Math.sin(t*3)*.08:0;c.save();c.translate(490+dx,320+dy);c.rotate(tilt);c.translate(-490,-320)}else c.save();
 c.save();c.globalAlpha=.18;c.fillStyle='#243927';c.beginPath();c.ellipse(id==='water'?495:500,405,id==='car'?178:170,23,0,0,7);c.fill();c.restore();
 if(id==='car'&&assembly.body){drawPart(c,'wheel',429,309,.72,active?t*3:0,.34);drawPart(c,'wheel',629,309,.72,active?t*3:0,.34)}
 for(const slot of p.slots){const part=assembly[slot.id];if(!part){if(!preview)ghost(c,slot);continue}let x=slot.x,y=slot.y,angle=0,scale=1;
 if(active){if(['wheel','gear','waterwheel','crank'].includes(parts[part].kind))angle=t*(id==='water'?.8:2.5);if(parts[part].kind==='cam')angle=-t*2.5;if(parts[part].kind==='striker')angle=-Math.max(0,Math.sin(t*2.5))*.3;if(parts[part].kind==='bell')angle=Math.sin(t*16)*Math.max(0,Math.cos(t*2.5))*.045;if(part==='bucket'){x=450+Math.cos(-t*.8-2.3)*94;y=290+Math.sin(-t*.8-2.3)*94;scale=.68}}
 if(part==='crank')scale=.8;if(part==='gear')scale=1.04;drawPart(c,part,x,y,scale,angle);
 }
 if(id==='water'){wood(c,580,177,164,12,13);line(c,615,190,615,380,'#a48754',7);c.fillStyle='#678f8a';c.beginPath();c.ellipse(455,417,122,13,0,0,7);c.fill();if(active){for(let i=0;i<12;i++){const phase=(t*1.1+i/12)%1;circle(c,584+Math.sin(phase*14+i)*9,182+phase*213,2.7,'#81bac1')}c.fillStyle='#8fbdb4';c.fillRect(670,172,Math.min(t*8,72),5)}}
 if(id==='bell'&&active&&Math.cos(t*2.5)>.85){for(let i=0;i<3;i++){c.beginPath();c.arc(655,247,50+i*10,-.7,.5);c.strokeStyle='#bea258';c.lineWidth=1.5;c.stroke()}}
 c.restore();}
function drawFree(c,t){const power=network(state.free);for(const a of state.free)for(const b of state.free)if(a.id<b.id&&Math.hypot(a.x-b.x,a.y-b.y)<=150){line(c,a.x,a.y,b.x,b.y,running&&power.has(a.id)?'#ecd78c':'#a7b299',3);if(running&&power.has(a.id)){const f=(t*.5)%1;circle(c,a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f,4,'#fff0ad')}}
 for(const p of state.free){const on=running&&power.has(p.id),kind=parts[p.part].kind;const angle=on?(['wheel','gear','waterwheel','crank','cam'].includes(kind)?t*2*(p.id%2?1:-1):['striker','bell'].includes(kind)?Math.sin(t*5)*.15:0):0;drawPart(c,p.part,p.x,p.y,.65,angle);if(hover?.id===p.id){circle(c,p.x,p.y,46,null,'#ead494')}}
 if(!state.free.length){c.fillStyle='#e0e7d4';c.font='17px SimSun';c.textAlign='center';c.fillText('把零件放在这里，看看会发生什么',490,320);c.textAlign='left'}}
function sparkle(x,y,count=15){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*2.5,vy:-Math.random()*2-1,life:1,color:i%2?'#d9b777':'#fff2c4'})}
function frame(now){if(view==='bench'&&!document.hidden){fit(ctx,canvas,1000,560);background(ctx);const t=running?(now-startTime)/1000:0;if(state.project==='free')drawFree(ctx,t);else drawMachine(ctx,state.project,state.assemblies[state.project],t);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.06;p.life-=.02;ctx.globalAlpha=Math.max(p.life,0);circle(ctx,p.x,p.y,2,p.color)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);if(running&&(state.project==='bell'||state.project==='free'&&state.free.some(p=>p.part==='bell'&&network(state.free).has(p.id)))){const tick=Math.floor(t*2.5/(Math.PI*2));if(tick!==lastBell){lastBell=tick;sound('bell')}}}if(craft&&$('craft-dialog').open)drawCraft(now);requestAnimationFrame(frame)}
function refresh(){const p=projects[state.project],a=state.assemblies[state.project]||{};save();$('project-title').textContent=p.title;$('project-tag').textContent=p.tag;$('scene-number').textContent='造物 · '+({car:'001',water:'002',bell:'003',free:'自由'}[state.project]);$('tech-count').textContent=state.tech.length+'/9';$('assembly-count').textContent=state.project==='free'?state.free.length+' / 18 件':`已装 ${Object.keys(a).length} / ${p.slots.length} 件`;$('free-caption').textContent=state.completed.length===3?'所有零件，随你拼':'完成三件造物后开启';
 $$('[data-project]').forEach(b=>{b.classList.toggle('active',b.dataset.project===state.project);b.setAttribute('aria-pressed',b.dataset.project===state.project);if(b.querySelector('i'))b.querySelector('i').textContent=state.completed.includes(b.dataset.project)?'✓':''});
 $('parts-tray').innerHTML=p.parts.map(id=>`<button class="part-card ${selected===id?'selected':''}" data-part="${id}" aria-label="拿取${parts[id].name}" aria-pressed="${selected===id}"><span class="part-status">${parts[id].craft?(state.crafted.includes(id)?'已会做':'手作'):''}</span><canvas width="180" height="128" aria-hidden="true"></canvas><strong>${parts[id].name}</strong><small>${parts[id].craft&&!state.crafted.includes(id)?'先亲手加工':'拿取 · 放上桌'}</small></button>`).join('');
 $$('.part-card').forEach(b=>{const c=b.querySelector('canvas').getContext('2d');c.translate(90,65);const id=b.dataset.part;drawPart(c,id,0,0,['body','axle','support','waterwheel'].includes(id)?.5:.75);b.addEventListener('click',()=>selectPart(id));b.addEventListener('pointerdown',e=>startDrag(e,id,b))});
 if(state.project==='free'){$('slot-list').innerHTML='<button class="slot-button" id="free-place">＋ 放到空位</button><button class="slot-button" id="free-last">− 取下最后一件</button>';$('free-place').onclick=()=>{if(!selected)return say('先从零件匣里拿一件。');const i=state.free.length;place(selected,{x:230+i%5*130,y:240+Math.floor(i/5)*70})};$('free-last').onclick=()=>{if(!state.free.length)return;remember();stop();state.free.pop();refresh()}}
 else{$('slot-list').innerHTML=p.slots.map(s=>`<button class="slot-button ${a[s.id]?'filled':''} ${selected&&parts[selected].kind===s.kind?'target':''}" data-slot="${s.id}">${a[s.id]?'✓':'＋'} ${s.name}</button>`).join('');$$('[data-slot]').forEach(b=>b.onclick=()=>slotAction(b.dataset.slot))}
 const n=Object.keys(a).length,done=n===p.slots.length&&n>0;for(const id of ['craft','build','run'])$('step-'+id).classList.remove('active','done');$('step-'+(running||done?'run':n||selected?'build':'craft')).classList.add('active');if(n)$('step-craft').classList.add('done');if(done)$('step-build').classList.add('done');
 $('scene-hint').textContent=running?'装置正在运转 · 再拉一次把手可停下':selected?`拿着「${parts[selected].name}」 · 放到${state.project==='free'?'桌面任意位置':'亮起的装配位置'}`:state.project==='free'?'邻近的零件会相连 · 点击已放置的零件可取下':done?'拼好了！拉动把手，看看它会怎样动':'① 从下方拿一件零件，开始造物';
 $('discovery-hint').textContent=({car:'两只轮子如果不一样大，小车会怎样走？',water:'把水提起来，靠的是水斗和转动一起配合。',bell:'一直转圈的齿轮，怎样让木槌反复敲打？',free:'靠近会连接，分开会断开。试试混搭三种造物的零件。'})[state.project];$('sound-toggle').textContent=state.muted?'♪':'♫';$('sound-toggle').setAttribute('aria-label',state.muted?'开启声音':'关闭声音');$('undo-button').disabled=!history.length;
}
function stop(){running=false;clearTimeout(resultTimer);$('run-button').classList.remove('running');$('run-label').textContent='拉动把手';lastBell=-1}
function remember(){history.push(JSON.stringify({assemblies:state.assemblies,free:state.free}));if(history.length>30)history.shift()}
function changeProject(id){if(id==='free'&&state.completed.length<3){say(`再完成 ${3-state.completed.length} 件造物，自由工作台就开放。`);return}stop();state.project=id;selected=null;history=[];$('guide-copy').textContent=projects[id].prompt;refresh();switchView('bench')}
function selectPart(id){stop();if(parts[id].craft&&!state.crafted.includes(id)){beginCraft(id);return}selected=selected===id?null:id;$('guide-copy').textContent=selected?`拿好了${parts[id].name}。${state.project==='free'?'放到桌面上，靠近别的零件就能接起来。':'放到虚线位置，也可以点右边的位置按钮。'}`:projects[state.project].prompt;sound();refresh()}
function slotAction(id){const slot=projects[state.project].slots.find(s=>s.id===id);if(selected){if(parts[selected].kind!==slot.kind)return say('这件零件不适合这里。试试亮起的位置。');place(selected,slot)}else if(state.assemblies[state.project][id]){remember();stop();const p=state.assemblies[state.project][id];delete state.assemblies[state.project][id];selected=p;refresh();say('取下了'+parts[p].name+'，可以换个位置。')}else say('先从下方零件匣拿取'+slot.name+'。')}
function place(id,pos){stop();if(state.project==='free'){if(state.free.length>=18)return say('桌面放满啦，先取下一件再继续。');remember();state.free.push({id:Math.max(0,...state.free.map(p=>p.id))+1,part:id,x:Math.max(110,Math.min(840,pos.x)),y:Math.max(150,Math.min(430,pos.y))})}else{const s=pos.id?pos:projects[state.project].slots.filter(s=>s.kind===parts[id].kind).sort((a,b)=>Math.hypot(a.x-pos.x,a.y-pos.y)-Math.hypot(b.x-pos.x,b.y-pos.y))[0];if(!s||(!pos.id&&Math.hypot(s.x-pos.x,s.y-pos.y)>135))return say('再靠近亮起的虚线位置一点。');remember();state.assemblies[state.project][s.id]=id;pos=s}selected=null;sparkle(pos.x,pos.y,10);sound();refresh();const a=state.assemblies[state.project];$('guide-copy').textContent=state.project==='free'?'拼上了。继续加零件，或拉动把手试试看。':Object.keys(a).length===projects[state.project].slots.length?'全部拼好了！拉动把手，让它动起来。':'咔哒，装好了。再拿一件，继续拼。'}
function startDrag(e,id,button){if(e.button!==0)return;drag={id,x:e.clientX,y:e.clientY,button,moved:false};if(e.pointerType==='mouse')button.setPointerCapture(e.pointerId)}
window.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<9)return;drag.moved=true;if(!drag.proxy){const p=document.createElement('canvas');p.className='drag-proxy';p.width=180;p.height=180;drawPart(p.getContext('2d'),drag.id,90,90,['body','axle','support','waterwheel'].includes(drag.id)?.45:.7);document.body.append(p);drag.proxy=p}drag.proxy.style.left=(e.clientX-45)+'px';drag.proxy.style.top=(e.clientY-45)+'px'});
window.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;d.proxy?.remove();if(!d.moved)return;const r=canvas.getBoundingClientRect();d.button.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true,once:true});if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;if(parts[d.id].craft&&!state.crafted.includes(d.id)){beginCraft(d.id);return}selected=d.id;place(d.id,worldPoint(e,canvas))});
window.addEventListener('pointercancel',()=>{drag?.proxy?.remove();drag=null;freeDrag=null});
canvas.addEventListener('pointerdown',e=>{if(running){say('先停下装置，就可以继续拼。');return}const p=worldPoint(e,canvas);if(selected){place(selected,p);return}if(state.project==='free'){const hit=[...state.free].reverse().find(n=>Math.hypot(n.x-p.x,n.y-p.y)<55);if(hit){freeDrag={hit,original:{x:hit.x,y:hit.y},start:p,moved:false};remember();canvas.setPointerCapture(e.pointerId)}}else{const hit=[...projects[state.project].slots].reverse().find(s=>Math.hypot(s.x-p.x,s.y-p.y)<65);if(hit)slotAction(hit.id)}});
canvas.addEventListener('pointermove',e=>{const p=worldPoint(e,canvas);if(freeDrag){if(Math.hypot(p.x-freeDrag.start.x,p.y-freeDrag.start.y)>8)freeDrag.moved=true;if(freeDrag.moved){freeDrag.hit.x=Math.max(110,Math.min(840,p.x));freeDrag.hit.y=Math.max(150,Math.min(430,p.y))}}hover=state.project==='free'?state.free.find(n=>Math.hypot(n.x-p.x,n.y-p.y)<55):null});
canvas.addEventListener('pointerup',()=>{if(!freeDrag)return;if(!freeDrag.moved){selected=freeDrag.hit.part;state.free=state.free.filter(n=>n.id!==freeDrag.hit.id)}freeDrag=null;refresh()});
function run(){if(running){stop();refresh();return}if(state.project==='free'){if(!state.free.length)return say('先放一件零件，再拉把手。');const power=network(state.free);$('guide-copy').textContent=`${power.size} 件零件开始接力了。${power.size<state.free.length?'有零件离得太远，靠近一点再试。':'再加点不一样的零件，会发生什么？'}`;if(power.size>=4&&new Set(state.free.filter(p=>power.has(p.id)).map(p=>p.part)).size>=3&&!state.discoveries.includes('mixed')){state.discoveries.push('mixed');say('发现新造物：百工大合奏 ✧');sound('win')}}else{const result=evaluate(state.project,state.assemblies[state.project]);if(!result.ok){say(result.message);$('guide-copy').textContent=result.message;return}$('guide-copy').textContent=result.message;if(result.type==='wobble'){if(!state.discoveries.includes('wobble'))state.discoveries.push('wobble');say('意外发现：不走寻常路的小木车 ✧')}const first=!state.completed.includes(state.project);unlock(state,state.project);if(first){const id=state.project;resultTimer=setTimeout(()=>showResult(id,result),4300)}else say(result.message)}running=true;startTime=performance.now();lastBell=-1;sound();$('run-button').classList.add('running');$('run-label').textContent='停下来看看';refresh()}
function showResult(id,result){if(id!==state.project||!running)return;const p=projects[id];$('result-eyebrow').textContent='第 '+state.completed.length+' 件造物，记下了';$('result-title').textContent=({car:result.type==='wobble'?'它拐着弯跑起来了！':'它真的跑起来了！',water:'水真的往高处走了！',bell:'听，你做的铃响了！'})[id];$('result-copy').textContent=p.note;$('result-tech').innerHTML=p.tech.map(id=>'<span>✧ '+techs.find(t=>t.id===id).name+'</span>').join('');$('result-next').textContent=p.next==='free'?(state.completed.length===3?'去自由拼搭 →':'继续完成造物 →'):'去做下一件 →';$('result-dialog').showModal();sound('win');for(let i=0;i<5;i++)sparkle(300+i*100,220,16)}
function switchView(id){if(id!=='bench')stop();view=id;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id+'-view'));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='atlas')renderAtlas();if(id==='collection')renderCollection();if(id==='bench')refresh();}
function renderAtlas(){const edges=[[0,1],[1,2],[0,3],[1,4],[3,4],[4,5],[3,6],[4,7],[6,7],[7,8]];$('atlas').innerHTML=edges.map(([a,b])=>`<path d="M${techs[a].x},${techs[a].y} L${techs[b].x},${techs[b].y}" stroke="${state.tech.includes(techs[a].id)&&state.tech.includes(techs[b].id)?'#9fae80':'#cbd2bd'}" stroke-width="2" fill="none"/>`).join('')+techs.map((t,i)=>{const on=state.tech.includes(t.id);return `<g class="atlas-node" role="button" tabindex="0" data-tech="${t.id}" aria-label="${t.name}，${on?'已掌握':'待发现'}"><circle cx="${t.x}" cy="${t.y}" r="34" fill="${on?'#385c48':'#e9eddf'}" stroke="${on?'#c1a663':'#b9c4a7'}" stroke-width="2"/><text x="${t.x}" y="${t.y+6}" fill="${on?'#f5deb2':'#a4af94'}" font-size="18" text-anchor="middle">${on?'✧':String(i+1).padStart(2,'0')}</text><text x="${t.x}" y="${t.y+59}" fill="${on?'#486043':'#87977c'}" font-size="17" text-anchor="middle">${t.name}</text></g>`}).join('');$$('[data-tech]').forEach(b=>{const activate=()=>{const t=techs.find(t=>t.id===b.dataset.tech),on=state.tech.includes(t.id),p=Object.entries(projects).find(([id,p])=>p.tech.includes(t.id));$('atlas-detail').innerHTML=`<span class="eyebrow">${on?'已亲手掌握':'下一份好奇'}</span><h2>${t.name}</h2><p>${t.text}</p><p>在「${p[1].short}」中${on?'发现了它':'试试看'}。</p><button class="plain-button" id="atlas-go">去工作台 →</button>`;$('atlas-go').onclick=()=>changeProject(p[0])};b.onclick=activate;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}})}
function renderCollection(){$('collection-grid').innerHTML=['car','water','bell'].map(id=>{const p=projects[id],done=state.completed.includes(id);return `<article class="collection-card"><canvas width="700" height="420" data-display="${id}" aria-label="${p.short}${done?'已完成':'待完成'}"></canvas><p class="eyebrow">${done?'已收藏 · 亲手造物':'等待第一件作品'}</p><h2>${p.title}</h2><p>${done?p.note:'这里留给你亲手完成的'+p.short+'。'}</p><button class="plain-button" data-return="${id}">${done?'拿出来再玩':'去做这一件'} ↗</button></article>`}).join('');$$('[data-display]').forEach(el=>{const c=el.getContext('2d');c.translate(-40,-25);c.scale(.75,.75);const p=projects[el.dataset.display],assembly=state.completed.includes(el.dataset.display)?state.assemblies[el.dataset.display]:{};if(!state.completed.includes(el.dataset.display)){c.globalAlpha=.25;for(const s of p.slots){const id=p.parts.find(id=>parts[id].kind===s.kind);assembly[s.id]=id}}drawMachine(c,el.dataset.display,assembly,0,true)});$$('[data-return]').forEach(b=>b.onclick=()=>changeProject(b.dataset.return));$('discoveries').textContent=state.discoveries.length?'意外发明簿　'+state.discoveries.map(x=>x==='wobble'?'✧ 不走寻常路的小木车':'✧ 百工大合奏').join('　 /　 '):'意外发明簿还是空的。试试那些看起来“不太对”的组合。'}
// Four short craft interactions. Pointer movement affects the material; keyboard is an equivalent accessible route.
const craftInfo={sand:['把木轮磨圆','按住木轮来回打磨，让粗糙的轮廓慢慢变圆。','按住木轮并来回移动'],hammer:['轻敲，固定好','点亮起的木钉，把它一下一下敲进木料。','点击亮起的木钉'],align:['把接口对齐','按住零件绕中心转，让两条红线重合。','绕着圆心转动'],wrap:['把绳索缠好','按住绳头，绕着水斗画圈，把绳索缠牢。','围着水斗转两圈']};
function beginCraft(id){stop();const type=parts[id].craft;craft={id,type,progress:0,angle:-1.3,total:0,down:false,last:null,pegs:[0,0,0,0],dust:[],tool:{x:480,y:200},ready:false};const info=craftInfo[type];$('craft-title').textContent=info[0];$('craft-instruction').textContent=info[1];$('craft-action-hint').textContent=info[2];$('craft-progress').value=0;$('craft-percent').textContent='0%';$('craft-done').disabled=true;$('craft-done').textContent='继续加工';$('craft-dialog').showModal();}
function progress(value){if(!craft||craft.ready)return;craft.progress=Math.min(100,value);$('craft-progress').value=craft.progress;$('craft-percent').textContent=Math.round(craft.progress)+'%';if(craft.progress>=100){craft.ready=true;$('craft-done').disabled=false;$('craft-done').textContent='做好了，拿去拼装 →';$('craft-action-hint').textContent='这件零件，现在是你亲手做的了。';sound('win')}}
function dust(x,y){for(let i=0;i<4;i++)craft.dust.push({x,y,vx:(Math.random()-.5)*4,vy:Math.random()*2,life:1})}
function craftInput(p,click=false){if(!craft||craft.ready)return;const d=Math.hypot(p.x-350,p.y-165);craft.tool=p;if(craft.type==='sand'){if(d<130&&craft.last){const delta=Math.hypot(p.x-craft.last.x,p.y-craft.last.y);if(delta>2){progress(craft.progress+Math.min(delta*.065,3.2));dust(p.x,p.y);sound('sand')}}}
else if(craft.type==='hammer'&&click){const i=craft.pegs.findIndex(v=>v<2),x=245+i*70;if(Math.hypot(p.x-x,p.y-165)<43){craft.pegs[i]++;progress(craft.pegs.reduce((a,b)=>a+b,0)*12.5);dust(x,165);sound()}}
else if(craft.type==='align'&&craft.last&&d>35&&d<150){let delta=Math.atan2(p.y-165,p.x-350)-Math.atan2(craft.last.y-165,craft.last.x-350);delta=Math.atan2(Math.sin(delta),Math.cos(delta));craft.angle+=delta;const error=Math.abs(Math.atan2(Math.sin(craft.angle),Math.cos(craft.angle)));progress(error<.1?100:Math.max(0,100-error/1.3*100));sound('sand')}
else if(craft.type==='wrap'&&craft.last&&d>35&&d<170){let delta=Math.atan2(p.y-165,p.x-350)-Math.atan2(craft.last.y-165,craft.last.x-350);delta=Math.abs(Math.atan2(Math.sin(delta),Math.cos(delta)));if(delta<.5){craft.total+=delta;progress(craft.total/(Math.PI*4)*100);sound('sand')}}craft.last=p;}
craftCanvas.addEventListener('pointerdown',e=>{if(!craft)return;craft.down=true;const p=worldPoint(e,craftCanvas,700,360);craft.last=p;craftInput(p,true);craftCanvas.setPointerCapture(e.pointerId)});craftCanvas.addEventListener('pointermove',e=>{if(craft?.down)craftInput(worldPoint(e,craftCanvas,700,360))});for(const event of ['pointerup','pointercancel'])craftCanvas.addEventListener(event,()=>{if(craft){craft.down=false;craft.last=null}});
function assist(){if(!craft||craft.ready)return;craft.tool={x:330+Math.sin(craft.progress)*80,y:160};if(craft.type==='hammer'){const i=craft.pegs.findIndex(v=>v<2);craftInput({x:245+i*70,y:165},true)}else if(craft.type==='align'){craft.angle*=.72;progress(Math.abs(craft.angle)<.1?100:100-Math.abs(craft.angle)/1.3*100);sound()}else if(craft.type==='wrap'){craft.total+=Math.PI/5;progress(craft.total/(Math.PI*4)*100);sound('sand')}else{progress(craft.progress+8);dust(350,165);sound('sand')}}
$('craft-assist').onclick=assist;$('craft-dialog').addEventListener('keydown',e=>{if(e.code==='Space'&&e.target!==$('craft-done')&&e.target!==$('craft-close')){e.preventDefault();assist()}});
function drawCraft(now){fit(cc,craftCanvas,700,360);cc.fillStyle='#e6e9dc';cc.fillRect(-100,-100,900,600);const {type,progress:p}=craft;cc.save();cc.shadowColor='#2f482b30';cc.shadowBlur=20;cc.shadowOffsetY=10;
if(type==='sand'){const r=90,rough=(1-p/100)*10;cc.translate(350,165);cc.rotate(now*.0002);const pts=[];for(let i=0;i<64;i++){const a=i*Math.PI/32,rr=r+Math.sin(i*2.3)*rough;pts.push([Math.cos(a)*rr,Math.sin(a)*rr])}poly(cc,pts,'#bf8d53','#997142');circle(cc,0,0,77,null,'#ddb887');circle(cc,0,0,65,null,'#b48145');circle(cc,0,0,48,null,'#d5a469');circle(cc,0,0,10,'#5f684c','#d7b175');cc.restore();if(!craft.ready){cc.save();cc.translate(craft.tool.x,craft.tool.y);cc.rotate(-.4);wood(cc,-27,-11,54,22,6);cc.restore()}}
else if(type==='hammer'){wood(cc,203,165,295,60,20);craft.pegs.forEach((v,i)=>{const x=245+i*70;wood(cc,x-6,133+v*14,12,36-v*14,3);circle(cc,x,134+v*14,9,v===2?'#d7b67c':'#ead19d','#8f784e');if(i===craft.pegs.findIndex(v=>v<2)){circle(cc,x,165,27,null,'#b8593d')}});cc.restore()}
else if(type==='align'){drawPart(cc,craft.id,350,165,craft.id==='waterwheel'?.92:1.5,craft.angle);cc.restore();line(cc,350,52,350,83,'#b75036',5);cc.save();cc.translate(350,165);cc.rotate(craft.angle);line(cc,0,-86,0,-110,'#b75036',5);cc.restore();circle(cc,350,165,112,null,'#bec8ad')}
else{drawPart(cc,'bucket',350,165,2.3,0);cc.restore();for(let i=0;i<Math.floor(p/10);i++){cc.beginPath();cc.ellipse(350,130+i*9,66,15,0,0,Math.PI*2);cc.strokeStyle=i%2?'#d4b771':'#b59b61';cc.lineWidth=3;cc.stroke()}if(!craft.ready){cc.setLineDash([4,6]);circle(cc,350,165,115,null,'#b6c2a1');cc.setLineDash([])}}
for(const q of craft.dust){q.x+=q.vx;q.y+=q.vy;q.vy+=.1;q.life-=.015;cc.globalAlpha=Math.max(q.life,0);cc.fillStyle='#a87940';cc.fillRect(q.x,q.y,5,2)}cc.globalAlpha=1;craft.dust=craft.dust.filter(q=>q.life>0);if(craft.ready){cc.fillStyle='#496a47';cc.font='16px Microsoft YaHei';cc.textAlign='center';cc.fillText('✓ 加工完成',350,305);cc.textAlign='left'}}
function closeCraft(){craft=null;$('craft-dialog').close()}
$('craft-close').onclick=closeCraft;$('craft-dialog').addEventListener('cancel',()=>{craft=null});$('craft-done').onclick=()=>{if(!craft?.ready)return;const id=craft.id;if(!state.crafted.includes(id))state.crafted.push(id);closeCraft();selected=id;refresh();$('guide-copy').textContent='做得不错！'+parts[id].name+'已经拿在手里，放到工作台上吧。';say('亲手做成了'+parts[id].name+'。以后可以直接拿取。')};
$$('[data-project]').forEach(b=>b.onclick=()=>changeProject(b.dataset.project));$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('run-button').onclick=run;$('clear-button').onclick=()=>{remember();stop();if(state.project==='free')state.free=[];else state.assemblies[state.project]={};selected=null;refresh();$('guide-copy').textContent='零件收回了，加工过的零件都还在。重新拼一个吧。'};$('undo-button').onclick=()=>{if(!history.length)return;stop();Object.assign(state,JSON.parse(history.pop()));selected=null;refresh()};$('sound-toggle').onclick=()=>{state.muted=!state.muted;refresh();if(!state.muted)sound('bell')};$('help-button').onclick=()=>$('help-dialog').showModal();$('help-close').onclick=$('help-start').onclick=()=>$('help-dialog').close();$('result-close').onclick=$('result-retry').onclick=()=>$('result-dialog').close();$('result-next').onclick=()=>{$('result-dialog').close();const next=projects[state.project].next;changeProject(next==='free'&&state.completed.length<3?['car','water','bell'].find(id=>!state.completed.includes(id)):next)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();refresh()}});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){selected=null;stop();refresh()}});
refresh();$('guide-copy').textContent=projects[state.project].prompt;requestAnimationFrame(frame);
})();
