(function(){
'use strict';
const {parts,projects,techs,fresh,sanitize,evaluate,network,unlock,geometry,planePoint,bucketPose}=Tiangong;
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const KEY='tiangong-workshop-v1';let state;try{state=sanitize(JSON.parse(localStorage.getItem(KEY)))}catch{state=fresh()}
let selected=null,view='bench',running=false,startTime=0,resultTimer=0,toastTimer=0,history=[],craft=null,drag=null,freeDrag=null,hover=null,particles=[],lastBell=-1,audioContext=null,lastSound=0;
const canvas=$('scene'),ctx=canvas.getContext('2d'),craftCanvas=$('craft-canvas'),cc=craftCanvas.getContext('2d');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const worldArt=document.createElement('img');worldArt.src='assets/courtyard-v2.webp';
// Source rectangles leave each object's natural highlights intact; destination
// anchors match the existing assembly pivots and pointer coordinates.
const propAtlas={
 body:[12,45,340,268,-155,-130,310,244],axle:[376,134,340,90,-144,-21,288,49],
 wheel:[766,28,281,289,-56,-57,112,116],bigwheel:[1113,13,310,326,-77,-79,155,163],
 support:[38,377,313,325,-110,-112,220,228],waterwheel:[378,358,349,342,-100,-101.8,203,199],
 crank:[747,393,359,239,-18,-57.4,116,78],bucket:[1154,367,228,337,-29,-56,59,87],
 gear:[25,721,309,326,-64,-68,130,137],cam:[409,763,267,255,-49.5,-38.5,82,78],
 striker:[722,802,361,173,-14,-35.5,157,75],bell:[1159,725,228,323,-43,-72,87,123]
};
const propArt=document.createElement('img');propArt.onload=()=>{refresh();if(view==='collection')renderCollection()};propArt.src='assets/props-v3.png';
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('saved-label').textContent='进度自动记下'}catch{$('saved-label').textContent='当前浏览器无法保存'}}
function say(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3600)}
function sound(type='wood'){if(state.muted)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime;if(now-lastSound<.045)return;lastSound=now;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type==='bell'?'sine':'triangle';o.frequency.setValueAtTime(type==='bell'?880:type==='win'?660:type==='sand'?170:240,now);o.frequency.exponentialRampToValueAtTime(type==='bell'?700:type==='win'?990:75,now+.15);g.gain.setValueAtTime(type==='sand'?.018:.065,now);g.gain.exponentialRampToValueAtTime(.001,now+(type==='bell'?.9:.24));o.connect(g);g.connect(audioContext.destination);o.start();o.stop(now+1)}catch{}}
function circle(c,x,y,r,fill,stroke){c.beginPath();c.arc(x,y,r,0,Math.PI*2);if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.stroke()}}
function line(c,x1,y1,x2,y2,color='#816344',width=4){c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.lineWidth=width;c.strokeStyle=color;c.lineCap='round';c.stroke()}
function poly(c,points,fill,stroke){c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();if(fill){c.fillStyle=fill;c.fill()}if(stroke){c.strokeStyle=stroke;c.lineWidth=1.3;c.stroke()}}
function wood(c,x,y,w,h,depth=10){
 poly(c,[[x,y],[x+w,y],[x+w+depth,y-depth],[x+depth,y-depth]],'#e1bc75','#997242');
 poly(c,[[x+w,y],[x+w+depth,y-depth],[x+w+depth,y+h-depth],[x+w,y+h]],'#795239','#694e36');
 const g=c.createLinearGradient(x,y,x+w*.25,y+h);g.addColorStop(0,'#cca05e');g.addColorStop(.44,'#b88148');g.addColorStop(.46,'#ad7743');g.addColorStop(1,'#95623b');c.fillStyle=g;c.fillRect(x,y,w,h);c.strokeStyle='#79603c';c.lineWidth=1.3;c.strokeRect(x,y,w,h);line(c,x+1,y+1,x+w-1,y+1,'#f1d795',1.8);
 c.save();c.beginPath();c.rect(x+2,y+2,w-4,Math.max(1,h-4));c.clip();for(let i=0;i<4;i++){const gy=y+4+(i+.4)*h/4;c.beginPath();c.moveTo(x+4,gy);c.bezierCurveTo(x+w*.3,gy-2,x+w*.55,gy+3,x+w-4,gy);c.strokeStyle=i%2?'#e0b97766':'#75513744';c.lineWidth=.7;c.stroke()}if(w>80){c.beginPath();c.ellipse(x+w*.72,y+h*.46,8,Math.max(1,h*.08),-.05,0,7);c.strokeStyle='#7d583533';c.stroke()}c.restore();
}
function drawPart(c,id,x,y,scale=1,angle=0,opacity=1){c.save();c.translate(x,y);c.scale(scale,scale);c.globalAlpha*=opacity;c.shadowColor='#122d3060';c.shadowBlur=5;c.shadowOffsetX=2;c.shadowOffsetY=5;const kind=parts[id].kind;let r=55*(parts[id].size||1);
if(propArt.complete&&propArt.naturalWidth&&propAtlas[id]){c.rotate(angle);c.drawImage(propArt,...propAtlas[id]);c.restore();return}
if(kind==='wheel'||kind==='gear'||kind==='waterwheel'||kind==='cam'){
 c.rotate(angle);if(kind==='gear'){r=59;const points=[];for(let i=0;i<48;i++){const a=i*Math.PI/24,rr=i%4<2?65:54;points.push([Math.cos(a)*rr,Math.sin(a)*rr])}poly(c,points,'#bb955c','#7a603c')}
 if(kind==='waterwheel')r=99;if(kind==='cam')r=39;
 const off=kind==='cam'?14:0;circle(c,4+off,5,r,'#71543b','#5c4934');const timber=c.createLinearGradient(-r,-r,r,r);timber.addColorStop(0,'#edd195');timber.addColorStop(.45,'#c79c5d');timber.addColorStop(.48,'#b4854b');timber.addColorStop(1,'#94673c');circle(c,off,0,r,timber,'#80603b');circle(c,off,0,r-5,null,'#edd19b');circle(c,off,0,r-12,null,'#98723f');
 if(kind==='waterwheel'){circle(c,0,0,r-18,'#e1dec9','#8c6e41');for(let i=0;i<10;i++){c.save();c.rotate(i*Math.PI/5);wood(c,-5,0,10,90,3);wood(c,-20,79,40,13,5);c.restore()}}
 else if(kind==='wheel'||kind==='gear'){for(let i=0;i<6;i++){c.save();c.rotate(i*Math.PI/3);line(c,0,0,r-18,0,'#e0ba80',7);line(c,0,1,r-18,1,'#976d3e',1);c.restore()}}
 circle(c,0,0,14,'#587e65','#bcb574');circle(c,0,0,9,'#d3b573','#a48543');circle(c,0,0,4,'#294f47','#f0d494');
}else if(kind==='body'){wood(c,-145,-10,290,46,35);for(let i=0;i<4;i++)line(c,-125+i*65,-35,-145+i*65,-10,'#b18a58',2);wood(c,-125,-20,13,35,26);wood(c,103,-20,13,35,26)}
else if(kind==='axle'){wood(c,-139,-7,278,17,7);circle(c,-139,2,9,'#d1ad73','#936c42');circle(c,143,-3,9,'#d1ad73','#936c42')}
else if(kind==='support'){wood(c,-100,76,212,18,20);wood(c,-88,-93,19,171,13);wood(c,73,-93,19,171,13);wood(c,-99,-94,192,17,15);line(c,-80,70,64,-79,'#926638',9)}
else if(kind==='crank'){c.rotate(angle);circle(c,0,0,18,'#b98d48','#7c663d');line(c,0,0,49,-25,'#be9a5a',13);circle(c,50,-25,11,'#3d6055','#223e39');wood(c,47,-58,11,35,4)}
else if(kind==='bucket'){poly(c,[[-27,-20],[27,-20],[20,26],[-20,26]],'#a97740','#78542f');poly(c,[[-27,-20],[0,-29],[27,-20],[0,-10]],'#6e5437','#c79e65');for(let i=-12;i<20;i+=11)line(c,i,-7,i,20,'#d0a76a',1);line(c,-24,-1,24,-1,'#4b6655',3);line(c,-21,18,21,18,'#4b6655',3);c.strokeStyle='#bea66c';c.lineWidth=3;c.beginPath();c.arc(0,-15,25,Math.PI,0);c.stroke()}
else if(kind==='striker'){c.rotate(angle);wood(c,-14,-5,130,11,4);wood(c,109,-24,24,46,8)}
else if(kind==='bell'){c.rotate(angle);const g=c.createLinearGradient(-40,0,40,0);g.addColorStop(0,'#8d722f');g.addColorStop(.5,'#debf69');g.addColorStop(1,'#aa8837');circle(c,0,-40,9,null,'#9d8237');c.beginPath();c.moveTo(-10,-40);c.bezierCurveTo(-42,-32,-20,3,-44,21);c.quadraticCurveTo(0,39,44,21);c.bezierCurveTo(20,3,42,-32,10,-40);c.closePath();c.fillStyle=g;c.fill();c.strokeStyle='#8f7738';c.lineWidth=2;c.stroke();c.beginPath();c.ellipse(0,23,43,10,0,0,7);c.fillStyle='#907438';c.fill();circle(c,0,25,8,'#d7b361');line(c,-29,10,29,10,'#eedda0',2)}
c.restore();}
function camera(el,width,height,w,h){const scene=el===canvas,s=Math.min(width/(scene?(width<=800?840:1150):w),height/(scene?600:h));return{s,x:(width-w*s)/2,y:(height-h*s)/2}}
function fit(c,el,w,h){const ratio=Math.min(devicePixelRatio||1,2),r=el.getBoundingClientRect();if(!r.width||!r.height)return;const pw=Math.round(r.width*ratio),ph=Math.round(r.height*ratio);if(el.width!==pw||el.height!==ph){el.width=pw;el.height=ph}c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,pw,ph);const v=camera(el,r.width,r.height,w,h);c.setTransform(v.s*ratio,0,0,v.s*ratio,v.x*ratio,v.y*ratio);return v.s*ratio;}
function worldPoint(e,el,w=1000,h=560){const r=el.getBoundingClientRect(),v=camera(el,r.width,r.height,w,h);return{x:(e.clientX-r.left-v.x)/v.s,y:(e.clientY-r.top-v.y)/v.s};}
function background(c){
 c.save();c.setTransform(1,0,0,1,0,0);c.fillStyle='#819d83';c.fillRect(0,0,canvas.width,canvas.height);
 if(worldArt.complete&&worldArt.naturalWidth){const cover=Math.max(canvas.width/worldArt.naturalWidth,canvas.height/worldArt.naturalHeight);c.drawImage(worldArt,(canvas.width-worldArt.naturalWidth*cover)/2,(canvas.height-worldArt.naturalHeight*cover)/2,worldArt.naturalWidth*cover,worldArt.naturalHeight*cover)}c.restore();
 const sunlight=c.createLinearGradient(0,0,760,570);sunlight.addColorStop(0,'#ffe4a924');sunlight.addColorStop(.58,'#fff2cd00');sunlight.addColorStop(1,'#183f393d');c.fillStyle=sunlight;c.fillRect(-300,-300,1600,1200);
 c.save();c.shadowColor='#203d395e';c.shadowBlur=22;c.shadowOffsetX=12;c.shadowOffsetY=24;poly(c,[[140,210],[772,210],[950,431],[28,431]],'#b18b52');c.restore();
 // Keep the interactive work surface and its coordinates fixed.
 wood(c,142,425,27,64,13);wood(c,852,425,27,62,13);
 poly(c,[[28,431],[950,431],[950,452],[28,452]],'#694930','#483c2e');
 const top=c.createLinearGradient(150,210,870,435);top.addColorStop(0,'#cba465');top.addColorStop(.48,'#ab7b48');top.addColorStop(1,'#856038');poly(c,[[140,210],[772,210],[950,431],[28,431]],top,'#705533');
 c.save();c.beginPath();c.moveTo(140,210);c.lineTo(772,210);c.lineTo(950,431);c.lineTo(28,431);c.closePath();c.clip();
 for(let i=0;i<84;i++){const y=211+i*2.7;c.beginPath();c.moveTo(20,y);c.bezierCurveTo(240,y+Math.sin(i*.7)*3,610,y-Math.cos(i*.43)*4,955,y+Math.sin(i)*2);c.strokeStyle=i%3?'#563b242b':'#e2be7e39';c.lineWidth=i%7===0?1.2:.6;c.stroke()}
 for(let i=0;i<8;i++){const y=226+i*30;line(c,10,y,965,y,'#45392765',1);line(c,10,y+1.4,965,y+1.4,'#e4c5934f',.8)}
 c.restore();line(c,140,212,772,212,'#e2c083',2);line(c,29,431,949,431,'#dbb578',2);line(c,29,447,949,447,'#b78d5059',1);
 for(const x of [45,918]){c.fillStyle='#829074';c.fillRect(x,432,16,19);circle(c,x+8,438,2,'#ddc186')}
 poly(c,[[208,232],[726,232],[839,411],[108,411]],'#233f3650');const mat=c.createLinearGradient(220,220,500,410);mat.addColorStop(0,'#526b50');mat.addColorStop(.5,'#3a5946');mat.addColorStop(1,'#28463e');poly(c,[[206,228],[726,228],[839,407],[108,407]],mat,'#74846a');
 poly(c,[[221,239],[716,239],[821,396],[127,396]],null,'#b8b67866');
 c.save();c.beginPath();c.moveTo(206,228);c.lineTo(726,228);c.lineTo(839,407);c.lineTo(108,407);c.closePath();c.clip();for(let y=233;y<407;y+=4)line(c,105,y,840,y,'#90a67b19',.5);c.restore();
 for(let i=0;i<7;i++)line(c,175,260+i*20,182,260+i*20,'#aeb18188',1);
 c.save();c.translate(156,373);c.rotate(-.2);wood(c,-73,-7,135,12,3);for(let i=0;i<24;i++)line(c,-65+i*5,-6,-65+i*5,i%5===0?3:-1,'#745f39',1);c.restore();c.save();c.translate(822,357);c.rotate(.45);wood(c,-5,-38,11,83,4);wood(c,-23,-45,48,18,5);line(c,-5,13,5,13,'#56806b',4);line(c,-5,20,5,20,'#56806b',4);c.restore();
 c.font='10px Georgia';c.fillStyle='#e9d8ae';c.fillText('TIANGONG   ·   百工造物',386,442);
}
function ghost(c,slot){c.save();const target=selected&&parts[selected].kind===slot.kind;c.strokeStyle=target?'#f0d08d':'#c2cbb2';c.fillStyle=target?'#ead7a326':'#b5c1a114';c.lineWidth=1.6;c.setLineDash([5,5]);c.beginPath();c.ellipse(slot.x,slot.y,slot.kind==='body'?151:slot.kind==='axle'?135:slot.kind==='support'?75:slot.kind==='waterwheel'?88:44,slot.kind==='body'?36:slot.kind==='axle'?16:slot.kind==='support'?90:slot.kind==='waterwheel'?88:44,0,0,7);c.fill();c.stroke();c.setLineDash([]);c.font='13px Microsoft YaHei';c.textAlign='center';c.fillStyle=target?'#fff1c6':'#e0e4d5';c.fillText('+ '+slot.name,slot.x,slot.y+5);c.restore()}
function previewPart(c,id,x,y,scale){const r=propAtlas[id];drawPart(c,id,x-(r[4]+r[6]/2)*scale,y-(r[5]+r[7]/2)*scale,scale)}
function freeHit(n,p){const r=propAtlas[n.part],x=(p.x-n.x)/.65,y=(p.y-n.y)/.65;return x>=r[4]-8&&x<=r[4]+r[6]+8&&y>=r[5]-8&&y<=r[5]+r[7]+8}
function slotDistance(slot,p){const points=[slot];if(state.project==='car'){
 if(slot.kind==='wheel')points.push({x:slot.x+geometry.car.depth.x,y:slot.y+geometry.car.depth.y});
 if(slot.kind==='axle')for(const a of geometry.car.near)points.push({x:a.x+geometry.car.depth.x/2,y:a.y+geometry.car.depth.y/2});
 }return Math.min(...points.map(a=>Math.hypot(a.x-p.x,a.y-p.y)))}
// Rotate in the object's local plane, then project. Projecting after rotation
// keeps wheel hubs fixed and prevents the entire wheel plane from wobbling.
function projectedPart(c,id,point,plane,scale=1,angle=0){c.save();c.translate(point.x,point.y);c.transform(...plane,0,0);drawPart(c,id,0,0,scale,angle);c.restore()}
function shaft(c,a,b){drawPart(c,'axle',(a.x+b.x)/2,(a.y+b.y)/2,Math.hypot(b.x-a.x,b.y-a.y)/288,Math.atan2(b.y-a.y,b.x-a.x))}
function hangingBell(c,p,angle){c.save();c.translate(p.x,p.y-63);c.rotate(angle);drawPart(c,'bell',0,63);c.restore()}
function drawMachine(c,id,assembly,t=0,preview=false){const p=projects[id],active=running&&!preview;c.save();
 if(id==='car'&&active){const wobble=evaluate(id,assembly).type==='wobble';c.translate(490+Math.sin(t*.85)*95,320+(wobble?Math.sin(t*3)*7:0));c.rotate(wobble?Math.sin(t*3)*.04:0);c.translate(-490,-320)}
 c.save();c.globalAlpha=.18;c.fillStyle='#243927';c.beginPath();c.ellipse(500,405,id==='car'?178:170,23,0,0,7);c.fill();c.restore();
 if(id==='car'){
  const g=geometry.car,far=g.near.map(p=>({x:p.x+g.depth.x,y:p.y+g.depth.y})),spin=active?t*2.5:0;
  // Each wheel slot is a matched pair. Never invent wheels when only the board exists.
  for(let i=0;i<2;i++){const part=assembly[i?'right':'left'];if(part)projectedPart(c,part,far[i],g.plane,1,spin)}
  if(assembly.axle)for(let i=0;i<2;i++)shaft(c,g.near[i],far[i]);
  if(assembly.body)drawPart(c,assembly.body,g.body.x,g.body.y);
  for(let i=0;i<2;i++){const part=assembly[i?'right':'left'];if(part)projectedPart(c,part,g.near[i],g.plane,1,spin)}
 }else if(id==='water'){
  const g=geometry.water,spin=active?-t*.8:0;
  c.fillStyle='#678f8a';c.beginPath();c.ellipse(455,417,122,13,0,0,7);c.fill();
  // The shaft and handle share the waterwheel's axle instead of floating beside it.
  if(assembly.support)drawPart(c,'support',515,320);
  if(assembly.waterwheel||assembly.crank)shaft(c,g.hub,g.handle);
  if(assembly.crank)projectedPart(c,'crank',g.handle,g.plane,.8,spin);
  if(assembly.waterwheel)projectedPart(c,'waterwheel',g.hub,g.plane,1,spin);
  if(assembly.bucket){const b=bucketPose(active?t:0);line(c,b.x,b.y,b.x,b.y+7,'#ba9a5e',3);drawPart(c,'bucket',b.x,b.y+32,.68)}
  if(assembly.support){c.save();c.translate(487,201);c.transform(...g.plane,0,0);wood(c,0,0,171,10,9);c.restore();line(c,637,250.75,637,399,'#a48754',6)}
  if(active&&assembly.bucket&&assembly.waterwheel){const b=bucketPose(t);if(b.y<233&&b.x>450)for(let i=0;i<8;i++){const f=(t*1.5+i/8)%1;circle(c,b.x+(493-b.x)*f,b.y+f*30,2,'#a6d9dc')}c.save();c.translate(487,201);c.transform(...g.plane,0,0);c.fillStyle='#8fbdb4';c.fillRect(4,-2,Math.min(t*8,161),3);c.restore()}
 }else if(id==='bell'){
  const g=geometry.bell,spin=active?t*2.5:0,camSpin=-spin*1.6,lift=active?Math.max(0,Math.sin(camSpin)):0,lever=-lift*.28;
  if(assembly.support)drawPart(c,'support',505,325);
  if(assembly.gear)projectedPart(c,'gear',g.gear,g.plane,1.04,spin);
  if(assembly.cam)projectedPart(c,'cam',g.cam,g.plane,1,camSpin);
  if(assembly.support&&assembly.bell){line(c,587,255,642,215,'#926d3f',9);line(c,587,252,642,212,'#c6a46b',2);line(c,642,215,642,228,'#bda267',3)}
  if(assembly.bell)hangingBell(c,g.bell,active?Math.sin(t*16)*Math.max(0,1-lift*4)*.025:0);
  if(assembly.striker){
   c.save();c.translate(g.pivot.x,g.pivot.y);c.transform(...g.plane,0,0);c.rotate(lever);
   if(assembly.cam)wood(c,29,5,8,14,2);drawPart(c,'striker',0,0);circle(c,0,0,7,'#58796b','#d1ad6d');c.restore();
  }
  if(active&&assembly.bell&&lift<.12)for(let i=0;i<3;i++){c.beginPath();c.arc(g.bell.x,g.bell.y,50+i*10,-.7,.5);c.strokeStyle='#bea258';c.lineWidth=1.5;c.stroke()}
 }
 // Empty anchors are drawn last so the board cannot hide a wheel/axle target.
 if(!preview)for(const slot of p.slots)if(!assembly[slot.id])ghost(c,slot);
 c.restore();}
function drawFree(c,t){const power=network(state.free);for(const a of state.free)for(const b of state.free)if(a.id<b.id&&Math.hypot(a.x-b.x,a.y-b.y)<=150){line(c,a.x,a.y,b.x,b.y,running&&power.has(a.id)?'#ecd78c':'#a7b299',3);if(running&&power.has(a.id)){const f=(t*.5)%1;circle(c,a.x+(b.x-a.x)*f,a.y+(b.y-a.y)*f,4,'#fff0ad')}}
 for(const p of state.free){const on=running&&power.has(p.id),kind=parts[p.part].kind;const angle=on?(['wheel','gear','waterwheel','crank','cam'].includes(kind)?t*2*(p.id%2?1:-1):['striker','bell'].includes(kind)?Math.sin(t*5)*.15:0):0;drawPart(c,p.part,p.x,p.y,.65,angle);if(hover?.id===p.id){circle(c,p.x,p.y,46,null,'#ead494')}}
 if(!state.free.length){c.fillStyle='#e0e7d4';c.font='17px SimSun';c.textAlign='center';c.fillText('把零件放在这里，看看会发生什么',490,320);c.textAlign='left'}}
function sparkle(x,y,count=15){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*2.5,vy:-Math.random()*2-1,life:1,color:i%2?'#d9b777':'#fff2c4'})}
function frame(now){if(view==='bench'&&!document.hidden){fit(ctx,canvas,1000,560);background(ctx);const t=running?(now-startTime)/1000:0;if(state.project==='free')drawFree(ctx,t);else drawMachine(ctx,state.project,state.assemblies[state.project],t);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.06;p.life-=.02;ctx.globalAlpha=Math.max(p.life,0);circle(ctx,p.x,p.y,2,p.color)}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);if(running&&(state.project==='bell'||state.project==='free'&&state.free.some(p=>p.part==='bell'&&network(state.free).has(p.id)))){const tick=Math.floor(t*2.5/(Math.PI*2));if(tick!==lastBell){lastBell=tick;sound('bell')}}}if(craft&&$('craft-dialog').open)drawCraft(now);requestAnimationFrame(frame)}
function refresh(){const p=projects[state.project],a=state.assemblies[state.project]||{};save();$('project-title').textContent=p.title;$('project-tag').textContent=p.tag;$('scene-number').textContent='造物 · '+({car:'001',water:'002',bell:'003',free:'自由'}[state.project]);$('tech-count').textContent=state.tech.length+'/9';$('assembly-count').textContent=state.project==='free'?state.free.length+' / 18 件':`已装 ${Object.keys(a).length} / ${p.slots.length} 件`;$('free-caption').textContent=state.completed.length===3?'所有零件，随你拼':'完成三件造物后开启';
 $$('[data-project]').forEach(b=>{b.classList.toggle('active',b.dataset.project===state.project);b.setAttribute('aria-pressed',b.dataset.project===state.project);if(b.querySelector('i'))b.querySelector('i').textContent=state.completed.includes(b.dataset.project)?'✓':''});
 $('parts-tray').innerHTML=p.parts.map(id=>`<button class="part-card ${selected===id?'selected':''}" data-part="${id}" aria-label="拿取${parts[id].name}" aria-pressed="${selected===id}"><span class="part-status">${parts[id].craft?(state.crafted.includes(id)?'已会做':'手作'):''}</span><canvas width="180" height="128" aria-hidden="true"></canvas><strong>${parts[id].name}</strong><small>${parts[id].craft&&!state.crafted.includes(id)?'先亲手加工':'拿取 · 放上桌'}</small></button>`).join('');
 $$('.part-card').forEach(b=>{const c=b.querySelector('canvas').getContext('2d');c.translate(90,65);const id=b.dataset.part;previewPart(c,id,0,0,['body','axle','support','waterwheel'].includes(id)?.5:.75);b.addEventListener('click',()=>selectPart(id));b.addEventListener('pointerdown',e=>startDrag(e,id,b))});
 if(state.project==='free'){$('slot-list').innerHTML='<button class="slot-button" id="free-place">＋ 放到空位</button><button class="slot-button" id="free-last">− 取下最后一件</button>';$('free-place').onclick=()=>{if(!selected)return say('先从零件匣里拿一件。');const i=state.free.length;place(selected,{x:230+i%5*130,y:240+Math.floor(i/5)*70})};$('free-last').onclick=()=>{if(!state.free.length)return;remember();stop();state.free.pop();refresh()}}
 else{$('slot-list').innerHTML=p.slots.map(s=>`<button class="slot-button ${a[s.id]?'filled':''} ${selected&&parts[selected].kind===s.kind?'target':''}" data-slot="${s.id}">${a[s.id]?'✓':'＋'} ${s.name}</button>`).join('');$$('[data-slot]').forEach(b=>b.onclick=()=>slotAction(b.dataset.slot))}
 const n=Object.keys(a).length,done=n===p.slots.length&&n>0;for(const id of ['craft','build','run'])$('step-'+id).classList.remove('active','done');$('step-'+(running||done?'run':n||selected?'build':'craft')).classList.add('active');if(n)$('step-craft').classList.add('done');if(done)$('step-build').classList.add('done');
 $('scene-hint').textContent=running?'装置正在运转 · 再拉一次把手可停下':selected?`拿着「${parts[selected].name}」 · 放到${state.project==='free'?'桌面任意位置':'亮起的装配位置'}`:state.project==='free'?'邻近的零件会相连 · 点击已放置的零件可取下':done?'拼好了！拉动把手，看看它会怎样动':'① 从下方拿一件零件，开始造物';
 $('discovery-hint').textContent=({car:'两只轮子如果不一样大，小车会怎样走？',water:'把水提起来，靠的是水斗和转动一起配合。',bell:'一直转圈的齿轮，怎样让木槌反复敲打？',free:'靠近会连接，分开会断开。试试混搭三种造物的零件。'})[state.project];$('sound-toggle').textContent=state.muted?'♪':'♫';$('sound-toggle').setAttribute('aria-label',state.muted?'开启声音':'关闭声音');$('undo-button').disabled=!history.length;
}
function stop(){running=false;clearTimeout(resultTimer);$('run-button').classList.remove('running');$('run-label').textContent='拉动把手';lastBell=-1}
function remember(){history.push(JSON.stringify({assemblies:state.assemblies,free:state.free}));if(history.length>30)history.shift()}
function changeProject(id){if(id==='free'&&state.completed.length<3){say(`再完成 ${3-state.completed.length} 件造物，自由工作台就开放。`);return}stop();state.project=id;selected=null;history=[];$('guide-copy').textContent=projects[id].prompt;refresh();switchView('bench')}
function selectPart(id){stop();if(parts[id].craft&&!state.crafted.includes(id)){beginCraft(id);return}selected=selected===id?null:id;$('guide-copy').textContent=selected?`拿好了${parts[id].name}。${state.project==='free'?'放到桌面上，靠近别的零件就能接起来。':'放到虚线位置，也可以点装配位置按钮。'}`:projects[state.project].prompt;sound();refresh()}
function slotAction(id){const slot=projects[state.project].slots.find(s=>s.id===id);if(selected){if(parts[selected].kind!==slot.kind)return say('这件零件不适合这里。试试亮起的位置。');place(selected,slot)}else if(state.assemblies[state.project][id]){remember();stop();const p=state.assemblies[state.project][id];delete state.assemblies[state.project][id];selected=p;refresh();say('取下了'+parts[p].name+'，可以换个位置。')}else say('先从下方零件匣拿取'+slot.name+'。')}
function place(id,pos){stop();if(state.project==='free'){if(state.free.length>=18)return say('桌面放满啦，先取下一件再继续。');remember();state.free.push({id:Math.max(0,...state.free.map(p=>p.id))+1,part:id,x:Math.max(110,Math.min(840,pos.x)),y:Math.max(150,Math.min(430,pos.y))})}else{const s=pos.id?pos:projects[state.project].slots.filter(s=>s.kind===parts[id].kind).sort((a,b)=>Math.hypot(a.x-pos.x,a.y-pos.y)-Math.hypot(b.x-pos.x,b.y-pos.y))[0];if(!s||(!pos.id&&Math.hypot(s.x-pos.x,s.y-pos.y)>135))return say('再靠近亮起的虚线位置一点。');remember();state.assemblies[state.project][s.id]=id;pos=s}selected=null;sparkle(pos.x,pos.y,10);sound();refresh();const a=state.assemblies[state.project];$('guide-copy').textContent=state.project==='free'?'拼上了。继续加零件，或拉动把手试试看。':Object.keys(a).length===projects[state.project].slots.length?'全部拼好了！拉动把手，让它动起来。':'咔哒，装好了。再拿一件，继续拼。'}
function startDrag(e,id,button){if(e.button!==0)return;drag={id,x:e.clientX,y:e.clientY,button,moved:false};if(e.pointerType==='mouse')button.setPointerCapture(e.pointerId)}
window.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<9)return;drag.moved=true;if(!drag.proxy){const p=document.createElement('canvas');p.className='drag-proxy';p.width=180;p.height=180;previewPart(p.getContext('2d'),drag.id,90,90,['body','axle','support','waterwheel'].includes(drag.id)?.45:.7);document.body.append(p);drag.proxy=p}drag.proxy.style.left=(e.clientX-45)+'px';drag.proxy.style.top=(e.clientY-45)+'px'});
window.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;d.proxy?.remove();if(!d.moved)return;const r=canvas.getBoundingClientRect();d.button.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation()},{capture:true,once:true});if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;if(parts[d.id].craft&&!state.crafted.includes(d.id)){beginCraft(d.id);return}selected=d.id;place(d.id,worldPoint(e,canvas))});
window.addEventListener('pointercancel',()=>{drag?.proxy?.remove();drag=null;freeDrag=null});
canvas.addEventListener('pointerdown',e=>{if(running){say('先停下装置，就可以继续拼。');return}const p=worldPoint(e,canvas);if(selected){place(selected,p);return}if(state.project==='free'){const hit=[...state.free].reverse().find(n=>freeHit(n,p));if(hit){freeDrag={hit,original:{x:hit.x,y:hit.y},start:p,moved:false};remember();canvas.setPointerCapture(e.pointerId)}}else{const hit=[...projects[state.project].slots].sort((a,b)=>slotDistance(a,p)-slotDistance(b,p)).find(s=>slotDistance(s,p)<65);if(hit)slotAction(hit.id)}});
canvas.addEventListener('pointermove',e=>{const p=worldPoint(e,canvas);if(freeDrag){if(Math.hypot(p.x-freeDrag.start.x,p.y-freeDrag.start.y)>8)freeDrag.moved=true;if(freeDrag.moved){freeDrag.hit.x=Math.max(110,Math.min(840,p.x));freeDrag.hit.y=Math.max(150,Math.min(430,p.y))}}hover=state.project==='free'?state.free.find(n=>freeHit(n,p)):null});
canvas.addEventListener('pointerup',()=>{if(!freeDrag)return;if(!freeDrag.moved){selected=freeDrag.hit.part;state.free=state.free.filter(n=>n.id!==freeDrag.hit.id)}freeDrag=null;refresh()});
function run(){if(running){stop();refresh();return}if(state.project==='free'){if(!state.free.length)return say('先放一件零件，再拉把手。');const power=network(state.free);$('guide-copy').textContent=`${power.size} 件零件开始接力了。${power.size<state.free.length?'有零件离得太远，靠近一点再试。':'再加点不一样的零件，会发生什么？'}`;if(power.size>=4&&new Set(state.free.filter(p=>power.has(p.id)).map(p=>p.part)).size>=3&&!state.discoveries.includes('mixed')){state.discoveries.push('mixed');say('发现新造物：百工大合奏 ✧');sound('win')}}else{const result=evaluate(state.project,state.assemblies[state.project]);if(!result.ok){say(result.message);$('guide-copy').textContent=result.message;return}$('guide-copy').textContent=result.message;if(result.type==='wobble'){if(!state.discoveries.includes('wobble'))state.discoveries.push('wobble');say('意外发现：不走寻常路的小木车 ✧')}const first=!state.completed.includes(state.project);unlock(state,state.project);if(first){const id=state.project;resultTimer=setTimeout(()=>showResult(id,result),4300)}else say(result.message)}running=true;startTime=performance.now();lastBell=-1;sound();$('run-button').classList.add('running');$('run-label').textContent='停下来看看';refresh()}
function showResult(id,result){if(id!==state.project||!running)return;const p=projects[id];$('result-eyebrow').textContent='第 '+state.completed.length+' 件造物，记下了';$('result-title').textContent=({car:result.type==='wobble'?'它拐着弯跑起来了！':'它真的跑起来了！',water:'水真的往高处走了！',bell:'听，你做的铃响了！'})[id];$('result-copy').textContent=p.note;$('result-tech').innerHTML=p.tech.map(id=>'<span>✧ '+techs.find(t=>t.id===id).name+'</span>').join('');$('result-next').textContent=p.next==='free'?(state.completed.length===3?'去自由拼搭 →':'继续完成造物 →'):'去做下一件 →';$('result-dialog').showModal();sound('win');for(let i=0;i<5;i++)sparkle(300+i*100,220,16)}
function switchView(id){if(id!=='bench')stop();view=id;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id+'-view'));$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='atlas')renderAtlas();if(id==='collection')renderCollection();if(id==='bench')refresh();}
function renderAtlas(){const edges=[[0,1],[1,2],[0,3],[1,4],[3,4],[4,5],[3,6],[4,7],[6,7],[7,8]];$('atlas').innerHTML=edges.map(([a,b])=>`<path d="M${techs[a].x},${techs[a].y} L${techs[b].x},${techs[b].y}" stroke="${state.tech.includes(techs[a].id)&&state.tech.includes(techs[b].id)?'#bca66f':'#5b7969'}" stroke-width="2" fill="none"/>`).join('')+techs.map((t,i)=>{const on=state.tech.includes(t.id);return `<g class="atlas-node" role="button" tabindex="0" data-tech="${t.id}" aria-label="${t.name}，${on?'已掌握':'待发现'}"><circle cx="${t.x}" cy="${t.y}" r="34" fill="${on?'#4b7456':'#214b43'}" stroke="${on?'#d9b76c':'#709276'}" stroke-width="2"/><text x="${t.x}" y="${t.y+6}" fill="${on?'#ffedb9':'#94ae8d'}" font-size="18" text-anchor="middle">${on?'✧':String(i+1).padStart(2,'0')}</text><text x="${t.x}" y="${t.y+59}" fill="${on?'#f1dfb1':'#9bb69a'}" font-size="17" text-anchor="middle">${t.name}</text></g>`}).join('');$$('[data-tech]').forEach(b=>{const activate=()=>{const t=techs.find(t=>t.id===b.dataset.tech),on=state.tech.includes(t.id),p=Object.entries(projects).find(([id,p])=>p.tech.includes(t.id));$('atlas-detail').innerHTML=`<span class="eyebrow">${on?'已亲手掌握':'下一份好奇'}</span><h2>${t.name}</h2><p>${t.text}</p><p>在「${p[1].short}」中${on?'发现了它':'试试看'}。</p><button class="plain-button" id="atlas-go">去工作台 →</button>`;$('atlas-go').onclick=()=>changeProject(p[0])};b.onclick=activate;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}})}
function renderCollection(){$('collection-grid').innerHTML=['car','water','bell'].map(id=>{const p=projects[id],done=state.completed.includes(id);return `<article class="collection-card"><canvas width="700" height="420" data-display="${id}" aria-label="${p.short}${done?'已完成':'待完成'}"></canvas><p class="eyebrow">${done?'已收藏 · 亲手造物':'等待第一件作品'}</p><h2>${p.title}</h2><p>${done?p.note:'这里留给你亲手完成的'+p.short+'。'}</p><button class="plain-button" data-return="${id}">${done?'拿出来再玩':'去做这一件'} ↗</button></article>`}).join('');$$('[data-display]').forEach(el=>{const c=el.getContext('2d');c.translate(-40,-25);c.scale(.75,.75);const p=projects[el.dataset.display],assembly=state.completed.includes(el.dataset.display)?state.assemblies[el.dataset.display]:{};if(!state.completed.includes(el.dataset.display)){c.globalAlpha=.25;for(const s of p.slots){const id=p.parts.find(id=>parts[id].kind===s.kind);assembly[s.id]=id}}drawMachine(c,el.dataset.display,assembly,0,true)});$$('[data-return]').forEach(b=>b.onclick=()=>changeProject(b.dataset.return));$('discoveries').textContent=state.discoveries.length?'意外发明簿　'+state.discoveries.map(x=>x==='wobble'?'✧ 不走寻常路的小木车':'✧ 百工大合奏').join('　 /　 '):'意外发明簿还是空的。试试那些看起来“不太对”的组合。'}
// Four short craft interactions. Pointer movement affects the material; keyboard is an equivalent accessible route.
const craftInfo={sand:['把木轮磨圆','按住木轮来回打磨，让粗糙的轮廓慢慢变圆。','按住木轮并来回移动'],hammer:['轻敲，固定好','点亮起的木钉，把它一下一下敲进木料。','点击亮起的木钉'],align:['把接口对齐','按住零件绕中心转，让两条红线重合。','绕着圆心转动'],wrap:['把绳索缠好','按住绳头，绕着水斗画圈，把绳索缠牢。','围着水斗转两圈']};
function beginCraft(id){stop();const type=parts[id].craft;craft={id,type,progress:0,angle:-1.3,total:0,down:false,last:null,pegs:[0,0,0,0],dust:[],tool:{x:480,y:200},ready:false};const info=craftInfo[type];$('craft-title').textContent=info[0];$('craft-instruction').textContent=info[1];$('craft-action-hint').textContent=info[2];$('craft-progress').value=0;$('craft-percent').textContent='0%';$('craft-done').disabled=true;$('craft-done').textContent='继续加工';$('craft-dialog').showModal();}
function progress(value){if(!craft||craft.ready)return;craft.progress=Math.min(100,value);$('craft-progress').value=craft.progress;$('craft-percent').textContent=Math.round(craft.progress)+'%';if(craft.progress>=100){craft.ready=true;$('craft-done').disabled=false;$('craft-done').textContent='做好了，拿去拼装 →';$('craft-action-hint').textContent='这件零件，现在是你亲手做的了。';sound('win')}}
function dust(x,y){for(let i=0;i<4;i++)craft.dust.push({x,y,vx:(Math.random()-.5)*4,vy:Math.random()*2,life:1})}
function craftInput(p,click=false){if(!craft||craft.ready)return;const d=Math.hypot(p.x-350,p.y-165);craft.tool=p;if(craft.type==='sand'){if(d<130&&craft.last){const delta=Math.hypot(p.x-craft.last.x,p.y-craft.last.y);if(delta>2){progress(craft.progress+Math.min(delta*.065,3.2));dust(p.x,p.y);sound('sand')}}}
else if(craft.type==='hammer'&&click){const i=craft.pegs.findIndex(v=>v<2),x=245+i*70;if(Math.hypot(p.x-x,p.y-165)<43){craft.pegs[i]++;progress(craft.pegs.reduce((a,b)=>a+b,0)*12.5);dust(x,165);sound()}}
else if(craft.type==='align'&&craft.last&&d>35&&d<150){let delta=Math.atan2(p.y-165,p.x-350)-Math.atan2(craft.last.y-165,craft.last.x-350);delta=Math.atan2(Math.sin(delta),Math.cos(delta));craft.angle+=delta;const error=Math.abs(Math.atan2(Math.sin(craft.angle),Math.cos(craft.angle)));progress(error<.1?100:Math.max(0,100-error/1.3*100));sound('sand')}
else if(craft.type==='wrap'&&craft.last&&d>35&&d<170){let delta=Math.atan2(p.y-165,p.x-350)-Math.atan2(craft.last.y-165,craft.last.x-350);delta=Math.abs(Math.atan2(Math.sin(delta),Math.cos(delta)));if(delta<.5){craft.total+=delta;progress(craft.total/(Math.PI*4)*100);sound('sand')}}craft.last=p;}
craftCanvas.addEventListener('pointerdown',e=>{if(!craft)return;craft.down=true;const p=worldPoint(e,craftCanvas,700,360);craft.last=p;craftInput(p,true);craftCanvas.setPointerCapture(e.pointerId)});craftCanvas.addEventListener('pointermove',e=>{if(craft?.down)craftInput(worldPoint(e,craftCanvas,700,360))});for(const event of ['pointerup','pointercancel'])craftCanvas.addEventListener(event,()=>{if(craft){craft.down=false;craft.last=null}});
function assist(){if(!craft||craft.ready)return;craft.tool={x:330+Math.sin(craft.progress)*80,y:160};if(craft.type==='hammer'){const i=craft.pegs.findIndex(v=>v<2);craftInput({x:245+i*70,y:165},true)}else if(craft.type==='align'){craft.angle*=.72;progress(Math.abs(craft.angle)<.1?100:100-Math.abs(craft.angle)/1.3*100);sound()}else if(craft.type==='wrap'){craft.total+=Math.PI/5;progress(craft.total/(Math.PI*4)*100);sound('sand')}else{progress(craft.progress+8);dust(350,165);sound('sand')}}
$('craft-assist').onclick=assist;$('craft-dialog').addEventListener('keydown',e=>{if(e.code==='Space'&&e.target!==$('craft-done')&&e.target!==$('craft-close')){e.preventDefault();assist()}});
function drawCraft(now){fit(cc,craftCanvas,700,360);const craftLight=cc.createLinearGradient(100,0,600,360);craftLight.addColorStop(0,'#2e5145');craftLight.addColorStop(.5,'#213f3c');craftLight.addColorStop(1,'#102c34');cc.fillStyle=craftLight;cc.fillRect(-800,-500,2400,1400);cc.strokeStyle='#dde1b71a';cc.lineWidth=1;cc.strokeRect(24,22,652,314);const {type,progress:p}=craft;cc.save();cc.shadowColor='#2f482b30';cc.shadowBlur=20;cc.shadowOffsetY=10;
if(type==='sand'){const r=90,rough=(1-p/100)*10;cc.translate(350,165);cc.rotate(now*.0002);if(propArt.complete&&propArt.naturalWidth){drawPart(cc,craft.id,0,0,craft.id==='bigwheel'?1.48:2);cc.save();cc.globalAlpha=(1-p/100)*.65;for(let i=0;i<46;i++){const a=i*Math.PI/23;line(cc,Math.cos(a)*92,Math.sin(a)*92,Math.cos(a)*(92+rough),Math.sin(a)*(92+rough),'#c9a164',2)}cc.restore()}else{const pts=[];for(let i=0;i<64;i++){const a=i*Math.PI/32,rr=r+Math.sin(i*2.3)*rough;pts.push([Math.cos(a)*rr,Math.sin(a)*rr])}poly(cc,pts,'#bf8d53','#997142');circle(cc,0,0,77,null,'#ddb887');circle(cc,0,0,65,null,'#b48145');circle(cc,0,0,48,null,'#d5a469');circle(cc,0,0,10,'#5f684c','#d7b175')}cc.restore();if(!craft.ready){cc.save();cc.translate(craft.tool.x,craft.tool.y);cc.rotate(-.4);wood(cc,-27,-11,54,22,6);cc.restore()}}
else if(type==='hammer'){wood(cc,203,165,295,60,20);craft.pegs.forEach((v,i)=>{const x=245+i*70;wood(cc,x-6,133+v*14,12,36-v*14,3);circle(cc,x,134+v*14,9,v===2?'#d7b67c':'#ead19d','#8f784e');if(i===craft.pegs.findIndex(v=>v<2)){circle(cc,x,165,27,null,'#b8593d')}});cc.restore()}
else if(type==='align'){drawPart(cc,craft.id,350,165,craft.id==='waterwheel'?.92:1.5,craft.angle);cc.restore();line(cc,350,52,350,83,'#b75036',5);cc.save();cc.translate(350,165);cc.rotate(craft.angle);line(cc,0,-86,0,-110,'#b75036',5);cc.restore();circle(cc,350,165,112,null,'#e4d196')}
else{drawPart(cc,'bucket',350,165,2.3,0);cc.restore();for(let i=0;i<Math.floor(p/10);i++){cc.beginPath();cc.ellipse(350,130+i*9,66,15,0,0,Math.PI*2);cc.strokeStyle=i%2?'#d4b771':'#b59b61';cc.lineWidth=3;cc.stroke()}if(!craft.ready){cc.setLineDash([4,6]);circle(cc,350,165,115,null,'#b6c2a1');cc.setLineDash([])}}
for(const q of craft.dust){q.x+=q.vx;q.y+=q.vy;q.vy+=.1;q.life-=.015;cc.globalAlpha=Math.max(q.life,0);cc.fillStyle='#a87940';cc.fillRect(q.x,q.y,5,2)}cc.globalAlpha=1;craft.dust=craft.dust.filter(q=>q.life>0);if(craft.ready){cc.fillStyle='#ecedc6';cc.font='16px Microsoft YaHei';cc.textAlign='center';cc.fillText('✓ 加工完成',350,305);cc.textAlign='left'}}
function closeCraft(){craft=null;$('craft-dialog').close()}
$('craft-close').onclick=closeCraft;$('craft-dialog').addEventListener('cancel',()=>{craft=null});$('craft-done').onclick=()=>{if(!craft?.ready)return;const id=craft.id;if(!state.crafted.includes(id))state.crafted.push(id);closeCraft();selected=id;refresh();$('guide-copy').textContent='做得不错！'+parts[id].name+'已经拿在手里，放到工作台上吧。';say('亲手做成了'+parts[id].name+'。以后可以直接拿取。')};
$$('[data-project]').forEach(b=>b.onclick=()=>changeProject(b.dataset.project));$$('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('run-button').onclick=run;$('clear-button').onclick=()=>{remember();stop();if(state.project==='free')state.free=[];else state.assemblies[state.project]={};selected=null;refresh();$('guide-copy').textContent='零件收回了，加工过的零件都还在。重新拼一个吧。'};$('undo-button').onclick=()=>{if(!history.length)return;stop();Object.assign(state,JSON.parse(history.pop()));selected=null;refresh()};$('sound-toggle').onclick=()=>{state.muted=!state.muted;refresh();if(!state.muted)sound('bell')};$('help-button').onclick=()=>$('help-dialog').showModal();$('help-close').onclick=$('help-start').onclick=()=>$('help-dialog').close();$('result-close').onclick=$('result-retry').onclick=()=>$('result-dialog').close();$('result-next').onclick=()=>{$('result-dialog').close();const next=projects[state.project].next;changeProject(next==='free'&&state.completed.length<3?['car','water','bell'].find(id=>!state.completed.includes(id)):next)};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();refresh()}});window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){selected=null;stop();refresh()}});
refresh();$('guide-copy').textContent=projects[state.project].prompt;requestAnimationFrame(frame);
})();
