import * as T from './vendor/three/three.module.js?v=9a3955b709d6';
import {OrbitControls} from './vendor/three/OrbitControls.js?v=9a3955b709d6';
import {box,materials} from './palace-models.mjs?v=9a3955b709d6';
import {makeWork,disposeGroup} from './atelier-models.mjs?v=9a3955b709d6';
import {powered} from './atelier-data.mjs?v=9a3955b709d6';
export class WorkStage{
 constructor(canvas){this.canvas=canvas;this.renderer=new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMappingExposure=1.35;this.scene=new T.Scene();this.scene.background=new T.Color('#173c40');this.camera=new T.OrthographicCamera(-6,6,5,-5,.1,100);this.camera.position.set(10,9,13);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,1.4,0);this.controls.enableDamping=true;this.controls.enablePan=false;this.controls.minZoom=.6;this.controls.maxZoom=3;this.controls.maxPolarAngle=Math.PI*.46;this.scene.add(new T.HemisphereLight(0xc4e8d8,0x394432,2.6));const light=new T.DirectionalLight(0xffddaa,4);light.position.set(-6,12,8);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-10,right:10,top:10,bottom:-10});light.shadow.bias=-.001;this.scene.add(light);const rim=new T.DirectionalLight(0x90cdda,2);rim.position.set(8,6,-7);this.scene.add(rim);this.floor=new T.Group();const m=materials();box(this.floor,m.stone,22,.15,22,0,-.18);this.scene.add(this.floor);const grid=new T.GridHelper(18,36,0x779281,0x38585a);grid.position.y=-.08;grid.material.transparent=true;grid.material.opacity=.24;this.floor.add(grid);this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.ro=new ResizeObserver(()=>this.resize());this.ro.observe(canvas);this.resize();this.last=0;this.time=0;this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame)}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);this.camera.left=-5.5*w/h;this.camera.right=5.5*w/h;this.camera.top=5.5;this.camera.bottom=-5.5;this.camera.updateProjectionMatrix()}
 setGroup(group){this.select(null);disposeGroup(this.group);this.group=group;this.scene.add(group)}
 setWork(w,exploded=false){this.work=w;this.time=0;this.lastBellBeat=null;this.active=w?powered(w):new Set();this.setGroup(w?makeWork(w,materials(),exploded):new T.Group());this.drawLinks();this.focus()}
 drawLinks(){disposeGroup(this.lines);this.lines=new T.Group();this.scene.add(this.lines);if(!this.work)return;for(const [a,b]of this.work.links){const A=this.group.children.find(p=>p.userData.partId===a),B=this.group.children.find(p=>p.userData.partId===b);if(!A||!B)continue;const mat=new T.LineBasicMaterial({color:0xd8c188,transparent:true,opacity:.7});const line=new T.Line(new T.BufferGeometry().setFromPoints([A.position,B.position]),mat);line.userData={a:A,b:B};this.lines.add(line)}}
 focus(){if(!this.group?.children.length)return;this.group.updateMatrixWorld(true);const b=new T.Box3().setFromObject(this.group),c=b.getCenter(new T.Vector3()),size=b.getSize(new T.Vector3());this.controls.target.copy(c);this.camera.position.copy(c).add(new T.Vector3(10,9,13));this.camera.zoom=Math.max(.45,Math.min(1.4,7/Math.max(size.x,size.y,size.z,3)));this.camera.updateProjectionMatrix();this.controls.update()}
 pick(e){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const h=this.ray.intersectObjects(this.group?.children||[],true)[0];if(!h)return null;let o=h.object;while(o.parent&&o.parent!==this.group)o=o.parent;return o}
 ground(e,y=0){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);return this.ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),-y),new T.Vector3())}
 select(id){if(this.outline){this.outline.geometry.dispose();this.outline.material.dispose();this.scene.remove(this.outline);this.outline=null}const o=this.group?.children.find(o=>o.userData.partId===id);if(o){this.outline=new T.BoxHelper(o,0xe9d38e);this.scene.add(this.outline)}}
 frame(now){const dt=Math.min(.04,(now-this.last)/1000||0);this.last=now;if(!this.paused&&!document.hidden){this.time+=dt;this.controls.update();if(this.running&&this.work){let hasRingingBell=false;for(const g of this.group.children){if(!this.active.has(g.userData.partId))continue;const n=this.work.nodes.find(n=>n.id===g.userData.partId),type=g.userData.type;if(g.userData.rotor)g.userData.rotor.rotation[g.userData.axis]=this.time*(type==='waterwheel'?.65:1.2);if(type==='basket')g.position.y=n.y+.35*(1-Math.cos(this.time));if(type==='bell'){g.rotation.z=Math.sin(this.time*3)*.18;hasRingingBell=true}if(type==='striker')g.rotation.z=Math.sin(this.time*3)*.25;if(type==='leg')g.rotation.z=Math.sin(this.time*2)*.35}if(hasRingingBell){const beat=Math.floor(this.time*3/Math.PI);if(beat!==this.lastBellBeat){this.lastBellBeat=beat;this.onBell?.()}}this.lines?.children.forEach(l=>{l.geometry.setFromPoints([l.userData.a.position,l.userData.b.position])})}this.onFrame?.(dt,this.time);this.outline?.update();this.renderer.render(this.scene,this.camera)}this.raf=requestAnimationFrame(this.frame)}
 capture(work,{width=900,height=750,exploded=false}={}){const old=this.work,running=this.running,paused=this.paused;this.running=false;this.setWork(work,exploded);this.renderer.setPixelRatio(1);this.renderer.setSize(width,height,false);this.camera.left=-5.5*width/height;this.camera.right=5.5*width/height;this.camera.top=5.5;this.camera.bottom=-5.5;this.camera.updateProjectionMatrix();this.controls.update();this.renderer.render(this.scene,this.camera);const copy=document.createElement('canvas');copy.width=width;copy.height=height;copy.getContext('2d').drawImage(this.canvas,0,0,width,height);this.setWork(old);this.running=running;this.paused=paused;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));this.resize();return copy}
 dispose(){cancelAnimationFrame(this.raf);this.ro.disconnect();this.controls.dispose();disposeGroup(this.group);disposeGroup(this.lines);disposeGroup(this.floor);this.renderer.dispose()}
}
