import * as revision from '../story-revision.mjs';
import {PART_GROUPS,TOTAL_PARTS} from '../rocket-atlas-model.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {ERA_SCENES} from '../era-stories.mjs';
import * as data from '../chronicle-data.mjs';import * as parts from '../atelier-data.mjs';
// Controller integration with DOM doubles; no browser layout or rendering claims.
async function boot(){const ids=new Map(),elements=[],saved=new Map();
 const match=(e,s)=>s.startsWith('#')?e.attrs.id===s.slice(1):s.startsWith('[data-')?s.slice(1,-1)in e.attrs:e.tag===s;
 class Element{constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.dataset={};this.children=[];this.events={};this.open=false;this.hidden='hidden'in attrs;this.style={};this.value='';this.textContent='';this.disabled='disabled'in attrs;this.classList={add(){},remove(){},toggle(){}};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;if(attrs.id)ids.set(attrs.id,this);elements.push(this)}set innerHTML(s){this.html=s;this.children=parse(s)}get innerHTML(){return this.html||''}addEventListener(k,f){(this.events[k]??=[]).push(f)}showModal(){assert.equal(this.open,false,'dialog should only open once');this.open=true}close(){this.open=false;this.events.close?.forEach(f=>f())}querySelector(s){return this.children.find(e=>match(e,s))}querySelectorAll(s){return this.children.filter(e=>match(e,s))}closest(s){return match(this,s)?this:null}insertAdjacentHTML(_,html){this.children.push(...parse(html))}getContext(){return {drawImage(){}}}animate(){return {}}}
 function parse(html){return [...html.matchAll(/<(?!\/)([\w-]+)\b([^>]*)>/g)].map(m=>{const attrs=Object.fromEntries([...m[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g)].map(a=>[a[1],a[2]||'']));return new Element(m[1],attrs)})}
 parse(fs.readFileSync('index.html','utf8'));
 class Store{constructor(status){this.status=status;this.pending={}}async init(){return true}save(k,v){saved.set(k,structuredClone(v));return Promise.resolve(true)}get(k){return saved.get(k)||null}all(){return [...saved].map(([key,value])=>({key,value}))}}
 class World{constructor(){this.mode='overview';this.modules=[]}configureNetwork(){}setQuality(){}showThrone(){}applyState(){}setMode(m){this.mode=m}exhibitWorks(){}descend(step,done){step(0);done()}reveal(){}finale(done){done()}}
 class Lab{constructor(c,done){this.c=c;this.onDone=done;ids.get('lab-modal').showModal()}dispose(){ids.get('lab-modal').close()}}
 class Toy{constructor(w){this.work=w;this.stage={resize(){},capture(){return {toDataURL:()=>''}},setWork(){}}}setWork(w){this.work=w}render(){}}
 const doc={getElementById:id=>ids.get(id)||null,querySelectorAll:s=>elements.filter(e=>match(e,s)),createElement:tag=>new Element(tag),hidden:false};
 class Atlas{constructor(c,pick){this.pick=pick;this.filter=-1}setProgress(n){this.chapter=n}resize(){}explode(n){this.target=n}setFilter(n){this.filter=n}fit(){}select(n){this.selected=n}isolate(){}}
 class Audio{unlock(){}setMuted(v){this.muted=v}play(){}pause(){}}
 const sandbox={GameAudio:Audio,...revision,PART_GROUPS,TOTAL_PARTS,RocketAtlas:Atlas,ERA_SCENES,...data,...parts,ChronicleWorld:World,ChronicleLab:Lab,ArchiveStore:Store,Atelier:Toy,readLocal:()=>null,downloadFile(){},makePoster(){},document:doc,window:{addEventListener(){}},console,URL,structuredClone,FormData,Map,Set,Number,String,Math,JSON,setTimeout:()=>1,clearTimeout(){},matchMedia:()=>({matches:false}),localStorage:{setItem(){}},performance:{now:()=>0},fetch(){}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('chronicle.mjs','utf8').replace(/^import .*;\r?\n/gm,''),sandbox);await vm.runInContext('ready',sandbox);return {ids,saved,sandbox,run:s=>vm.runInContext(s,sandbox)}}
test('new controller binds the 2D opening and completes all eight chapters with real progression',async()=>{const b=await boot();await b.run('enter()');assert.equal(b.ids.get('opening-art').hidden,true);assert.equal(b.ids.get('game').hidden,false);for(let i=0;i<8;i++){b.run('startChapter()');if(data.DECISIONS[i]){const choice=b.ids.get('drawer-body').children.find(e=>e.dataset.decision);assert.ok(choice);choice.onclick()}assert.equal(b.ids.get('lab-modal').open,true);b.run(`lab.onDone({passed:true,note:'完成第 ${i+1} 段',value:''})`);assert.equal(b.saved.get('campaign-0').chapter,i+1);if(b.ids.get('drawer').open)b.ids.get('drawer').close()}assert.equal(b.saved.get('campaign-0').known.length,17);assert.equal(b.ids.get('chapter-title').textContent,'此器已成，故事未尽');b.run("showView('network')");assert.equal(b.ids.get('network-panel').hidden,false);assert.equal(b.ids.get('network').children.filter(e=>e.dataset.node).length,17)});
test('controller preserves a selected era and exposes return, gallery, sources and settings',async()=>{const b=await boot();b.run('selectedEra=3;eras()');await b.run('enter()');assert.equal(b.saved.get('campaign-3').era,3);assert.ok(b.ids.get('era-year').textContent.includes('慈禧'));b.ids.get('settings').onclick();assert.ok(b.ids.has('export-all'));b.ids.get('drawer').close();b.run('openAtelier()');assert.equal(b.ids.get('atelier-screen').hidden,false);b.ids.get('open-gallery').onclick();assert.equal(b.ids.get('gallery-modal').open,true);assert.ok(b.ids.has('empty-toy'));b.ids.get('gallery-modal').close();b.ids.get('atelier-back').onclick();assert.equal(b.ids.get('game').hidden,false);b.ids.get('sources').onclick();assert.ok(b.ids.get('drawer-body').innerHTML.includes('史实'))});
test('poster reveals difficulty selection, then the retained throne descent enters the atlas',async()=>{const b=await boot();assert.equal(b.ids.get('poster-cover').hidden,false);assert.equal(b.ids.get('opening').hidden,true);b.ids.get('poster-enter').onclick();assert.equal(b.ids.get('opening').hidden,false);assert.ok(!b.ids.get('eras').innerHTML.includes('步步引导'));assert.ok(b.ids.get('eras').innerHTML.includes('叶赫那拉氏'));b.run('selectedEra=3;eras()');assert.ok(b.ids.get('era-line').textContent.includes('相同的动手体验'));await b.run('enter()');assert.equal(b.ids.get('poster-cover').hidden,true);assert.equal(b.ids.get('selection-art').hidden,true);assert.equal(b.ids.get('opening-art').hidden,true);assert.equal(b.ids.get('atlas-canvas').hidden,false);assert.equal(b.ids.get('atlas-status').textContent,'0 / 192 件已点亮');b.ids.get('atlas-spread').onclick();assert.equal(b.run('atlas.target'),1);b.ids.get('atlas-reset').onclick();assert.equal(b.run('atlas.target'),0);assert.ok(!b.ids.has('team-panel'))});
test('each alternate ending can be read to completion and replayed without extra progression',async()=>{for(let era=0;era<4;era++){const b=await boot();b.run(`s.era=${era};s.chapter=8;ending()`);for(let i=0;i<4;i++){const html=b.ids.get('drawer-body').innerHTML;assert.ok(html.includes(revision.ENDINGS[era].beats[i][0]));assert.ok(html.includes('架空结局'));assert.ok(html.includes('chibi'));if(i<3)b.ids.get('ending-next').onclick()}assert.ok(b.ids.has('ending-toy'));assert.ok(b.ids.has('ending-era'));b.ids.get('drawer').close();b.run('ending()');assert.ok(b.ids.get('drawer-body').innerHTML.includes(revision.ENDINGS[era].beats[0][0]))}});

test('home reset targets one campaign, preserves other campaigns and artwork, and replays descent',async()=>{const b=await boot();b.saved.set('campaign-1',{...data.freshCampaign(1),entered:true,completed:['measure'],chapter:1});b.saved.set('campaign-0',{...data.freshCampaign(0),entered:true});b.saved.set('work-example',{name:'藏品'});b.saved.set('draft',{name:'草稿'});b.ids.get('home-reset').onclick();assert.equal(b.ids.get('drawer').open,true);assert.ok(b.ids.get('drawer-body').innerHTML.includes('其他人物'));b.run('confirmRestart(1)');await b.ids.get('restart-confirm').onclick();assert.equal(b.saved.get('campaign-1').chapter,0);assert.equal(b.saved.get('campaign-1').entered,true);assert.equal(b.saved.get('campaign-0').entered,true);assert.equal(b.saved.get('work-example').name,'藏品');assert.equal(b.saved.get('draft').name,'草稿');assert.equal(b.ids.get('game').hidden,false);assert.equal(b.ids.get('opening-art').hidden,true)});

test('completed ending unlocks direct reading of other endings without mutating campaigns',async()=>{const b=await boot();b.run('s.era=0;s.chapter=8;ending()');assert.equal(b.ids.get('drawer-body').children.filter(e=>e.dataset.endingView!==undefined).length,0);for(let i=0;i<3;i++)b.ids.get('ending-next').onclick();const choices=b.ids.get('drawer-body').children.filter(e=>e.dataset.endingView!==undefined);assert.equal(choices.length,3);const before=b.run('JSON.stringify(s)');choices.find(e=>e.dataset.endingView==='2').onclick();assert.ok(b.ids.get('drawer-body').innerHTML.includes(revision.ENDINGS[2].beats[0][0]));assert.ok(b.ids.get('drawer-body').innerHTML.includes('朱元璋'));for(let i=0;i<3;i++)b.ids.get('ending-next').onclick();assert.equal(b.ids.get('drawer-body').children.filter(e=>e.dataset.endingView!==undefined).length,3);assert.equal(b.run('JSON.stringify(s)'),before);assert.equal(b.saved.size,0);b.run('ending()');assert.ok(b.ids.get('drawer-body').innerHTML.includes(revision.ENDINGS[0].beats[0][0]))});

test('jade seal gates the descent and can be cancelled or confirmed without double entry',async()=>{const b=await boot();b.ids.get('enter').onclick();assert.equal(b.ids.get('seal-ritual').open,true);assert.equal(b.ids.get('game').hidden,true);b.ids.get('seal-back').onclick();assert.equal(b.ids.get('seal-ritual').open,false);assert.equal(b.saved.size,0);b.ids.get('enter').onclick();await b.run('finishSeal()');assert.equal(b.ids.get('seal-ritual').open,false);assert.equal(b.ids.get('game').hidden,false);assert.equal(b.saved.get('campaign-0').chapter,0);await b.run('finishSeal()');assert.equal(b.saved.size,1)});

test('poster selection highlights character and immediately opens the central seal',async()=>{const b=await boot();b.ids.get('poster-enter').onclick();const poster=b.ids.get('eras').children.find(e=>e.dataset.era==='2');b.ids.get('eras').onclick({target:poster});assert.equal(b.run('selectedEra'),2);assert.equal(b.run('posterChosen'),2);assert.equal(b.ids.get('seal-ritual').open,true);assert.ok(b.ids.get('seal-person').textContent.includes('朱元璋'));b.ids.get('seal-back').onclick();assert.equal(b.ids.get('opening').hidden,false);assert.equal(b.saved.size,0)});
test('complete reset is available on home and requires a separate checkbox confirmation',async()=>{const b=await boot();b.ids.get('complete-reset').onclick();assert.ok(b.ids.get('drawer-body').innerHTML.includes('所有收藏作品'));assert.equal(b.ids.get('reset-everything').disabled,true);await b.ids.get('reset-everything').onclick();assert.equal(b.saved.size,0);b.ids.get('reset-cancel').onclick();assert.equal(b.ids.get('drawer').open,false)});
