import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {ERA_SCENES} from '../era-stories.mjs';
import * as data from '../chronicle-data.mjs';import * as parts from '../atelier-data.mjs';
// Controller integration with DOM doubles; no browser layout or rendering claims.
async function boot(){const ids=new Map(),elements=[],saved=new Map();
 const match=(e,s)=>s.startsWith('#')?e.attrs.id===s.slice(1):s.startsWith('[data-')?s.slice(1,-1)in e.attrs:e.tag===s;
 class Element{constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.dataset={};this.children=[];this.events={};this.open=false;this.hidden='hidden'in attrs;this.style={};this.value='';this.textContent='';this.disabled='disabled'in attrs;this.classList={add(){},remove(){},toggle(){}};for(const [k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;if(attrs.id)ids.set(attrs.id,this);elements.push(this)}set innerHTML(s){this.html=s;this.children=parse(s)}get innerHTML(){return this.html||''}addEventListener(k,f){(this.events[k]??=[]).push(f)}showModal(){assert.equal(this.open,false,'dialog should only open once');this.open=true}close(){this.open=false;this.events.close?.forEach(f=>f())}querySelector(s){return this.children.find(e=>match(e,s))}querySelectorAll(s){return this.children.filter(e=>match(e,s))}closest(s){return match(this,s)?this:null}insertAdjacentHTML(_,html){this.children.push(...parse(html))}getContext(){return {drawImage(){}}}animate(){return {}}}
 function parse(html){return [...html.matchAll(/<(?!\/)([\w-]+)\b([^>]*)>/g)].map(m=>{const attrs=Object.fromEntries([...m[2].matchAll(/([\w-]+)(?:="([^"]*)")?/g)].map(a=>[a[1],a[2]||'']));return new Element(m[1],attrs)})}
 parse(fs.readFileSync('index.html','utf8'));
 class Store{constructor(status){this.status=status;this.pending={}}async init(){return true}save(k,v){saved.set(k,structuredClone(v));return Promise.resolve(true)}get(k){return saved.get(k)||null}all(){return [...saved].map(([key,value])=>({key,value}))}}
 class World{constructor(){this.mode='overview';this.modules=[]}configureNetwork(){}setQuality(){}showThrone(){}applyState(){}setMode(m){this.mode=m}exhibitWorks(){}descend(step,done){step(0);done()}reveal(){}finale(done){done()}}
 class Lab{constructor(c,done){this.c=c;this.onDone=done;ids.get('lab-modal').showModal()}dispose(){ids.get('lab-modal').close()}}
 class Toy{constructor(w){this.work=w;this.stage={resize(){},capture(){return {toDataURL:()=>''}},setWork(){}}}setWork(w){this.work=w}render(){}}
 const doc={getElementById:id=>ids.get(id)||null,querySelectorAll:s=>elements.filter(e=>match(e,s)),createElement:tag=>new Element(tag),hidden:false};
 const sandbox={ERA_SCENES,...data,...parts,ChronicleWorld:World,ChronicleLab:Lab,ArchiveStore:Store,Atelier:Toy,readLocal:()=>null,downloadFile(){},makePoster(){},document:doc,window:{addEventListener(){}},console,URL,structuredClone,FormData,Map,Set,Number,String,Math,JSON,setTimeout:()=>1,clearTimeout(){},matchMedia:()=>({matches:false}),localStorage:{setItem(){}},performance:{now:()=>0},fetch(){}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('chronicle.mjs','utf8').replace(/^import .*;\r?\n/gm,''),sandbox);await vm.runInContext('ready',sandbox);return {ids,saved,sandbox,run:s=>vm.runInContext(s,sandbox)}}
test('new controller binds the 2D opening and completes all eight chapters with real progression',async()=>{const b=await boot();await b.ids.get('enter').onclick();assert.equal(b.ids.get('opening-art').hidden,true);assert.equal(b.ids.get('game').hidden,false);for(let i=0;i<8;i++){b.run('startChapter()');if(data.DECISIONS[i]){const choice=b.ids.get('drawer-body').children.find(e=>e.dataset.decision);assert.ok(choice);choice.onclick()}assert.equal(b.ids.get('lab-modal').open,true);b.run(`lab.onDone({passed:true,note:'完成第 ${i+1} 段',value:''})`);assert.equal(b.saved.get('campaign-0').chapter,i+1);if(b.ids.get('drawer').open)b.ids.get('drawer').close()}assert.equal(b.saved.get('campaign-0').known.length,17);assert.equal(b.ids.get('chapter-title').textContent,'此器已成，故事未尽');b.run("showView('network')");assert.equal(b.ids.get('network-panel').hidden,false);assert.equal(b.ids.get('network').children.filter(e=>e.dataset.node).length,17)});
test('controller preserves a selected era and exposes return, gallery, sources and settings',async()=>{const b=await boot();b.run('selectedEra=3;eras()');await b.ids.get('enter').onclick();assert.equal(b.saved.get('campaign-3').era,3);assert.ok(b.ids.get('era-year').textContent.includes('慈禧'));b.ids.get('settings').onclick();assert.ok(b.ids.has('export-all'));b.ids.get('drawer').close();b.run('openAtelier()');assert.equal(b.ids.get('atelier-screen').hidden,false);b.ids.get('open-gallery').onclick();assert.equal(b.ids.get('gallery-modal').open,true);assert.ok(b.ids.has('empty-toy'));b.ids.get('gallery-modal').close();b.ids.get('atelier-back').onclick();assert.equal(b.ids.get('game').hidden,false);b.ids.get('sources').onclick();assert.ok(b.ids.get('drawer-body').innerHTML.includes('史实'))});
