const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),G=require('../palace-data.js');
// Controller integration only. Real Three.js geometry is tested separately;
// these DOM doubles do not claim browser rendering or frame-rate coverage.
function boot(){const ids=new Map(),elements=[],storage=new Map(),intervals=new Map();let timer=0;
 class Element{constructor(tag,attrs={}){this.tag=tag;this.attrs=attrs;this.dataset={};this.children=[];this.style={};this.events={};this.open=false;this.hidden=false;this.value='';this.width=240;this.height=170;this.classes=new Set((attrs.class||'').split(' '));this.classList={add:(...x)=>x.forEach(k=>this.classes.add(k)),remove:(...x)=>x.forEach(k=>this.classes.delete(k)),toggle:(k,v)=>v?this.classes.add(k):this.classes.delete(k)};for(const k in attrs)if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=attrs[k];if(attrs.id)ids.set(attrs.id,this);elements.push(this)}set innerHTML(s){for(const c of this.children){const i=elements.indexOf(c);if(i>=0)elements.splice(i,1)}this.children=parse(s);this.html=s}get innerHTML(){return this.html||''}setAttribute(k,v){this.attrs[k]=v}addEventListener(k,f){(this.events[k]??=[]).push(f)}emit(k,e={}){const ev={preventDefault(){},target:this,detail:0,...e};for(const f of this.events[k]||[])f(ev);if(this['on'+k])this['on'+k](ev)}click(){if(!this.disabled)this.emit('click')}querySelector(s){return this.children.find(x=>match(x,s))||null}querySelectorAll(s){return this.children.filter(x=>match(x,s))}showModal(){this.open=true}close(){this.open=false}getContext(){return {clearRect(){},drawImage(){}}}append(e){this.children.push(e)}}
 function parse(s){const stack=[],all=[];for(const m of s.matchAll(/<(\/?)([\w-]+)\b([^>]*)>/g)){if(m[1]){if(stack.length)stack.pop();continue}const attrs=Object.fromEntries([...m[3].matchAll(/([\w-]+)="([^"]*)"/g)].map(a=>[a[1],a[2]])),e=new Element(m[2],attrs);all.push(e);if(stack.length)stack[stack.length-1].children.push(e);if(!['input','img','br','link','meta','hr'].includes(m[2]))stack.push(e)}return all}
 function match(e,s){if(s.startsWith('.'))return e.classes.has(s.slice(1));if(s.startsWith('#'))return e.attrs.id===s.slice(1);const a=s.match(/^\[([^=\]]+)\]$/);if(a)return a[1] in e.attrs;return e.tag===s}
 parse(fs.readFileSync('palace-v2.html','utf8'));
 const body=new Element('body'),doc={body,hidden:false,getElementById:id=>ids.get(id),querySelectorAll:s=>elements.filter(e=>match(e,s)),querySelector:s=>elements.find(e=>match(e,s)),createElement:t=>new Element(t),addEventListener(){}};
 class World{configureNetwork(){}setQuality(){}applyState(){}setMode(){}select(){}reveal(){}inspect(){}highlightTech(){}beginCeremony(){}ceremonyStep(){}finale(){}}
 class Portraits{draw(c){assert.ok(c,'portrait has an actual canvas target')}}
 class Bench{constructor(c,opts){this.opts=opts;this.progress=0;this.quality=1}start(){this.progress=0;this.opts.onProgress(0)}assist(){this.progress=Math.min(100,this.progress+25);this.opts.onProgress(this.progress)}stop(){}}
 const win={addEventListener(){}},sandbox={window:win,document:doc,console,Math,Set,Map,Object,JSON,String,Number,performance:{now:()=>0},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>++timer,clearTimeout(){},setInterval:f=>{intervals.set(++timer,f);return timer},clearInterval:id=>intervals.delete(id),PalaceWorld:World,PropPortraits:Portraits,CraftBench:Bench};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('palace-data.js','utf8'),sandbox);const code=fs.readFileSync('palace.mjs','utf8').replace(/^import .*;\r?\n/gm,'');vm.runInContext(code,sandbox);
 const get=()=>JSON.parse(storage.get('tiangong-palace-v2'));
 function click(id){assert.ok(ids.has(id),'missing button '+id);ids.get(id).click()}
 function build(){assert.equal(ids.get('craft-modal').open,true);for(let i=0;i<4;i++)click('craft-assist');assert.equal(ids.get('craft-submit').disabled,false);click('craft-submit')}
 function found(){click('enter-era');assert.equal(get().phase,'founding');ids.get('imperial-seal').emit('keydown',{key:'Enter'});const f=[...intervals.values()][0];for(let i=0;i<5;i++)f();assert.equal(get().phase,'playing')}
 return {ids,elements,get,click,build,found};
}
test('palace controller establishes the hall, then builds and persists the first real module',()=>{const b=boot();b.found();b.click('module-build');b.build();assert.ok(b.get().modules[0]);assert.equal(b.get().months,2);assert.equal(b.ids.get('module-count').textContent,'1 / 8 已成')});
test('complete controller path from opening through resources, events, technologies, and ending',()=>{const b=boot();b.found();for(let i=0;i<250;i++){const s=b.get();if(s.phase==='victory'){assert.equal(Object.keys(s.modules).length,8);return}assert.equal(s.phase,'playing');if(s.pendingEvent!==null){const choice=b.elements.find(e=>e.dataset.choice==='1');assert.ok(choice);choice.click();continue}const next=G.nextStep(s),q=next.type==='tech'?G.quote(s,next.id):{coins:next.type==='module'?12:next.type==='system'?5:10,months:next.type==='system'?1:2,crew:2};if(!G.canSpend(s,q)){b.click('side-halls');b.click('rest-halls');b.ids.get('library-modal').close();continue}b.click('next-action');if(next.type==='tech')b.click('trial-normal');if(next.type==='module')b.click('module-build');if(next.type==='system')b.click('system-test');b.build()}assert.fail('controller did not reach ending')});
test('readable technology view binds all 58 nodes and four systems',()=>{const b=boot();b.found();b.elements.find(e=>e.dataset.mode==='tech').click();assert.equal(b.elements.filter(e=>e.dataset.node).length,58);assert.equal(b.elements.filter(e=>e.dataset.system).length,4);const final=b.elements.find(e=>e.dataset.final);assert.equal(typeof final.onclick,'function')});
