const test=require('node:test'),assert=require('node:assert/strict'),G=require('../palace-data.js');
function found(era=0){const s=G.fresh(era);assert.equal(G.establish(s),true);return s}
function pending(s){if(s.pendingEvent!==null)assert.equal(G.chooseEvent(s,1).ok,true)}
function play(era=0){const s=found(era);for(let count=0;count<240;count++){pending(s);const next=G.nextStep(s);assert.ok(next,'campaign must have a next action');let q;if(next.type==='tech')q=G.quote(s,next.id,'steady');else q={coins:next.type==='module'?12:next.type==='system'?5:10,months:next.type==='system'?1:2,crew:2};if(!G.canSpend(s,q)){assert.equal(G.rest(s).ok,true,'resupply must be affordable');continue}let r;if(next.type==='tech')r=G.trial(s,next.id,'steady',1);if(next.type==='module')r=G.buildModule(s,next.id,1);if(next.type==='system')r=G.validateSystem(s,next.id,1);if(next.type==='final')r=G.finish(s,1);assert.equal(r.ok,true,JSON.stringify(r));assert.notEqual(s.phase,'ended','recommended play should finish comfortably');if(s.phase==='victory')return s}throw new Error('campaign exceeded action limit')}
test('network is a 58-node acyclic cross-branch graph with sources and four era states',()=>{assert.equal(G.nodes.length,58);const visited=new Set(),active=new Set();function visit(id){assert.ok(G.nodeById[id],id);assert.ok(!active.has(id),'cycle at '+id);if(visited.has(id))return;active.add(id);for(const d of G.nodeById[id].deps)visit(d);active.delete(id);visited.add(id)}for(const n of G.nodes){visit(n.id);assert.equal(n.eraLevels.length,4);assert.ok(G.sources[n.source]?.url.startsWith('https://'));assert.ok(n.history.includes('游戏化推演'))}assert.ok(G.nodes.some(n=>n.deps.some(id=>G.nodeById[id].branch!==n.branch)))});
test('founding is the only permitted first operation',()=>{const s=G.fresh(),copy=JSON.stringify(s);assert.equal(G.rest(s).ok,false);assert.equal(G.trial(s,'artisan').ok,false);assert.equal(G.buildModule(s,0).ok,false);assert.equal(G.upgrade(s,0).ok,false);assert.equal(JSON.stringify(s),copy);assert.equal(G.establish(s),true);assert.equal(G.establish(s),false);assert.equal(s.months,0);assert.equal(Object.keys(s.modules).length,0)});
test('eras share topology but have different initial capabilities',()=>{const counts=G.eras.map((_,i)=>found(i).known.length);assert.equal(new Set(counts).size,4);assert.ok(counts[0]<counts[1]&&counts[1]<counts[2]&&counts[2]<counts[3]);assert.ok(G.moduleReady(found(),0))});
for(let i=0;i<4;i++)test(G.eras[i].name+' can complete every module and the final trial through recommended play',()=>{const s=play(i);assert.equal(s.phase,'victory');assert.equal(Object.keys(s.modules).length,8);assert.equal(Object.keys(s.systems).length,4);assert.ok(s.months<210);assert.ok(s.finalReliability>=90);const copy=G.sanitize(JSON.parse(JSON.stringify(s)));assert.equal(copy.phase,'victory');assert.deepEqual(copy.modules,s.modules);assert.deepEqual(copy.known,s.known)});
test('normal trials block missing dependencies without spending resources',()=>{const s=found(),before=JSON.stringify(s);assert.equal(G.trial(s,'correction','steady',1).ok,false);assert.equal(JSON.stringify(s),before)});
test('forced failure points to a concrete missing capability and preserves a cross-run diagnosis',()=>{const s=found(),r=G.trial(s,'correction','steady',1,true,.9);assert.equal(r.type,'failure');assert.ok(G.missing(s,'correction').includes(r.bottleneck));assert.equal(s.failures,1);assert.equal(s.legacy.length,1);const next=G.fresh(2,s.legacy);assert.equal(next.legacy.length,1);assert.equal(next.known.length,0);assert.equal(next.months,0)});
test('partial work is retained and can be made reliable on the next trial',()=>{const s=found(),id=G.nodes.find(n=>G.status(s,n.id)==='ready').id;const r=G.trial(s,id,'rush',.4,false,.9);assert.equal(r.type,'partial');assert.equal(s.reliability[id],55);assert.equal(G.trial(s,id,'steady',1).type,'success')});
test('event zero remains pending and cannot be bypassed by a new paid action',()=>{const s=found();s.pendingEvent=0;const before=s.coins;assert.equal(G.rest(s).ok,false);assert.equal(G.buildModule(s,0).ok,false);assert.equal(s.coins,before);assert.equal(G.chooseEvent(s,1).ok,true);assert.equal(s.pendingEvent,null)});
test('resources never become negative and time limit ends a run',()=>{const s=found();s.coins=0;assert.equal(G.upgrade(s,0).ok,false);assert.equal(G.buildModule(s,0).ok,false);assert.equal(s.coins,0);s.months=237;assert.equal(G.rest(s).ok,true);assert.equal(s.phase,'ended');assert.equal(G.rest(s).ok,false)});
test('historical toy workshop rewards are once per project in each run',()=>{const s=found(),money=s.coins;assert.equal(G.claimWorkshop(s,['car','water','bell']),3);assert.equal(s.coins,money+36);assert.equal(G.claimWorkshop(s,['car','water','bell']),0)});
test('modular checks prevent duplicate builds and premature final completion',()=>{const s=found();assert.equal(G.buildModule(s,7).ok,false);assert.equal(G.finish(s).ok,false);assert.equal(G.buildModule(s,0).ok,true);const money=s.coins;assert.equal(G.buildModule(s,0).ok,false);assert.equal(s.coins,money)});
test('save validation rejects invalid versions, contains malformed values, and strips injected labels',()=>{assert.equal(G.sanitize({version:1}),null);const s=G.sanitize({version:2,era:0,phase:'victory',coins:-100,crew:NaN,known:['wood','wood','unlisted'],breakthroughs:{},records:[null,{title:4},{title:'ok',text:'saved'}],pendingEvent:99,systems:{drive:{quality:99}}});assert.equal(s.phase,'playing');assert.equal(s.coins,0);assert.deepEqual(s.known,['wood']);assert.equal(s.records.length,1);assert.equal(s.pendingEvent,null);assert.equal(Object.keys(s.systems).length,0)});
test('repeated verification and optional base development produce higher endings',()=>{const s=play(3);s.coins=1000;for(const t of G.systems)assert.equal(G.validateSystem(s,t.id,1).ok,true);assert.equal(G.finish(s,1).ending,'工程可复制');for(let i=0;i<5;i++){assert.equal(G.upgrade(s,i).ok,true);assert.equal(G.upgrade(s,i).ok,true)}assert.equal(G.finish(s,1).ending,'时代跃迁');s.support=20;assert.equal(G.finish(s,1).ending,'代价过高')});
